### PR TITLE
fix: update the flag due to using higher version of csi livenessprobe

### PR DESCRIPTION
**Pull request by ZeroMagic**
**Reason for Change**:

The version of CSI livenessprobe are different from AzureDiskFile CSI Drivers and Secret Store CSI Drivers currently. Tested the AzureDiskFile CSI Drivers with CSI livenessprobe v2.0.0. They worked well. So here make a change that has the minimum impact on the code. 
Later I will update the CSI livenessprobe version in AzureDiskFileCSI Drivers repo.
/cc @feiskyer  @andyzhangx 

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Review by chewong — DISMISSED** [review]
Could you run `make generate`?

**Comment by mboersma** [comment]
@chewong I ran `make generate` and pushed the commit. 🤞

**Pull request merged**
