### PR TITLE
feat: Support kubectl port-forward with k8s 1.15 on Windows nodes

### LINKED ISSUE #1461: Fix `kubectl port-forward` for Windows on K8s 1.15
**Describe the bug**
The pause image deployed by AKS-Engin on Windows nodes should include `wincat`. This is needed for `kubectl port-forward` to work on Kubernetes 1.15+

**AKS Engine version**
all

**Kubernetes version**
1.15+

**Additional context**

Reference:  https://github.com/kubernetes/kubernetes/pull/75479

### PR DESCRIPTION
**Pull request by PatrickLang**
**Reason for Change**:
A new pause image is needed to make `kubectl port-forward` work for Windows pods in 1.15. This won't fix it for <= 1.14.

**Issue Fixed**:
resolves #1461 

cc @jchauncey

### CODE REVIEW

**Comment by jackfrancis** [comment]
Should we include a Windows + >= 1.15 unit test to prove and protect this functionality?

**Comment by PatrickLang** [comment]
sure, can add a test but wanted to get some results and make sure it doesn't break anything else first

**Comment by PatrickLang** [comment]
Ok, tests added. Review comments welcome :)

**Comment by PatrickLang** [comment]
kube-dashboard is not happy in 1.15. it took 3 tries for it to come up

**Pull request merged**
