### PR TITLE
chore: update go toolchain to v1.15.3

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/deis/docker-go-dev/releases/tag/v1.28.4

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

Looks like an unrequested update to `packer` broke VHD building. Will fix.

**Comment by mboersma** [comment]
/hold cancel

`packer` is pinned now at v1.6.1.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by mboersma** [comment]
I updated `DEIS_GO_DEV_IMAGE` on upstream Jenkins to v1.28.4. Let me know if we see any issues, please.

**Pull request merged**
