### PR TITLE
debugging 'make ensure-generated' false positives in CI

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
A way to test why `make ensure-generated` succeeds when it shouldn't in CI, as described in #1318.

It uses [`shfmt`](https://github.com/mvdan/sh) to raise an error if shell scripts aren't formatted consistently, and reformatting all the shell scripts causes a massive and obvious delta to `templates_generated.go` which *should* fail the PR since that's not included here.

```shell
$ make ensure-generated
...
< echo "<searchDomainRealmPassword>" | realm join -U <searchDomainRealmUser>@$(echo "<searchDomainName>" | tr /a-z/ /A-Z/) $(echo "<searchDomainName>" | tr /a-z/ /A-Z/)
---
> echo "<searchDomainRealmPassword>" | realm join -U $(echo "<searchDomainName>" | tr /a-z/ /A-Z/) <searchDomainRealmUser >@$(echo "<searchDomainName>" | tr /a-z/ /A-Z/)
+ echo 'go generate produced changes that were not already present.'
go generate produced changes that were not already present.
+ echo 'Make sure you include generated assets in your commit.'
Make sure you include generated assets in your commit.
+ exit 1
+ rm -rf /var/folders/tq/2cdy0tqn6g556ny243rx3p840000gn/T/tmp.M5TYhoHW
make: *** [ensure-generated] Error 1
```

(We could merge the `shfmt` change if we like it, but that's not the current goal.)

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
Both the `ensure-generated.sh` script and my attempt at a `git diff` replacement **succeeded** in the `make ensure-generated` step in Azure DevOps. Both strategies correctly fail when run locally against this commit. I'm not seeing what the difference is.

**Comment by CecileRobertMichon** [comment]
@mboersma could it have anything to do with how devops handles checking out the changes? Does it merge the changes with master before running the build?

**Comment by mboersma** [comment]
It does merge with master before running the build. But even in that case, `templates_generated.go` wouldn't be up-to-date so `make ensure-generated` should fail...unless I'm confused, which is entirely possible.

**Comment by mboersma** [comment]
This served its purpose: to highlight the underlying problem in #1318 and to work out the fix in #1501.

**Pull request closed without merging**
