### PR TITLE
chore: Upgrade CNI to v1.1.8

### PR DESCRIPTION
**Pull request by pjohnst5**
**Reason for Change**:
updated cni version to latest release - 1.1.8.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by pjohnst5** [comment]
@sozercan can you upload the artiifacts to acs mirror?

windows - https://acnreleaseartifacts.azureedge.net/azure-cni/v1.1.8/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.1.8.zip

Linux - https://github.com/Azure/azure-container-networking/releases/download/v1.1.8/azure-vnet-cni-linux-amd64-v1.1.8.tgz

**Comment by pjohnst5** [comment]
/assign @jackfrancis @mboersma

can you run azp e2e?

@sozercan uploaded artifacts to acs mirror, tests should pass now

**Review by jackfrancis — APPROVED** [review]
/lgtm

thanks @pjohnst5!

**Comment by jackfrancis** [comment]
@jchauncey @sozercan can you ping when the new 1.1.8 artifact is available at the standard URI?

thanks!

**Comment by sozercan** [comment]
@jackfrancis they are already published. is there a problem with the urls?

**Comment by jackfrancis** [comment]
@sozercan Re-running the VHD CI jobs, perhaps they weren't published yet on Wednesday evening when the original test jobs ran

**Comment by jackfrancis** [comment]
@pjohnst5 could you kindly rebase against current master to pick up changes made to the Windows VHD pipeline since this PR was created?

**Pull request merged**
