### PR TITLE
feat: add support for Kubernetes v1.19.3

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1192

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

~~Publishing is not yet complete, so tests will fail for the time being.~~

### CODE REVIEW

**Review by jackfrancis — DISMISSED** [review]
/lgtm

**Comment by jackfrancis** [comment]
cc @jchauncey @sozercan it looks like the 1.19.3 artifacts aren't yet online

**Comment by sozercan** [comment]
@jackfrancis checking

**Comment by mboersma** [comment]
This had an LGTM and was just rebased without any changes, so I'm considering it approved and merging.

**Pull request merged**
