### PR TITLE
feat: add new etcd versions, 3.2.25 is default

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

Add October 3.2 and 3.3 releases of etcd.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@mboersma can you kindly add 3.2.25 and 3.3.10 to acs-mirror

**Comment by CecileRobertMichon** [comment]
/hold

you need a newline for / commands to work

**Comment by CecileRobertMichon** [comment]
codecov will work after rebase

/label needs-rebase

**Pull request merged**
