### PR TITLE
fix: #926 Escape servicePrincipalClientSecret in Windows custom script block

### LINKED ISSUE #926: Using special characters in client_secret will break windows node pool creation
**Is this a request for help?**: No.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**: 1.12.6

---

**Kubernetes version**: 1.12.6

**What happened**: When the client secret includes special chars such as "(" and ")", the node provision will fail.

**What you expected to happen**: Node provision to succeed.

**How to reproduce it** (as minimally and precisely as possible): Provision a windows agent pool with specials chars ")" in the service principal client secret.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by PatrickLang**
**Reason for Change**:
The AADClientSecret needs to be escaped in case it contains a special character such as `)`

**Issue Fixed**:
Fixes #926 

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

Not tested, relying on automation to test it

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm pending E2E

**Comment by CecileRobertMichon** [comment]
unit tests are failing @PatrickLang

**Pull request merged**
