### PR TITLE
fix: correcting spelling in documentation

### PR DESCRIPTION
**Pull request by henrykhadass**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
thx @henrykhadass!

**Comment by henrykhadass** [comment]
> thx @henrykhadass!

I was a bit too fast on this one...saw one more thing -> in a new pr

**Pull request merged**
