### PR TITLE
[WIP] chore: update metrics-server to 0.4.2

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR updates the metrics-server implementation to use v0.4.2. See:

https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.4.2

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
metrics-server v0.4.0 includes several breaking changes compared to v0.3.7, see:

https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.4.0

My initial testing suggests that the change to use IP addresses instead of DNS entries has broken the aks-engine certificate generation assumptions:

```
$ kubectl logs metrics-server-844d9574cf-8df9r -n kube-system
E0212 20:15:00.779512       1 pathrecorder.go:107] registered "/metrics" from goroutine 1 [running]:
runtime/debug.Stack(0x1942e80, 0xc000339bc0, 0x1bb58b5)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc000196690, 0x1bb58b5, 0x8)
	/go/pkg/mod/k8s.io/apiserver@v0.19.2/pkg/server/mux/pathrecorder.go:109 +0x86
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc000196690, 0x1bb58b5, 0x8, 0x1e96f00, 0xc0000e38c0)
	/go/pkg/mod/k8s.io/apiserver@v0.19.2/pkg/server/mux/pathrecorder.go:173 +0x84
k8s.io/apiserver/pkg/server/routes.MetricsWithReset.Install(0xc000196690)
	/go/pkg/mod/k8s.io/apiserver@v0.19.2/pkg/server/routes/metrics.go:43 +0x5d
k8s.io/apiserver/pkg/server.installAPI(0xc00000a1e0, 0xc0004b9440)
	/go/pkg/mod/k8s.io/apiserver@v0.19.2/pkg/server/config.go:711 +0x6c
k8s.io/apiserver/pkg/server.completedConfig.New(0xc0004b9440, 0x1f099c0, 0xc0003f4230, 0x1bbdb5a, 0xe, 0x1ef29e0, 0x2cef248, 0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apiserver@v0.19.2/pkg/server/config.go:657 +0xb45
sigs.k8s.io/metrics-server/pkg/server.Config.Complete(0xc0004b9440, 0xc0004a2900, 0xc0004b8480, 0xdf8475800, 0xc92a69c00, 0x0, 0x0, 0xdf8475800)
	/go/src/sigs.k8s.io/metrics-server/pkg/server/config.go:52 +0x312
sigs.k8s.io/metrics-server/cmd/metrics-server/app.runCommand(0xc000144e70, 0xc000100a80, 0x0, 0x0)
	/go/src/sigs.k8s.io/metrics-server/cmd/metrics-server/app/start.go:66 +0x157
sigs.k8s.io/metrics-server/cmd/metrics-server/app.NewMetricsServerCommand.func1(0xc0004f5600, 0xc0004d7200, 0x0, 0x4, 0x0, 0x0)
	/go/src/sigs.k8s.io/metrics-server/cmd/metrics-server/app/start.go:37 +0x33
github.com/spf13/cobra.(*Command).execute(0xc0004f5600, 0xc00012e010, 0x4, 0x4, 0xc0004f5600, 0xc00012e010)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f5600, 0xc000128120, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/go/src/sigs.k8s.io/metrics-server/cmd/metrics-server/metrics-server.go:38 +0xae
I0212 20:15:00.919332       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0212 20:15:00.919355       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0212 20:15:00.919393       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0212 20:15:00.919400       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0212 20:15:00.919417       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0212 20:15:00.919427       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0212 20:15:00.919970       1 secure_serving.go:197] Serving securely on [::]:4443
I0212 20:15:00.920130       1 dynamic_serving_content.go:130] Starting serving-cert::/tmp/apiserver.crt::/tmp/apiserver.key
I0212 20:15:00.920248       1 tlsconfig.go:240] Starting DynamicServingCertificateController
E0212 20:15:00.920853       1 server.go:132] unable to fully scrape metrics: [unable to fully scrape metrics from node k8s-agentpool1-24111246-vmss000001: unable to fetch metrics from node k8s-agentpool1-24111246-vmss000001: Get "https://10.240.0.65:10250/stats/summary?only_cpu_and_memory=true": x509: cannot validate certificate for 10.240.0.65 because it doesn't contain any IP SANs, unable to fully scrape metrics from node k8s-agentpool1-24111246-vmss000000: unable to fetch metrics from node k8s-agentpool1-24111246-vmss000000: Get "https://10.240.0.34:10250/stats/summary?only_cpu_and_memory=true": dial tcp 10.240.0.34:10250: connect: connection refused, unable to fully scrape metrics from node k8s-master-24111246-0: unable to fetch metrics from node k8s-master-24111246-0: Get "https://10.255.255.5:10250/stats/summary?only_cpu_and_memory=true": x509: cannot validate certificate for 10.255.255.5 because it doesn't contain any IP SANs]
I0212 20:15:01.019518       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0212 20:15:01.019518       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
I0212 20:15:01.019571       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
```

**Comment by pierluigilenoci** [comment]
@jackfrancis it might be time to review this PR since the metrics-server version 0.5.0 has also been released which promises interesting performances: 

> This release comes with big improvements in both autoscaling quality and reliability. A 2X improvement to the CPU based scale up time makes horizontal pod autoscaler much more responsive to large load spikes. A default resource requirements that should guarantee reliable support up to 100 node clusters (70 pods per node) out of the box. This is achieved thanks to multiple performance improvements, that allowed an increase of metric collection frequency while keeping the resource requests low.

Ref: https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.5.0

**Comment by pierluigilenoci** [comment]
I created this https://github.com/Azure/aks-engine/issues/4455

**Comment by jackfrancis** [comment]
Obsolete

**Pull request closed without merging**
