### PR TITLE
chore: update cloud-provider-azure components to v0.4.0

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
See https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v0.4.0

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:
This still isn't enabled unless `useCloudControllerManager` is on.

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

Maybe the release hasn't actually made it through the pipeline yet:

```
$ docker pull mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.4.0
Error response from daemon: manifest for mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.4.0 not found: manifest unknown: manifest unknown
```

@jchauncey @feiskyer is this PR too early? 😄

**Comment by feiskyer** [comment]
@mboersma I got some error when build and push the image to MCR. asking @jchauncey for help now

**Comment by feiskyer** [comment]
@mboersma New images have been pushed to

* mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v0.4.0
* mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v0.4.0

Could you help to update the image location? (by the way, v0.3.0 images are also in the same place)

**Comment by jchauncey** [comment]
you duplicated the image names there. 

mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v0.4.0
mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v0.4.0

**Comment by mboersma** [comment]
The simplest thing to do here is to change the MCR base URL to the new one, which appears to be safe (see #2479). Assuming that's correct, let's block this change until after that PR merges.

**Pull request merged**
