### PR TITLE
chore: update AKS distro version to 2019.03.15

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

This VHD contains a new release of walinuxagent.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm pending E2E

**Comment by CecileRobertMichon** [comment]
/hold cancel

:)

**Pull request merged**
