### PR TITLE
fix: change kernel settings based on number of cores

### PR DESCRIPTION
**Pull request by xizhamsft**
**Reason for Change**:

For nodes with more CPU/Memory, the default kernel settings for  ubuntu is not big enough for high-performance server scenarios.

**Issue Fixed**:

We changed the values for ARP table, network connections. These optimizations are applied widely in the industry.

**Requirements**:

- [X ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [X ] includes documentation
- [X] adds unit tests
- [x] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@xizhamsft run `make build` to generate new code based on these changes, and then commit that change

**Comment by jackfrancis** [comment]
If you have trouble you may need to run `cd ./hack/tools && make reload` locally to get the version of code generator tools that github CI uses. Then, run `make build`.

**Comment by devigned** [comment]
If you rebase on the latest master, you no longer need to run `cd ./hack/tools && make reload`. The correct version of `go-bindata` will be installed in `./hack/tools/bin` and will be used in the build.

**Comment by xizhamsft** [comment]
@jackfrancis , @CecileRobertMichon , please take a look. The only e2e failure is exit code 14, unable to start etcd runtime. Should not be related. 
@devigned . Thanks for the tip. Works perfectly.

**Comment by jackfrancis** [comment]
@xizhamsft Can you run some manual tests using > 8 core VM SKUs to validate the desired OS configuration changes?

**Comment by xizhamsft** [comment]
> @xizhamsft Can you run some manual tests using > 8 core VM SKUs to validate the desired OS configuration changes?

Sure. Doing that now.

**Comment by palma21** [comment]
Hey, any eta for this? Pending just a few manual tests right?

**Comment by jackfrancis** [comment]
@xizhamsft could you add a new E2E configuration file under this directory?

- `test/e2e/test_cluster_configs`

You can use `base.json` as a template for a new file, we can call it `large-vm-sku.json`.

Let's replace `Standard_D2_v3` with `Standard_D16_v3`, that way the additional "if greater than 8 cores" configuration will kick in.

Also, please replace the empty `"env": {},` line with:

```
"env": {
		"REGION_OPTIONS": "eastus,westeurope,southeastasia,westus2"
	},
```

This is because we have add'l quota granted to our test subs for Dv3 in those regions.

Thanks!

**Comment by xizhamsft** [comment]
@jackfrancis, @palma21 , a few changes in the new iteration:
1. Included the new test file as suggested by Jack Francis
2. removed the conntrac_max settings since turns out kube-proxy is already setting that value based on number of cores: --conntrack-max-per-core="32768" and the value is large enough for us.
3. tested by copying the kubelet.service file to the node and restart kublet and  verified the settings are applied

**Pull request merged**
