### PR TITLE
chore: remove comments from cilium addons spec

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This saves > 25% against the payload of this yaml

Also includes a reference to `docker.io/cilium/operator:v1.4` instead of `docker.io/cilium/operator:latest` as per @skinny 

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@skinny FYI

**Comment by skinny** [comment]
Also the operator image tag in the current addon is set to :latest which breaks a bit against the 1.4 addon, but I will make a seperate PR for that after the weekend

**Comment by jackfrancis** [comment]
> The yaml payload size is not the biggest deal right?

Actually it is. As long as we use Azure's cloud-init interface, we are bound to data limits. E.g.:

```
Deployment failed. Correlation ID: d8046089-f0da-4856-ad31-2c9cd052c35e. {
  "error": {
    "code": "InvalidParameter",
    "message": "Custom data in OSProfile must be in Base64 encoding and with a maximum length of 87380 characters.",
    "target": "customData"
  }
}
```

**Comment by skinny** [comment]
Ah well that sort of rules out the chance of keeping this file in tact. While you merge this PR, can you also change the `:latest` version of the operator in this file (`image: docker.io/cilium/operator:latest`) to `image: docker.io/cilium/operator:v1.4` to keep stuff running now 1.5 is around the corner

**Comment by jackfrancis** [comment]
@skinny done

**Pull request merged**
