### PR TITLE
fix: Remove the blind mkdir when writing outputs (#1048)

### LINKED ISSUE #1048: Scale command throws error with --api-model=kubernetes.json
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE 
---

**What version of aks-engine?**:
0.34.0
---

**What happened**:
aks-engine scale --api-model=kubernetes.json throws error
`Error: error creating directory '': mkdir : The system cannot find the path specified.`

aks-engine scale --api-model=D:\aks\kubernetes.json works.

**What you expected to happen**:
aks-engine scale works well

**How to reproduce it** (as minimally and precisely as possible):
aks-engine scale --api-model=kubernetes.json

**Anything else we need to know**:
I think it is caused by below code in scale.go: 
```
dir, file := filepath.Split(sc.apiModelPath)
return f.SaveFile(dir, file, b)
```

### PR DESCRIPTION
**Pull request by ocdi**
**Reason for Change**:

This fixes the blind mkdir which fails if it is empty.

**Issue Fixed**:

Fixes #1048 

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@ocdi thanks for the PR. Please change the target branch to `master`. See https://github.com/Azure/aks-engine/blob/master/docs/community/developer-guide.md for more info. 

Also please update the commit message to describe the change and use the `fix: ` prefix to facilitate release notes as described above.

**Comment by ocdi** [comment]
@CecileRobertMichon thanks for your feedback - I have rebased this on master and fixed the title of the PR to match convention, hope this looks better! :-)

**Pull request merged**
