### PR TITLE
docs: update limitations in dualstack docs

### PR DESCRIPTION
**Pull request by aramase**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jsturtevant** [comment]
Should we add a message about windows support https://github.com/Azure/aks-engine/pull/3688?

**Comment by aramase** [comment]
> Should we add a message about windows support #3688?

Dualstack support for windows is added only in 1.19 and I was thinking we can add a message for windows in the doc once 1.19 is released? WDYT?

The validation check needs to be removed only after the [backport](https://github.com/Azure/aks-engine/issues/3568) is complete, right?

**Comment by jsturtevant** [comment]
Sorry I wasn't clear.  I wanted to add a note to make it clear that Windows is not supported at this time because it requires 1.19 and backport to 2004.

**Comment by aramase** [comment]
> Sorry I wasn't clear. I wanted to add a note to make it clear that Windows is not supported at this time because it requires 1.19 and backport to 2004.

Ah, that makes sense. Let me add that.

**Comment by jsturtevant** [comment]
Thanks!

/lgtm

**Pull request merged**
