### PR TITLE
chore: Update Azure CNI to 1.4.0

### PR DESCRIPTION
**Pull request by AbelHu**
**Reason for Change**:

chore: Update Azure CNI to 1.4.0

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by AbelHu** [comment]
@jstur It seems like that the test cases are flaky
https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=6890&view=results
https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=6889&view=results

**Comment by jsturtevant** [comment]
I think the 1.22 job is know flaky @jackfrancis? I've restarted it.

**Comment by jackfrancis** [comment]
@jsturtevant Not the version that we have support for, let's wait to see what the re-run yields.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
