### PR TITLE
feat: add new Azure Switzerland regions

### LINKED ISSUE #1901: SwitzerlandNorth and SwitzerlandWest missing from constants/TLS generation
**Describe the bug**

These two Azure regions GAed a week ago https://azure.microsoft.com/en-us/blog/microsoft-azure-available-from-new-cloud-regions-in-switzerland/ but are absent from 

https://github.com/Azure/aks-engine/blob/master/pkg/helpers/azureconst.go#L11-L67 at this time

resulting in TLS errors went attempting validation. 

As the work for #1897 did not pick these up, it may indicate a bug or edge case in your constant generation scripts

**AKS Engine version**
master

**Kubernetes version**
all

**Additional context**

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
Adds two new Swiss regions.

These are documented as [generally available](https://azure.microsoft.com/en-us/blog/microsoft-azure-available-from-new-cloud-regions-in-switzerland/), but do not show up yet for any subscriptions we've tried in the portal or with `az account list-locations`. So I created the changes manually but have not been able to verify them.

*Edit:* I was able to verify after getting access to the new regions.

**Issue Fixed**:
Fixes #1901

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
I want all my IaaS in Switzerland!

**Comment by mboersma** [comment]
/hold cancel

I have access now in my sub to `switzerlandnorth` and `switzerlandwest` and ran `./pkg/helpers/generate_azure_constants.py` and no diff was created. So this is ready for review.

**Comment by donaldguy** [comment]
I built this branch and successfully made clusters

**Pull request merged**
