### PR TITLE
feat: run unattended upgrades by default

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This is a follow-up PR from #4217. This PR sets the newly added `runUnattendedUpgradesOnBootstrap` LinuxProfile configuration to `true` for Azure cloud environments.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @jadarsie @JesusAlvarezTorres @Michael-Sinz

**Comment by Michael-Sinz** [comment]
I am a bit concerned about the split personality here.  A configuration deployed in public will act differently than that "same" configuration elsewhere.  It makes sense as to why we are doing this but it still is concerning.

I also don't know the config management structure very well so will let others do the deeper review.

**Comment by jackfrancis** [comment]
> I am a bit concerned about the split personality here. A configuration deployed in public will act differently than that "same" configuration elsewhere. It makes sense as to why we are doing this but it still is concerning.
> 
> I also don't know the config management structure very well so will let others do the deeper review.

Strictly speaking, there is already ample precedent for default configuration between Azure Stack (and other custom clouds) and public Azure cloud being different. I think the larger concern is that, arguably, the value of ensuring apt-updated nodes is more pressing in non-public cloud, because it can be more difficult to do that patching manually.

I trust @jadarsie and others understand that, but it makes sense to give those folks time to test these assumptions in their environments first.

Also cc @DavidParks8 @ericsuhong in case you have any thoughts.

**Comment by Michael-Sinz** [comment]
> > I am a bit concerned about the split personality here. A configuration deployed in public will act differently than that "same" configuration elsewhere. It makes sense as to why we are doing this but it still is concerning.
> 
> Strictly speaking, there is already ample precedent for default configuration between Azure Stack (and other custom clouds) and public Azure cloud being different. I think the larger concern is that, arguably, the value of ensuring apt-updated nodes is more pressing in non-public cloud, because it can be more difficult to do that patching manually.
> 
> I trust @jadarsie and others understand that, but it makes sense to give those folks time to test these assumptions in their environments first.
> 
> Also cc @DavidParks8 @ericsuhong in case you have any thoughts.

I fully agree - just pushing for "better security by default" but those environment should call the shots.

**Comment by jadarsie** [comment]
/lgtm

I could not start the conversation on my side yet. You can wait until I get back with an answer OR merge and then we can later update the code if needed.

**Comment by jadarsie** [comment]
@jackfrancis, `false` is the preferred default for ASH.

**Pull request merged**
