### PR TITLE
ci: add timestamp to artifact names

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

This is to allow re-running individual jobs without the published artifact names colliding.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm

**Comment by CecileRobertMichon** [comment]
The date doesn't get evaluated as expected

**Comment by CecileRobertMichon** [comment]
/hold cancel

@jackfrancis @mboersma this is ready for final `/lgtm`. Verified that the retries work https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=322&view=logs.

**Pull request merged**
