### PR TITLE
fix: updating hotfix packages used for windows inlcuding CVE and metric

### PR DESCRIPTION
**Pull request by AbelHu**
fixes

**Reason for Change**:

updating hotfix packages used for windows inlcuding CVE and metric

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jsturtevant** [comment]
code coverage is down a bit but I am not sure there is much we can do on this?  @mboersma any thoughts?

**Comment by mboersma** [comment]
@jsturtevant codecov is complaining about `k8s_versions.go` which is actually tested. I don't think there's anything reasonable we can do here, so let's ignore it and merge anyway. (Unfortunately, code coverage here is a blunt instrument that can be buggy, so we have to ignore its signal sometimes.)

**Comment by jsturtevant** [comment]
thanks!

/approve

**Pull request merged**
