### PR TITLE
feat: Upgrade Azure Disk CSI driver to support various new features

### PR DESCRIPTION
**Pull request by chewong**
**Reason for Change**:

- Upgraded the following CSI sidecar containers:
  - csi-provisioner `v1.0.1` -> `v1.4.0`
  - csi-attacher `v1.0.1` -> `v1.2.0`
  - azuredisk-csi-driver `v0.3.0` -> `v0.5.0`
- Added the following CSI sidecar containers:
  - csi-snapshotter `v1.1.0` (>= k8s 1.13)
  - csi-resizer `v0.3.0` (>= k8s 1.16)
- Upgrading CSI containers enables the following new features:
  - [Topology](https://kubernetes-csi.github.io/docs/topology.html) (k8s >= 1.14)
    - Requires `volumeBindingMode: WaitForFirstConsumer` and `allowedTopologies` key-value in storage class
    - Requires `--feature-gates=Topology=true` in csi-provisioner
  - [Volume expansion](https://kubernetes-csi.github.io/docs/volume-expansion.html) (k8s >= 1.16)
    - Requires `allowVolumeExpansion: true` in storage class
  - [Volume cloning](https://kubernetes-csi.github.io/docs/volume-cloning.html) (k8s >= 1.16)
  - [Snapshot](https://kubernetes-csi.github.io/docs/snapshot-restore-feature.html) (k8s >= 1.13)
    - Requires `--feature-gates=VolumeSnapshotDataSource=true` in API server until >= k8s 1.17

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by chewong** [comment]
> I think we could remove 1.13 support, to reduce support burden since we use different deployment scripts between 1.13 and 1.14+, other part LGTM

If we remove 1.13 support, `file.csi.azure.com` is the only storage class available for 1.13 clusters when cloud-controller-manager is enabled. Does that sound good?

**Comment by chewong** [comment]
@andyzhangx Should I also include https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/252 into this PR?

**Comment by andyzhangx** [comment]
> @andyzhangx Should I also include [kubernetes-sigs/azuredisk-csi-driver#252](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/252) into this PR?

no, that PR is for next release. LGTM for this PR.

**Comment by chewong** [comment]
/hold
Adding e2e tests.

**Comment by chewong** [comment]
Added cloud-controller-manager-enabled clusters as part of the e2e tests and ran on Jenkins against this PR - https://upstream.jenkins.azure-containers.io/view/aks-engine%20PRs/job/k8s-create-cluster-matrix/51/
@jackfrancis @mboersma @andyzhangx  Could you take another look? Thanks.
/unhold

**Pull request merged**
