### PR TITLE
chore(CIS): add streaming-connection-idle-timeout

### PR DESCRIPTION
**Pull request by andyzhangx**
**Reason for Change**:

Add "--streaming-connection-idle-timeout=true" flag, according to CIS conformance, kubectl exec will drop after 5 minutes unattended:
```
[FAIL] 2.1.5 Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Scored)
== Remediations ==
2.1.5 If using a Kubelet config file, edit the file to set streamingConnectionIdleTimeout to a
value other than 0.
If using command line arguments, edit the kubelet service file
/etc/systemd/system/kubelet.service on each worker node and
set the below parameter in KUBELET_SYSTEM_PODS_ARGS variable.
--streaming-connection-idle-timeout=5m
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service
```

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

/assign @jackfrancis
cc @leifei87 @feiskyer

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
The commit message should be fix(CIS conformance): ... in order to be picked up by release notes.

https://www.conventionalcommits.org/en/v1.0.0-beta.3/#commit-message-for-a-fix-using-an-optional-issue-number

**Comment by andyzhangx** [comment]
> The commit message should be fix(CIS conformance): ... in order to be picked up by release notes.

My commit msg is like following, I think it's ok, it already starts with `fix:` @CecileRobertMichon 
```
fix: add streaming-connection-idle-timeout
```

**Comment by CecileRobertMichon** [comment]
let's standardize on https://github.com/Azure/aks-engine/pull/1013#issuecomment-481880375

**Comment by andyzhangx** [comment]
@CecileRobertMichon I have changed the commit msg as following, PTAL, thanks.
```
chore(CIS): add streaming-connection-idle-timeout
```

**Pull request merged**
