### PR TITLE
chore: upgrade csi driver config

### PR DESCRIPTION
**Pull request by andyzhangx**
**Reason for Change**:

chore: upgrade csi driver config

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by andyzhangx** [comment]
@CecileRobertMichon how can I rerun the failed tests? I don't think the failure is related to this PR.

**Comment by CecileRobertMichon** [comment]
@andyzhangx I clicked re-run on the checks tab, looks like retry worked

**Comment by andyzhangx** [comment]
@CecileRobertMichon could you approve and merge this PR? thanks.

**Review by jadarsie — APPROVED** [review]

**Comment by andyzhangx** [comment]
can someone merge this PR? thanks.

**Comment by jadarsie** [comment]
Thx @andyzhangx for keeping the driver up to date!

**Pull request merged**
