### PR TITLE
chore: update Azure VM sizes

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

Adds new VM types picked up by `pkg/helpers/generate_azure_constants.py`, specifically `Standard_NV12s_v3`, `Standard_NV24s_v3`, `Standard_NV48s_v3`, and several `_Promo` types.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:
Do we need to include all these `_Promo` VM types?

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm pending some manual validation that these SKUs pass basic ARM template deployment.

**Comment by mboersma** [comment]
I'll fix up the unit tests and test the new VM types by hand.

**Pull request merged**
