### PR TITLE
feat: add support for Kubernetes v1.22.0-beta.0

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1220-alpha3

**Issue Fixed**:

Closes #4439
Closes #4447

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
I think getting this merged and then rebasing this PR on top of master afterwards is the last hurdle:

https://github.com/Azure/aks-engine/pull/4559

**Comment by mboersma** [comment]
/hold

Rebased on #4559 for now, because that should tell us if there is any work left to do here.

**Comment by mboersma** [comment]
@jackfrancis @jadarsie @Michael-Sinz this passed CI on the first go, so let's :shipit:.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by jadarsie — APPROVED** [review]

**Pull request merged**
