### PR TITLE
docs: adding instructions for how how to build the Windows VHD for di…

### PR DESCRIPTION
**Pull request by marosset**
…fferent container runtimes/OS versions

**Reason for Change**:

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by craiglpeters** [comment]
Looks great. Also please add a link to this in https://github.com/Azure/aks-engine/blob/master/docs/howto/README.md

**Comment by craiglpeters** [comment]
@jackfrancis should we extend this for Linux too?

**Comment by marosset** [comment]
> Looks great. Also please add a link to this in https://github.com/Azure/aks-engine/blob/master/docs/howto/README.md

updated

**Comment by jackfrancis** [comment]
Let's just add a TODO for Linux then we can merge this ASAP!

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
