### PR TITLE
feat: add support for Kubernetes v1.17.13

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v11712

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

This needs a temp testing commit. I will add that and restart CI.

**Comment by mboersma** [comment]
[1.17.13 passed CI](https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=6080&view=logs&jobId=9fc418ba-3811-54f4-f946-57d583faef20), so I'll remove the testing commit and this should be ready for review.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
