### PR TITLE
test: unit test for azure stack AzureClient

### PR DESCRIPTION
**Pull request by honcao**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [X] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by honcao** [comment]
FYI @deaborch @jadarsie @rjaini @vikasnav @Bhuvaneswari-Santharam

**Comment by jackfrancis** [comment]
lgtm

**Comment by CecileRobertMichon** [comment]
@honcao are you waiting for review from someone on the Azure Stack team or is this good to go?

**Comment by honcao** [comment]
@CecileRobertMichon it is good to go.

**Comment by jadarsie** [comment]
> @honcao are you waiting for review from someone on the Azure Stack team or is this good to go?

I am still caching up, getting close.

**Comment by CecileRobertMichon** [comment]
sorry if I merged too fast @jadarsie...

**Comment by honcao** [comment]
@CecileRobertMichon , you are good. 
@jadarsie is looking back all my changes for Azure Stack. I will follow up with him.
I will do another changes for the Unit test in next two weeks and will address Javier's comments if there is any.
Thanks to merge the pull request.

**Comment by honcao** [comment]
FYI @deaborch @jadarsie @rjaini @vikasnav @Bhuvaneswari-Santharam

**Comment by jadarsie** [comment]
> 
> 
> sorry if I merged too fast @jadarsie...

You are fine. It is like Hongbin said. My quick response was not clear.

**Pull request merged**
