### PR TITLE
feat: Adding steps to get log collection scripts for windows nodes

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

Make log collection scripts available for all windows nodes so users do not need to download them from the internet when needed.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
Holding until https://github.com/Azure/aks-engine/pull/2156 is merged and a new VHD with the files cached is available

**Comment by PatrickLang** [comment]
/lgtm

cc @rjaini since this will be helpful for AzureStack

**Comment by rjaini** [comment]
@PatrickLang Thanks for the update. Yes this will be helpful to collect windows logs if needed.

**Comment by rjaini** [comment]
lgtm

**Pull request merged**
