### PR TITLE
fix: bumping timeout for getting management ip on windows nodes

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

Some customers are seeing issues where the windows nodes do not come up because a management IP address never resolved. This PR extends the timeout (per guidance from networking team)

**Issue Fixed**:

#2281 

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
cc @pradipd

**Comment by marosset** [comment]
Related to https://github.com/Azure/aks-engine/issues/2281

**Comment by CecileRobertMichon** [comment]
/hold 
the commit message needs be amended to `fix: ` (lowercase + space)

**Comment by marosset** [comment]
PR title has been updated, thanks @CecileRobertMichon

**Pull request merged**
