### PR TITLE
feat: add support for Kubernetes v1.20.0-beta.2

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1200-beta1

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Hrm, two of these in a row on the 1.20 + containerd E2E tests:

`dns-liveness pod should not have any restarts`

**Comment by jackfrancis** [comment]
> Hrm, two of these in a row on the 1.20 + containerd E2E tests:
> 
> `dns-liveness pod should not have any restarts`

and three times :/

**Comment by jackfrancis** [comment]
I was able to repro this by building a local cluster against this PR:

```
$ k exec -it dns-liveness -- /bin/sh
/ # command terminated with exit code 137
```

(you wait a while and you get that response)

@cpuguy83 is there a way to determine if containerd is sending a SIGKILL to the container?

```
$ sudo ctr -n k8s.io containers ls | grep busybox
ae254bdb217027f861b24f500adb6ec63a26036e1aee5894b239ceb62abbd930    docker.io/library/busybox:latest                                                                                                    io.containerd.runc.v2    
c41bdd8ef3d118b7e79d29defc38fa64c1178badf7037e105c0f0d68ad194310    docker.io/library/busybox:latest                                                                                                    io.containerd.runc.v2
```

Some googling suggests an exit 137 pod may be a result of that.

**Comment by cpuguy83** [comment]
There might be some data in the containerd logs in journald.

**Comment by jackfrancis** [comment]
@cpuguy83 I see this in the containerd logs on the VM that the pod is scheduled onto:

```
level=error msg="ExecSync for \"fd6f2bdcebcca5e587f241ba5120b58f8430fa71fee467e0820368f6338aa69e\" failed" error="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 1s exceed
9Z" level=info msg="ExecSync for \"fd6f2bdcebcca5e587f241ba5120b58f8430fa71fee467e0820368f6338aa69e\" with command [sh -c nslookup www.bing.com || nslookup google.com] and timeout 1 (s)"
```

```
$ sudo ctr -n k8s.io containers ls | grep busybox
fd6f2bdcebcca5e587f241ba5120b58f8430fa71fee467e0820368f6338aa69e    docker.io/library/busybox:latest                                                                                                          io.containerd.runc.v2
```

**Comment by jackfrancis** [comment]
Thanks to @aramase we know the cause of this:

https://github.com/kubernetes/kubernetes/pull/94115

**Pull request closed without merging**
