### PR TITLE
feat: add support for Kubernetes v1.21.8

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1217

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
lgtm

**Comment by jackfrancis** [comment]
let's not merge this until after the new VHD PRs land, so we can release from master without cherry-picking into a new branch

**Comment by mboersma** [comment]
@jackfrancis is this mergeable now?

**Comment by jackfrancis** [comment]
Given that we can't release due to https://github.com/Azure/aks-engine/issues/4792 I think we can safely merge all of these new versions now (we'll have to build a new VHD to address Azure CNI bug anyways).

Thanks!

**Pull request merged**
