### PR TITLE
chore: add csi windows related images

### PR DESCRIPTION
**Pull request by ZeroMagic**
**Reason for Change**:

These images will be used by CSI Drivers.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

/cc @andyzhangx @xuto2

### CODE REVIEW

**Comment by andyzhangx** [comment]
@marosset could you approve? thanks. We will make csi-proxy enabled by default on AKS windows agent node and by caching these images, the csi driver on windows could be loaded quite faster.

**Comment by ZeroMagic** [comment]
Rebase to the master to solve the latest conflict.

**Comment by marosset** [comment]
We don't currently have logic to remove un-used container images for Windows nodes and I'm a little hesitant to include container images for a feature still in alpha.

@MikkelHegn @AbelHu @keikhara  do you have any concerns here from AKS?

Should we add logic to provisioning to remove Windows related CSI images if CSI proxy isn't enabled for Windows?

/cc @jsturtevant

**Comment by marosset** [comment]
Sorry, i missed the comment above where AKS is trying to enable CSI proxy by default.
If that is the case I don't have concerns with this.

/LGTM

**Pull request merged**
