### PR TITLE
fix: private cluster with VMSS masters, jumpbox

### PR DESCRIPTION
**Pull request by alexeldeib**
**Reason for Change**:

Private clusters do not currently deploy due to mixing of jumpbox and master resources, leading to variables absent or resources duplicated in the ARM templates. This PR separates and dedupes in the appropriate places, and fixes the corresponding tests to account for the behavior.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by alexeldeib** [comment]
Related to https://github.com/Azure/aks-engine/issues/1158

**Comment by alexeldeib** [comment]
One thing incomplete here is the networking setup when using private cluster + jumpbox. I wasn't sure what the desired output would be. I think it should be a single NSG with port 22 allowed from all sources and port 6443 (kube-tls) allowed inside VNET only? That should be okay because masters won't have any public IP?

**Comment by alexeldeib** [comment]
Technically, I guess the current config is sufficient: jumpbox has public IP and is open on port 22, while master NSG *which has allow all on 443* doesn't expose any public IPs, only private. I'd probably prefer to make 443 vnet internal. WDYT?

**Comment by jackfrancis** [comment]
lgtm

**Comment by CecileRobertMichon** [comment]
@alexeldeib can you please add a small description of what the PR does for future context?

**Comment by alexeldeib** [comment]
@CecileRobertMichon oops, how's that?

**Pull request merged**
