### PR TITLE
fix: CoreOS improvements and fixes

### LINKED ISSUE #1576: Controlplane on rebooted master node running Coreos does not recover
**Describe the bug**
Currently, when master node runs CoreOS and it's rebooted, either manually by user or by `update_engine`, the controlplane is not coming back.

I tracked it down and it seems to be related to 2 etcd systemd units. On initial provisioning `etcd` unit is running and it handles HTTPS on port 2379, since it reads the configuration from `/etc/default/etcd`. However, after a reboot `etcd-member` unit is started, which does not have TLS certificates configured, so it uses regular HTTP on port 2379 then, which causes kube-apiserver pod to crash.

I made it work by explicitly disabling `etcd-member` unit and explicitly enabling `etcd` unit, along with some other, smaller patches.

**Steps To Reproduce**

1. Deploy cluster with following snippet:
```
    "masterProfile": {
      "count": 1,
      "distro": "coreos"
    },
```
2. Wait for cluster to come up.
3. SSH into master node and reboot it.

**Expected behavior**
Controlplane survives reboot.

**AKS Engine version**
```
Version: v0.37.4
GitCommit: 9e8364ee9
GitTreeState: clean
```
**Kubernetes version**
`"orchestratorRelease": "1.15",`

**Additional context**

### PR DESCRIPTION
**Pull request by invidian**
**Reason for Change**:

This PR brings various CoreOS provisioning fixes and improvements, utilizing cloud-init capabilities.

It also fixes issue with rebooting master node on cluster running CoreOS.

**Issue Fixed**:

Closes #1576.

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

### CODE REVIEW

**Comment by invidian** [comment]
@CecileRobertMichon what's the status of this PR? Can it be merged? Is there anything which needs to be done on my side?

**Comment by CecileRobertMichon** [comment]
@invidian waiting for a secondary approver.

@mboersma @PatrickLang @marosset could one of you take a look?

**Pull request merged**
