### PR TITLE
chore: update pause image to 1.4.1

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR updates the pause image in aks-engine-created clusters to 1.4.1.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @marosset

**Comment by AbelHu** [comment]
@jackfrancis may I know what the change in the pause image 1.4.1 is?

**Comment by jackfrancis** [comment]
@jchauncey @sozercan can you answer @AbelHu's question?

**Comment by jchauncey** [comment]
runs the linux image as nonroot and included pipeline change for publishing the image to the airgap

**Comment by AbelHu** [comment]
Thanks for the answer, @jchauncey . Is it possible to add release notes for the pause images so we do not need to bother you later?

**Comment by jchauncey** [comment]
This is the last build that my team is building from our internal repo. From now own it will follow the upstream pause image release so the release notes will be there.

**Pull request merged**
