### PR TITLE
perf: increased default max pod limit to 110 for azure cni

### LINKED ISSUE #820: Is it possible to set the default value of max-pods to 110 by using the azure network plugin on the AKS-Engine?
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE 
---

**What version of aks-engine?**:
v0.32.3
---

**Kubernetes version**:
1.13.4

**What happened**:
I want to confirm that is it possible to set the default value of `max-pods` to 110 by using the azure network plugin on the AKS-Engine? 

**What you expected to happen**:
The default value of `max-pods` should be set to 110 by using the azure network plugin.

**How to reproduce it** (as minimally and precisely as possible):

1. Generate the template file by AKS-Engine
1. Deploy the cluster to Azure

**Anything else we need to know**:
No

### PR DESCRIPTION
**Pull request by tamilmani1989**
**Reason for Change**:

This PR increases the default limit of maz pods to 110 for azure cni (#820 , #87)

**Issue Fixed**:

Fixes #820 

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@tamilmani1989 Is there any additional guidance to add with this default change? Why did Azure CNI originally ship with a different opinion than vanilla Kubernetes? I.e., does Azure CNI behave differently when there are a lot of pods scheduled on a single node?

**Comment by tamilmani1989** [comment]
@jackfrancis Originally we thought  30 as reasonable number to start with but its based on customer experience. Since many customers wanted to go with 110 as default similar to kubenet plugin, then there is no point in keeping the limit to 30. 
There is no limitation from cni side to run 110 pods on the agent node. There is no change in behavior from CNI side. I tested running 110 pods on single node.

**Comment by jackfrancis** [comment]
@tamilmani1989 thx for the confirmation

Could you kindly change the documentation from this (in clusterdefinition.md):

> "30", or "110" if using kubenet --network-plugin (i.e., `"networkPlugin": "kubenet"`)

To this:

`"110"`

**Comment by tamilmani1989** [comment]
done.

**Comment by CecileRobertMichon** [comment]
We have unit tests that expect 30 max-pods that need to be updated.

**Comment by CecileRobertMichon** [comment]
@tamilmani1989 all E2E Linux deployments using `examples/e2e-tests/kubernetes/release/default/definition.json` are failing.

/hold

**Comment by toyota790** [comment]
Hi @tamilmani1989 and @CecileRobertMichon,

Is there any way that I can help on this? Thank you.

**Comment by CecileRobertMichon** [comment]
@toyota790 I believe @tamilmani1989 is on vacation right now. I haven't had cycles to look into this in depth but it looks like all E2E tests are failing. If you'd like to help move this PR forward you could start by looking at the test logs and try to repro the error with a deployment from this branch (or one with the same changes) to see what's going on. I'll re-trigger the tests since the old build expired.

**Comment by sozercan** [comment]
@tamilmani1989 can this be re-visited, or 30 is still good default?

**Comment by tamilmani1989** [comment]
> @tamilmani1989 can this be re-visited, or 30 is still good default?

im sorry for very delayed response. 110 should be good based on recent customer usage since kubnet default also 110. But for windows, we can't run more than 50 pods due to windows limitation.

**Pull request closed without merging**
