### PR TITLE
fix: make security context configs more restrictive

### PR DESCRIPTION
**Pull request by vtikoo**
**Reason for Change**:
Updated the security context related configs of the sgx device plugin to be more restrictive.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
We should definitely keep the E2E test up-to-date w/ doc recommendations!

**Comment by vtikoo** [comment]
@salsal97 @jackfrancis the e2e test is a slightly different scenario, as its not using a device plugin and directly accessing /dev/sgx on the host.
We can however update the e2e test to use a device plugin in a future PR, as thats the workflow we are recommending users. Any thoughts on that?

**Comment by jackfrancis** [comment]
@vtikoo Makes sense. So it sounds like we're not really testing/validating what we're recommending?

What would be involved to update our tests? Is it as simple as updating the spec we kubectl apply onto the cluster?

**Comment by vtikoo** [comment]
It would involve installing the sgx device plugin before the actual test workload runs. 

For installing the device plugin, we could either kubectl apply it and wait for it to be ready, or create an addon/extension. The latter would be more effort, but might be useful to users as well.

**Comment by jackfrancis** [comment]
Right, thanks for clarifying, yeah, let's add a follow-up task to do the kubectl apply + run updated spec in the E2E tests.

**Comment by jackfrancis** [comment]
Added this backlog issue: https://github.com/Azure/aks-engine/issues/3462

**Pull request merged**
