### PR TITLE
feat: Update Antrea version to v1.3.0

### PR DESCRIPTION
**Pull request by reachjainrahul**
Signed-off-by: Rahul Jain <reachjainrahul@gmail.com>

**Reason for Change**:
Upgrading Antrea version to v1.3.0. Also fixed documentation
links.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [X] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by reachjainrahul** [comment]
cc @jackfrancis @mboersma

**Comment by reachjainrahul** [comment]
@mboersma Any known issue with TOT?

**Comment by mboersma** [comment]
> Any known issue with TOT?

I don't know what TOT stands for here...

**Comment by reachjainrahul** [comment]
> > Any known issue with TOT?
> 
> I don't know what TOT stands for here...

TOT Top of the tree. I meant to ask if there is any known issue with E2E tests on **master** (TOT) branch. As you see some E2E tests are failing on specific version.

**Comment by mboersma** [comment]
> As you see some E2E tests are failing on specific version.

Yes, and they look like flakes unrelated to your changes as far as I can tell. I'll re-run them.

**Comment by jackfrancis** [comment]
Hi @reachjainrahul, I assume you have manually tested these changes?

**Comment by reachjainrahul** [comment]
> Hi @reachjainrahul, I assume you have manually tested these changes?

Yes.. Ran e2e tests on latest change. and it passed.

**Comment by reachjainrahul** [comment]
> > Hi @reachjainrahul, I assume you have manually tested these changes?
> 
> 
> 
> Yes.. Ran e2e tests on latest change. and it passed. 

@jackfrancis can we submit the changes soon. Thanks

**Pull request merged**
