### PR TITLE
docs: add how to install aks-engine with Chocolatey

### LINKED ISSUE #652: Chocolatey install
We used to be able to install `acs-engine` using [Chocolatey](https://chocolatey.org/). This was very convenient, as everything we required for setup could be installed with Chocolatey (azure cli, helm, etc.). It appears that `aks-engine` isn't available via Chocolatey though - is there any plan to make it available again?

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

Explains how to install `aks-engine` with the Windows package manager Chocolatey. All thanks goes to @synax for maintaining and publishing this!

**Issue Fixed**:

Fixes #652

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by deborahc** [comment]
@khenidak, @wmengmsft, @shreyshah-msft for review

**Comment by CecileRobertMichon** [comment]
@deborahc did you mean to write this comment for #669 ?

**Comment by mboersma** [comment]
Still waiting for package approval.

**Pull request merged**
