### PR TITLE
chore: Update default Windows VHDs to Sept 2021 images

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

**Reason for Change**:

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
@jsturtevant @jackfrancis 
This just includes 9B patches. I have opened a PR to include 9C patches and we can release those as a separate VHD if they pass validation.

**Comment by jackfrancis** [comment]
Got it, so this update isn't meant to be for a new aks-engine release? (with new k8s versions still in the progress of merging...)

**Comment by marosset** [comment]
> Got it, so this update isn't meant to be for a new aks-engine release? (with new k8s versions still in the progress of merging...)

This has some fixes we've been waiting for for upstream tests.
We can make a new VHD w/ new versions and 9C patches for the next release.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
