### PR TITLE
feat: add support for Kubernetes v1.24.0-alpha.2

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1240-alpha1

**Issue Fixed**:

N/A

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
@mboersma I think we need to drop the docker test from the e2e matrix for 1.24 :)

**Comment by jackfrancis** [comment]
@marosset speaks truth!

**Comment by mboersma** [comment]
> we need to drop the docker test from the e2e matrix for 1.24

Indeed we do--let me amend the PR.

**Review by marosset — APPROVED** [review]
/lgtm

Thanks Matt!

**Pull request merged**
