### PR TITLE
chore: updating cni to v1.1.2

### PR DESCRIPTION
**Pull request by tamilmani1989**
**Reason for Change**:

Upgrading cni to v.1.1.2. 
1. Has minor fixes
3. Windows CNI dualstack support

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@jchauncey @sozercan do we have pre-existing pipeline jobs to publish new Azure CNI versions to our CDN endpoint?

**Comment by tamilmani1989** [comment]
> @jchauncey @sozercan do we have pre-existing pipeline jobs to publish new Azure CNI versions to our CDN endpoint?

@jackfrancis lets hold this. we are going to release new cni soon. Lets take that. Sorry for the inconvenience.

**Comment by matmerr** [comment]
> @jchauncey @sozercan do we have pre-existing pipeline jobs to publish new Azure CNI versions to our CDN endpoint?

We've added a pipeline job to publish new signed Azure CNI versions to our CDN endpoint if you're looking to mirror or pull directly

https://acnreleaseartifacts.azureedge.net/azure-cni/v1.1.1/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.1.1.zip

**Comment by tamilmani1989** [comment]
@jackfrancis  Released v1.1.2. Can pick :
1. linux binaries from github page -  https://github.com/Azure/azure-container-networking/releases/download/v1.1.2/azure-vnet-cni-linux-amd64-v1.1.2.tgz

2. Signed windows binaries from https://acnreleaseartifacts.blob.core.windows.net/azure-cni/v1.1.2/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.1.2.zip

Please remove backlog label

**Comment by mboersma** [comment]
> Please remove backlog label

@tamilmani1989 "backlog" is used for our general set of work items. We attach that label mainly so the bot doesn't mark things as stale after 30 days. Sorry, that's probably not intuitive.

**Comment by sozercan** [comment]
they are mirrored to `kubernetesartifacts` now

**Comment by tamilmani1989** [comment]
@mboersma  can you please run azp again? The binaries are mirrored now.

**Comment by sozercan** [comment]
i think windows zip needs to be renamed, it has `singletenancy` in the name now

**Comment by tamilmani1989** [comment]
> i think windows zip needs to be renamed in the pr, it has `singletenancy` in the name now

Ya noticed that. @matmerr  we are not supposed to change zip name. can we rename and upload to storage account for now?

**Comment by tamilmani1989** [comment]
ok free. I will update the url in PR

**Comment by tamilmani1989** [comment]
@sozercan do you know why this test (AKS-Engine WS2019 VHD - docker) failed? I saw this:

"VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'."

**Comment by tamilmani1989** [comment]
Let me check updating this file also -> pkg\api\azenvtypes.go

**Comment by tamilmani1989** [comment]
@mboersma can you please start azp? looks like vhd passed

**Comment by tamilmani1989** [comment]
@mboersma @sozercan  can we merge this?

**Pull request merged**
