### PR TITLE
fix: restart hns for Windows dual-stack

### PR DESCRIPTION
**Pull request by vavenk-ms**
**Reason for Change**:

Due to a bug in the hns service there is a race where it picks up the incorrect IPv6 address from the node in some cases. The hns service has to be restarted after the node internal IPv6 address is available when dual-stack is enabled.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [X] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jsturtevant** [comment]
should this be a commit as part of #4176?

**Comment by vavenk-ms** [comment]
> should this be a commit as part of #4176?

@jsturtevant sure, I can add it there and close this one.

**Comment by vavenk-ms** [comment]
Added the commit to #4176

**Pull request closed without merging**
