### PR TITLE
fix: include vnet CIDR in windows node CNI outbound NAT exception list

### PR DESCRIPTION
**Pull request by xizhamsft**
**Reason for Change**:
For windows node provisioned in custom vnet with CNI, we should include VNETCIDR in the outbound NAT exception list. Otherwise VMs in different subnet won't be able to reach the windows pods.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [x] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by xizhamsft** [comment]
@kkmsft , please take a look

**Comment by xizhamsft** [comment]
> is this just for custom Vnets, or is it needed in other cases?
> 
> cc @daschott - can you find a networking reviewer for this?

Yes. It is for custom vnet only.

**Comment by daschott** [comment]
@ashvindeodhar PTAL
@madhanrm @dineshgovindasamy FYI please comment if any concerns with this

**Comment by CecileRobertMichon** [comment]
@PatrickLang @daschott the change is breaking as-is, all Windows E2E tests are failing. I don't think it's ready for review.

**Comment by CecileRobertMichon** [comment]
@PatrickLang are we still waiting for a networking reviewer to approve this? I don't see an lgtm from @ashvindeodhar

**Comment by xizhamsft** [comment]
@CecileRobertMichon I am working with @ashvindeodhar on the review.

**Pull request merged**
