### PR TITLE
feat: Adding a configurable additional ssh port.

### LINKED ISSUE #2813: Support custom ssh port.
**Describe the request**

In the current version, ssh port is default to 22. However, in our case the port 22 is banned by some network policies and ssh connection to master cannot be established.

**Explain why AKS Engine needs it**

**Describe the solution you'd like**

Add support for custom ssh default port.

**Describe alternatives you've considered**

Just simply configure something like `/etc/ssh/sshd_config` before the cluster has been built.

**Additional context**

### PR DESCRIPTION
**Pull request by nilo19**
**Reason for Change**:

Adding a configurable additional ssh port.

**Issue Fixed**:

Fixes #2813

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@nilo19 can you describe why we want to expose an *additional* ssh listener and NSG inbound rule, instead of just replacing TCP 22 w/ a configurable port? In other words, what's the benefit of continuing to listen on 22 *and* another port?

**Comment by nilo19** [comment]
> @nilo19 can you describe why we want to expose an _additional_ ssh listener and NSG inbound rule, instead of just replacing TCP 22 w/ a configurable port? In other words, what's the benefit of continuing to listen on 22 _and_ another port?



> @nilo19 can you describe why we want to expose an _additional_ ssh listener and NSG inbound rule, instead of just replacing TCP 22 w/ a configurable port? In other words, what's the benefit of continuing to listen on 22 _and_ another port?

In our case, we couldn't use the port 22 but someone else could. Since it's not globally useless, I think adding an additional port would be a better choice.

**Comment by jackfrancis** [comment]
@nilo19 Thanks for the explanation! I think the alternate port is also able to be used by those who can use 22, and for the benefit of maintaining the code it's a better idea to simply make the TCP 22 LoadBalancer port and sshd listener port user-configurable, so that folks who build clusters maintained from a variety of environments can settle on a TCP port that is accessible in common, and maintain the cluster thusly.

In addition to the improved maintainability of the aks-engine code, it's also an improvement to the ingress security model to reduce the available permissive inbound vectors as much as possible.

**Comment by nilo19** [comment]
@jackfrancis sorry for the late reply. I've change the code to replace the default ssh port by the new port.

**Comment by jackfrancis** [comment]
Re-open if we still want to consider merging this!

**Pull request closed without merging**
