### PR TITLE
fix: #2667 change apiVersion of deployments from v1beta2 to v1

### LINKED ISSUE #2667: no kind "Deployment" is registered for version "apps/v1beta2"
**Describe the bug**
no kind "Deployment" is registered for version "apps/v1beta2"

**Steps To Reproduce**

run make prow at https://github.com/Azure/aks-engine/tree/master/.prowci

**Expected behavior**

**AKS Engine version**

**Kubernetes version**
kubernetes 1.17.0

**Additional context**
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/

### PR DESCRIPTION
**Pull request by yc-zc**
**Reason for Change**:

**Issue Fixed**:

fixes #2667

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks @yc-zc. I think it's good to clean this up to avoid confusion.

But sadly `make prow` and friends are stale and don't represent the bot configuration we are currently using. I opened #1728 to make sure we sync up the current config, and I hope to finally do that in the next couple weeks.

**Comment by yc-zc** [comment]
Thank you @mboersma for your explanation. 

I have tried to use prow on AKS but sadly it definitely needs more documentations to explain on how to add plugins. So I have switched to GKE as it's much clearer. However, it seems the brazel still tries to deploy it on AKS though I have configured gcloud (kubectl returns right information).

**Pull request merged**
