### PR TITLE
fix: clean up stale CNI data regardless of HNS state

### PR DESCRIPTION
**Pull request by ashvindeodhar**
fix: cleanup stale CNI data regardless of HNS state
Currently CNI stale data is cleaned up only when a stale HNS network is found.
This change removes that unnecessary dependency and cleans up the stale CNI data
regardless of the HNS state. This is needed when HNS network is not persisted across the reboots.

**Reason for Change**:

**Issue Fixed**:

Fixes https://github.com/Azure/azure-container-networking/issues/642

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @ashvindeodhar, is this meant to be a Windows-only change? There is no equivalent Linux change to benefit those scenarios?

**Comment by ashvindeodhar** [comment]
@jackfrancis yes this is for windows-only. There is no change for linux scenario since linux removes all the CNI stale data upon reboot.

**Comment by marosset** [comment]
@AbelHu @mainred as FYI

**Comment by ashvindeodhar** [comment]
@marosset / @jackfrancis Do you know which AKS release will this get into? I am looking to get some idea as to when (ETA) will this is available to the customers.

**Comment by jackfrancis** [comment]
@xuto2 are you able to answer @ashvindeodhar's question?

**Comment by xuto2** [comment]
@AbelHu Can you comment on the above question? It's an issue for windows only.

**Comment by AbelHu** [comment]
@ashvindeodhar I think that aks-e will sign this script and publish a new Windows signed binary. After that, AKS can pick up it. Please let me know when the new signed binary is ready. @marosset. Thanks.

**Comment by mainred** [comment]
Want to confirm from @ashvindeodhar, we can resolve https://github.com/Azure/azure-container-networking/issues/642 by only this PR, right?
If so, Windows signed binary for CNI is required, but we need to include changes in this PR to AKS used branch.

**Comment by zhiweiv** [comment]
Just FYI, the issue in AKS is https://github.com/Azure/AKS/issues/1772, it is great to update the ETA there.

**Pull request merged**
