### PR TITLE
fix: Fix the incorrect computername parameter

### PR DESCRIPTION
**Pull request by tariq1890**
`computername` is the wrong name and it is not recognized by the RP schema. `computerName` should be used instead

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
is `it is recognized by the RP schema` meant to be `it is NOT recognized by the RP schema`?

**Comment by tariq1890** [comment]
@CecileRobertMichon updated the PR description.

**Comment by jackfrancis** [comment]
lgtm

**Pull request merged**
