### PR TITLE
chore: update docker EE to 20.10.9 for Windows

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

 Windows: Fix a situation where containers were not stopped if HcsShutdownComputeSystem returned an ERROR_PROC_NOT_FOUND error moby/moby#42613

**Reason for Change**:

Docker 20.10.8 contains a fix where windows containers can stay around after they get deleted (aka 'zombie pods') which continue to consume host resources.

https://docs.docker.com/engine/release-notes/#20108 -> Windows: Fix a situation where containers were not stopped if HcsShutdownComputeSystem returned an ERROR_PROC_NOT_FOUND error moby/moby#42613

/cc @AbelHu 

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by marosset** [comment]
/hold 
It looks like docker EE version 20.10.6 is still getting installed on the Windows nodes...

```
$ k get nodes -o json
2021/09/10 18:30:06 NAME                                   STATUS   ROLES    AGE     VERSION    INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION      CONTAINER-RUNTIME
3315k8s01000000                        Ready    agent    5m58s   v1.18.20   10.239.16.4      <none>        Windows Server 2019 Datacenter   10.0.17763.2061     docker://20.10.6
k8s-master-33153947-0                  Ready    master   8m37s   v1.18.20   10.239.255.239   <none>        Ubuntu 18.04.5 LTS               5.4.0-1058-azure    docker://20.10.7+azure
k8s-master-33153947-1                  Ready    master   8m27s   v1.18.20   10.239.255.240   <none>        Ubuntu 18.04.5 LTS               5.4.0-1058-azure    docker://20.10.7+azure
k8s-master-33153947-2                  Ready    master   8m26s   v1.18.20   10.239.255.241   <none>        Ubuntu 18.04.5 LTS               5.4.0-1058-azure    docker://20.10.7+azure
k8s-pool1604vhd-33153947-vmss000000    Ready    agent    3m20s   v1.18.20   10.239.32.4      <none>        Ubuntu 16.04.7 LTS               4.15.0-1113-azure   docker://20.10.7+azure
k8s-pool1804-33153947-vmss000000       Ready    agent    17s     v1.18.20   10.239.48.4      <none>        Ubuntu 18.04.5 LTS               5.4.0-1058-azure    docker://20.10.7+azure
k8s-pool1804gen2-33153947-vmss000000   Ready    agent    3m35s   v1.18.20   10.239.64.4      <none>        Ubuntu 18.04.5 LTS               5.4.0-1058-azure    docker://20.10.7+azure
k8s-poollinux-33153947-vmss000000      Ready    agent    4m59s   v1.18.20   10.239.0.4       <none>        Ubuntu 18.04.5 LTS               5.4.0-1058-azure    docker://20.10.7+azure
```

It looks like there is logic to install the latest Docker version in the nuget feed if we cannot find a specific verison...
https://github.com/Azure/aks-engine/blob/e38d4f79c1a9a0b3cdf101faca610b9b4ab8e2dd/parts/k8s/windowsconfigfunc.ps1#L100-L104

Need to investigate more...

**Comment by AbelHu** [comment]
@marosset I hit this issue before. 20.10.8 is not available in the MSFT nuget repo. We need to wait 20.10.8 in MSFT nuget repo

**Review by AbelHu — DISMISSED** [review]

**Comment by AbelHu** [comment]
@marosset could we merge this PR and start to run upstream test now?

**Review by AbelHu — APPROVED** [review]

**Comment by marosset** [comment]
Docker EE 20.10.8 has some problems on Windows.

Each time I reboot a machine with Docker EE 20.10.8 installed on the system the docker service tries to start and then fails a few times with error code 1067 (program terminated unexpectedly).
The windows event logs show 

> fatal: open C:\ProgramData\docker\panic.log: Access is denied.

If I delete the panic.log file try and start the docker service it starts, a new – empty – panic.log file is created, and everything works…. until the next reboot.

**Comment by AbelHu** [comment]
https://github.com/moby/moby/pull/42987
It seems like that we need to wait 20.10.11 DockerMsftProvider package is available.

**Comment by marosset** [comment]
I updated the PR to use 20.10.9

**Comment by slonopotamus** [comment]
I believe that `DockerMsftProvider` won't get any updates because of this: https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799

You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install modern Docker engine for Windows containers on both Windows Server/Client.

**Review by jackfrancis — APPROVED** [review]
lgtm

**Comment by marosset** [comment]
> I believe that `DockerMsftProvider` won't get any updates because of this: https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799
> 
> You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install modern Docker engine for Windows containers on both Windows Server/Client.

From the blog post it sounds like DockerMsftProvider will continue to get new packages until Sept 2022.
The issue I was seeing has resolved itself and I suspect it was related to CDN or some other replication not being fully complete.

**Comment by marosset** [comment]
> > I believe that `DockerMsftProvider` won't get any updates because of this: https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799
> > You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install modern Docker engine for Windows containers on both Windows Server/Client.
> 
> From the blog post it sounds like DockerMsftProvider will continue to get new packages until Sept 2022. The issue I was seeing has resolved itself and I suspect it was related to CDN or some other replication not being fully complete.

@slonopotamus I will take a look at that project in the future tho!

**Review by jsturtevant — APPROVED** [review]

**Pull request merged**
