### PR TITLE
fix: fix sshd logging to auth.log for OMS

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

https://icm.ad.msft.net/imp/v3/incidents/details/108362084/home
OMS agent relies on auth.log for getting ssh logs for security monitoring purposes. https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-sources-syslog#configure-syslog-on-linux-agent
https://github.com/Azure/acs-engine/pull/1956 disabled `ForwardToSyslog` which broke this scenario. See for additional context: https://github.com/Azure/acs-engine/pull/1956#issuecomment-382822102

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@JunSun17 @mpalumbo7 FYI

@jackfrancis @feiskyer please speak up if you know of any reasons that we shouldn't make this change.

**Comment by jackfrancis** [comment]
The argument against making this change is the additional I/O (and arguably CPU/mem, though probably not significant) overhead required to stream journald to syslog. @feiskyer @khenidak @cpuguy83 @cchildress any thoughts?

**Comment by JunSun17** [comment]
Thanks for fixing this! So does this only impact auth.log or all other logs? Just not sure how much other impact it might bring beside bring back auth.log.

**Comment by CecileRobertMichon** [comment]
Regarding extra I/O concern, I think it's a tradeoff. This is the only way to restore OMS security monitoring AFAIK. I don't think the extra logs would be significant I/O overhead but they would be the price to pay for auth logging. FWIW, `ForwardToSyslog` defaults to `yes` on vanilla Azure Ubuntu VMs so we would be going back to the default behavior.

**Pull request merged**
