### PR TITLE
fix: Update mirror probe port

### PR DESCRIPTION
**Pull request by karataliu**
**Reason for Change**:
Actual traffic goes to 443, should check 443 for outboud traffic.

This is required for egress locked nodes.

**Issue Fixed**:

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by karataliu** [comment]
cc @andyzhangx

**Comment by jackfrancis** [comment]
@andyzhangx do we still want this change?

**Comment by andyzhangx** [comment]
> @andyzhangx do we still want this change?

sure, thanks.

**Comment by andyzhangx** [comment]
why closed this PR? @karataliu

**Pull request merged**
