### PR TITLE
fix: deploy CSI drivers for Azure Disk & Azure File when cloud-controller-manager is enabled

### PR DESCRIPTION
**Pull request by chewong**
**Reason for Change**: When useCloudControllerManager is set to true, the in-tree volumes plugins for AzureDisk and AzureFile won't work any more. CSI drivers should be deployed

**Issue Fixed**: #1916

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:
/cc @andyzhangx @feiskyer @ritazh

### CODE REVIEW

**Comment by andyzhangx** [comment]
@chewong actually there is another work item related to this, when ccm is enabled, following built-in storage classes should be replaced by *.csi.azure.com
```
azurefile           kubernetes.io/azure-file
default (default)   kubernetes.io/azure-disk
managed-premium     kubernetes.io/azure-disk
managed-standard    kubernetes.io/azure-disk
```

```
azurefile           file.csi.azure.com
default (default)   disk.csi.azure.com
managed-premium     disk.csi.azure.com
managed-standard    disk.csi.azure.com
```

**Comment by chewong** [comment]
@andyzhangx Fixed.

**Comment by mboersma** [comment]
See also #2161.

**Comment by chewong** [comment]
@mboersma do you have any update on this PR?

**Comment by mboersma** [comment]
@chewong this looks good. My only concern is fetching the CSI containers from `quay.io` since we're trying to host everything in MCR. Is there a plan to mirror or move them to MCR?

**Comment by chewong** [comment]
> Is there a plan to mirror or move them to MCR?

@andyzhangx could you comment on this?

**Comment by ritazh** [comment]
@jchauncey we need to mirror the `quay.io/k8scsi` images as well

**Comment by andyzhangx** [comment]
> quay.io/k8scsi

Hi @jchauncey, `quay.io/k8scsi` is needed for all CSI drivers in the future, would you mirror those images in our MCR, thanks.

**Comment by jchauncey** [comment]
👍

**Comment by ritazh** [comment]
Until the mirror images are available, can we unblock this PR with the quay images for now then update all of them in a later PR? WDYT?

**Comment by mboersma** [comment]
> can we unblock this PR with the quay images for now...?

I think so. I opened #2195 to track changing over to the Azure mirror.

**Pull request merged**
