### PR TITLE
chore: Targeting August updates for Windows VHD

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:
New Windows Server images with August patches have been released.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=24450253

**Comment by PatrickLang** [comment]
/approve
Thanks!

**Pull request merged**
