### PR TITLE
fix: update Windows image validate on Azure Stack Hub

### PR DESCRIPTION
**Pull request by haofan-ms**
**Reason for Change**:

The image validation for raw Windows image on Azure Stack Hub should be based on image information from api model only.

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jadarsie** [comment]
lgtm

**Comment by jackfrancis** [comment]
@marosset can you review this one?

**Comment by jadarsie** [comment]
> @marosset can you review this one?

FYI, this is only executed if Azure Stack
https://github.com/Azure/aks-engine/blob/fce292453c194c3f2848eac210e017fbbca02b72/cmd/deploy.go#L544

**Comment by marosset** [comment]
Sorry - I got tied up this evening.
Looks good

**Pull request merged**
