### PR TITLE
Fixed wrong az group create command

### PR DESCRIPTION
**Pull request by agowdamsft**
Correct command is az group deployment

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by agowdamsft** [comment]
assign to @ksubrmnn for approval

**Comment by mboersma** [comment]
@agowdamsft `az group deployment` has been deprecated for several releases of the `az` client now. The preferred syntax is now `az deployment group`. You may have an older version of the CLI that can be updated.

See #3213 for details.

**Comment by agowdamsft** [comment]
I was looking into these docs @mboersma  https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest

**Comment by mboersma** [comment]
I guess they haven't updated those docs yet. But a few months ago the `az` client began emitting warnings for `az group deployment`:

```shell
% az group deployment -h  

Group
    az group deployment : Manage Azure Resource Manager deployments.
        This command group has been deprecated and will be removed in a future release. Use
        'deployment group' instead.
...
```

We call this command programmatically in a few places in tests, so I changed those to `az deployment group` to silence the warnings.

I did the same to our docs, but maybe that was a bit premature. If you use an `az` CLI from 2019 or earlier, you may not yet have this change.

**Pull request closed without merging**
