### PR TITLE
fix: Allow masters with custom images to use data disks for etcd

### LINKED ISSUE #496: Kube API high latency caused by etcd with custom image
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
0.28.0
---

**Kubernetes version**:
1.13.1

**What happened**:
We're seeing many etcd errors/warnings on our 3 master cluster with aks-engine: `server is likely overloaded`, `timed out waiting for read index response`, `took too long`, `failed to revoke x ("etcdserver: request timed out")`,...  which are causing kube API requests take too long/timeout.

Running the standard prometheus operator ruleset is resulting in lots of high latency alerts being fired for the kube api, that's what led me to the etcd errors and warnings.

**What you expected to happen**:
etcd can take the I/O and kube API requests go through seamlessly.

**How to reproduce it** (as minimally and precisely as possible):
3 master cluster, running standard Prometheus operator ruleset resulting in many high latency alerts fired for kube api.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by danmassie**
**Reason for Change**:

Allow masters with custom images to use data disks for etcd

**Issue Fixed**:

Fixes #496 

**Requirements**:

- [ x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:
Tested with a custom ubuntu 16.04 image. And this model:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
      "etcdDiskSizeGB": "256"
}
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_DS2_v2",
      "imageReference": {
        "name": "ubuntu-16-04",
        "resourceGroup": "test-images"
      },
      "availabilityProfile": "AvailabilitySet"
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": 1,
        "vmSize": "Standard_DS2_v2",
        "storageProfile" : "ManagedDisks",
      "imageReference": {
        "name": "ubuntu-16-04",
        "resourceGroup": "test-images"
      },
        "availabilityProfile": "VirtualMachineScaleSets"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

etcd volume is created using a Premium SSD and mounted at 
```
Filesystem     Mounted on
/dev/sdc1      /var/lib/etcddisk
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@tariq1890 I added this to the go template refactor project FYI since it changes the templates.

**Comment by CecileRobertMichon** [comment]
Thank you @danmassie for opening the PR! Someone from the team will review and make sure this has no side effects then make sure it is integrated with @tariq1890's refactor of the templates.

**Comment by tariq1890** [comment]
cc @andyzhangx 

If this change is approved, we should also update this in the `masterarmresouirces.go` file.

**Comment by CecileRobertMichon** [comment]
@tariq1890 can you please guide @danmassie to make the change you mentioned in `masterarmresources.go`? 

@danmassie, because the file you modified is not going to be used anymore when we stop using templates, we need to add your change to the new go implemention of ARM resource definitions.

**Comment by danmassie** [comment]
@CecileRobertMichon @tariq1890 I messed this one up while rebasing my fork. https://github.com/Azure/aks-engine/pull/710 created instead.

**Pull request closed without merging**
