### PR TITLE
fix: do not create ELB for private clusters

### LINKED ISSUE #474: ELB and load balancer standard
**Is this a request for help?**:
no
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
0.30.0
---

**Kubernetes version**:
N/A

**What happened**:
Despite I am creating a private cluster in an environment with forced tunneling ELB (!) is create for some ridiculuous reasons (standard load balancer is not a good enough reason, especially in a private cluster).

**What you expected to happen**:
Don't create the ELB in private clusters! At least allow disabling it. This is nonsense.

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster with in a multizone configuration (private cluster), ELB will be created as documented here: https://github.com/Azure/aks-engine/blob/babf7087433559012c61acda2aa7f82f3ce94eed/docs/topics/clusterdefinitions.md (see `loadBalancerSku` section)

**Anything else we need to know**:
Forced tunneling or NVA is a normal situation and you don't need SNAT in SLB then.

### PR DESCRIPTION
**Pull request by mkosieradzki**
**Reason for Change**:

Prevents creation of ELB for private clusters.

**Issue Fixed**:

Fixes #474 

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm

**Comment by jackfrancis** [comment]
@mkosieradzki FYI I rebased/force-pushed to your branch to unblock testing of this due to go generated nonsense

**Comment by mkosieradzki** [comment]
@jackfrancis Thanks. However unfortunately I am unable to see the test results.

**Pull request merged**
