### PR TITLE
feat: Support enabling secure TLS protocols on Windows nodes

### PR DESCRIPTION
**Pull request by AbelHu**
**Reason for Change**:

Support enabling secure TLS protocols on Windows nodes
This depends on a new Windows provisioning package v0.0.14. https://github.com/Azure/aks-engine/pull/4567

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by AbelHu** [comment]
TLS logs in C:\AzureData\CustomDataSetupScript.log in my test.
```
Enable secure TLS protocols
2021-07-06T08:33:38.1552735+00:00: ========== Start of logging for Enable-SecureTls ==========
2021-07-06T08:33:38.1552735+00:00: Enabling TLS1.2. Disabling TLS1.1, TLS1.0, SSL3.0, SSL2.0
2021-07-06T08:33:38.1552735+00:00: Check which registry keys exist already and which registry keys need to be created.
2021-07-06T08:33:38.1552735+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2
2021-07-06T08:33:38.1865227+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2
2021-07-06T08:33:38.1865227+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
2021-07-06T08:33:38.2021466+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
2021-07-06T08:33:38.2021466+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
2021-07-06T08:33:38.2333958+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
2021-07-06T08:33:38.2333958+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0
2021-07-06T08:33:38.2490370+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0
2021-07-06T08:33:38.2490370+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client
2021-07-06T08:33:38.2646693+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client
2021-07-06T08:33:38.2803181+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server
2021-07-06T08:33:38.2959328+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server
2021-07-06T08:33:38.2959328+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0
2021-07-06T08:33:38.2959328+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client
2021-07-06T08:33:38.3115380+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server
2021-07-06T08:33:38.3740109+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0
2021-07-06T08:33:38.3896328+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0
2021-07-06T08:33:38.4052625+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
2021-07-06T08:33:38.4052625+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
2021-07-06T08:33:38.4208978+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
2021-07-06T08:33:38.4365093+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
2021-07-06T08:33:38.4521531+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1
2021-07-06T08:33:38.4521531+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1
2021-07-06T08:33:38.4677721+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
2021-07-06T08:33:38.4834023+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
2021-07-06T08:33:38.4834023+00:00: Checking for existing of key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
2021-07-06T08:33:38.4990261+00:00: Creating key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
2021-07-06T08:33:38.5146513+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client
2021-07-06T08:33:38.5302853+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server
2021-07-06T08:33:38.5615289+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client
2021-07-06T08:33:38.5771543+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server
2021-07-06T08:33:38.5928449+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
2021-07-06T08:33:38.6240858+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
2021-07-06T08:33:38.6396326+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
2021-07-06T08:33:38.6708815+00:00: Disabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
2021-07-06T08:33:38.6865148+00:00: Enabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
2021-07-06T08:33:38.7021402+00:00: Enabling this key: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
2021-07-06T08:33:38.7490155+00:00: ----- Checking the status of RC4 -----
2021-07-06T08:33:38.7490155+00:00: There was no change for RC4
2021-07-06T08:33:38.7490155+00:00: ----- starting ciphersuite order calculation for excellence cipher suite order -----
2021-07-06T08:33:38.7646598+00:00: Appropriate ciphersuite order : TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_
WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
2021-07-06T08:33:38.7646598+00:00: Previous cipher suite value:
2021-07-06T08:33:38.7646598+00:00: New cipher suite value     : TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WIT
H_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
2021-07-06T08:33:38.7646598+00:00: Cipher suite order needs to be updated.
2021-07-06T08:33:38.7646598+00:00: Cipher suite value was updated.
2021-07-06T08:33:38.7646598+00:00: Checking to see if reg keys exist and if MinEncryptionLevel is set to 4
2021-07-06T08:33:38.7646598+00:00: Checking to see if HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\MinEncryptionLevel exists
2021-07-06T08:33:38.7802769+00:00: Regkey HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\MinEncryptionLevel left at value 2
2021-07-06T08:33:38.7802769+00:00: Checking to see if HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\MinEncryptionLevel exists
2021-07-06T08:33:38.8115112+00:00: Regkey HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\MinEncryptionLevel was not found
2021-07-06T08:33:38.8115112+00:00: Checking to see if HKLM:\System\CurrentControlSet\Control\Terminal Server\DefaultUserConfiguration\MinEncryptionLevel exists
2021-07-06T08:33:38.8115112+00:00: Regkey HKLM:\System\CurrentControlSet\Control\Terminal Server\DefaultUserConfiguration\MinEncryptionLevel was not found
2021-07-06T08:33:38.8115112+00:00: ========== End of logging for Enable-SecureTls ==========
```

**Comment by jsturtevant** [comment]
Unit tests are failing due to linter check:

```
==> Running Go linter <==
golangci-lint has version 1.39.0 built from 9aea4aee on 2021-03-26T08:02:53Z
Running inside container
pkg/api/vlabs/types.go:193:2: struct field `WindowsSecureTlsEnabled` should be `WindowsSecureTLSEnabled` (golint)
	WindowsSecureTlsEnabled       *bool             `json:"windowsSecureTlsEnabled,omitempty"`
	^
pkg/api/types.go:192:2: struct field `WindowsSecureTlsEnabled` should be `WindowsSecureTLSEnabled` (golint)
	WindowsSecureTlsEnabled       *bool             `json:"windowsSecureTlsEnabled,omitempty"`
	^
pkg/engine/armvariables.go:641:2: var `windowsSecureTlsEnabled` should be `windowsSecureTLSEnabled` (golint)
	windowsSecureTlsEnabled := false
```

**Comment by jsturtevant** [comment]
@ablehe we will want to bump the vhd configuration script to put the new package on the VHD

**Comment by AbelHu** [comment]
> @ablehe we will want to bump the vhd configuration script to put the new package on the VHD

Created a new PR: https://github.com/Azure/aks-engine/pull/4581

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by jsturtevant — APPROVED** [review]

**Pull request merged**
