### PR TITLE
fix: disable accelerated networking for Windows due to instability

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

Disable accelerated networking for Windows pools. See:

https://github.com/Azure/aks-engine/issues/2281

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by PatrickLang** [comment]
@marosset - want to look? seems ok to me

**Comment by marosset** [comment]
https://github.com/Azure/aks-engine/issues/2281 is related.
Should be ok to disable until that issue is resolved.

**Comment by marosset** [comment]
https://github.com/Azure/aks-engine/issues/2281 is related.
Should be ok to disable until that issue is resolved.

**Comment by richkgit** [comment]
Any chance we are getting this back?   Accelerated Networking is a definite boost to performance.

**Pull request merged**
