### PR TITLE
fix: do not override vnetCidr param when empty string

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

azuredeploy.json

    "vnetCidr": {
      "defaultValue": "10.0.0.0/8",
      "metadata": {
        "description": "Cluster vnet cidr"
      },
      "type": "string"
    },
azuredeploy.parameters.json overrides this with the empty string which results in an empty vnetCidr.

**Issue Fixed**:

#1550 

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@PatrickLang @Alwandy @msbecker

**Comment by CecileRobertMichon** [comment]
I have [another attempt](https://github.com/Azure/aks-engine/compare/master...CecileRobertMichon:fix-default-vnet-cidr) at rationalizing the vnetCidr defaults and using apimodel defaults instead of ARM param defaults but it's more complex so I'd rather start with this PR as an easy, straightforward fix.

**Comment by Alwandy** [comment]
@CecileRobertMichon first fix looks good to me, 

2nd fix looks OK, assuming that it will merge with the 1st fix? Or any reason why you won't be setting: 
`if properties.OrchestratorProfile.IsKubernetes() && properties.MasterProfile.VnetCidr != ""` on 2nd fix?

**Comment by PatrickLang** [comment]
I think this fix makes the most sense - we shouldn't set an empty parameter that overrides the variables default.

For the second approach - I don't see why there's an if (windows) type decision tree. We should be passing the same networking parameters down to both Windows & Linux nodes and I would rather aim to get those consistent.

**Comment by PatrickLang** [comment]
this is included in https://github.com/Azure/aks-engine/releases/tag/v0.38.0 :)

**Pull request merged**
