### PR TITLE
feat: update img binary to v0.5.6

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

Use the latest published version of `img` for the binary we put on the node vms.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
to @mboersma for updating acs-mirror binaries

Here's the canonical source:

https://github.com/genuinetools/img/releases/tag/v0.5.6

**Comment by CecileRobertMichon** [comment]
we should run a non-docker container runtime cluster e2e test for this as it's the only path using img (non of our current e2e tests cover that I believe).

/hold

**Comment by CecileRobertMichon** [comment]
codecov will work after rebase

/label needs-rebase

**Pull request merged**
