### PR TITLE
feat: add "coming soon" regions to allow list

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

Adds some new and some "coming soon" regions to the list of allowed AKS engine locations:
- brazilus
- israelcentral
- italynorth
- polandcentral
- spaincentral

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
cc: @bridgetkromhout

**Comment by CecileRobertMichon** [comment]
I don't see `brazilus` and `polandcentral` being added in the PR even though the description mentions them, are those missing ?

**Comment by mboersma** [comment]
> are those missing ?

No, they are in the azure_locations.go file which is the actual gatekeeper. The other three locations required special handling since they aren’t (yet) visible via the API. Finally, the other three regions also had to be added to the test output (but not the two you mentioned) because that UT expects the command to list just the static or “special” locations.

**Comment by CecileRobertMichon** [comment]
this should be ready to rebase and rerun tests

**Review by bridgetkromhout — APPROVED** [review]
LGTM

**Pull request merged**
