### PR TITLE
fix: Add support for low pri scalesets in windows agents

### PR DESCRIPTION
**Pull request by tariq1890**
Why should windows miss out on the fun  ;)

cc @asw101

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@tariq did you try a deployment with windows + ScaleSetPriority = "Low" and verify the result?

code lgtm

**Comment by tariq1890** [comment]
@CecileRobertMichon I can confirm that this works

**Comment by PatrickLang** [comment]
sure - nothing Windows specific here. If it passes CI with those set in the API model then LGTM

**Comment by tariq1890** [comment]
Thanks @PatrickLang !

**Pull request merged**
