### PR TITLE
chore: releasing new Windows VHD with Nov 2019 patches/updated bins

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
UT error is weird...

**Comment by devigned** [comment]
uhm... looks like there is a gofmt error.

**Comment by marosset** [comment]
looking

**Comment by jackfrancis** [comment]
@devigned yep, had to fix it manually on my PR as well

**Comment by devigned** [comment]
I think this should be fixed in master now with: https://github.com/Azure/aks-engine/pull/2423#event-2872005240

**Pull request merged**
