### PR TITLE
docs: remove mention about library for AKS

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR removes the mention in the landing page README.md about AKS Engine being a library for AKS.

Historically, this was true, but more and more any AKS Engine usage by AKS is more or less piecemeal, and not obvious to the public, so we should stop suggesting otherwise.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @craiglpeters @palma21

**Comment by mboersma** [comment]
In the FAQ we also say:

> AKS uses AKS Engine internally, but they are not the same.

I assume that language is vague and correct enough to remain intact.

**Comment by jackfrancis** [comment]
@mboersma good find! No, I don't think we should say that either, updated the FAQ language.

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
