### PR TITLE
fix: enable Windows plus custom VNET

### LINKED ISSUE #210: Windows nodes initialization script fails in hybrid cluster with custom VNet
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
Version: v0.28.1
GitCommit: efc9dcfd
GitTreeState: clean
---

**Kubernetes version**:
1.11.5

**What happened**:
Deployed hybrid cluster in custom vnet with one subnet. kuberneteswindowssetup.ps1 failed to configure networking because MasterSubnet parameter was null or empty. 

Fixed this manually by providing 'masterSubnet' parameter in azuredeploy.parameters.json and deploying generated ARM template.

Cluster definition:
```json
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.11",
            "orchestratorVersion": "1.11.5"
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "dnsPrefix",
            "vmSize": "Standard_D2_v2",
            "vnetSubnetId": "subnet",
            "agentVnetSubnetId": "subnet",
            "firstConsecutiveStaticIP": "192.168.255.200",
            "vnetCidr": "192.168.255.0/24"
        },
        "agentPoolProfiles": [{
                "name": "win",
                "count": 1,
                "vmSize": "Standard_DS2_v2",
                "vnetSubnetId": "subnet",
                "osType": "Windows"
            },
            {
                "name": "linux",
                "count": 1,
                "vmSize": "Standard_DS2_v2",
                "vnetSubnetId": "subnet"
            }
        ],
        "windowsProfile": {
            "adminUsername": "adminUsername",
            "adminPassword": "adminPassword"
        },
        "linuxProfile": {
            "adminUsername": "adminUsername",
            "ssh": {
                "publicKeys": [{
                    "keyData": "ssh-rsa ..."
                }]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "clientId",
            "secret": "secret"
        }
    }
}
```

**What you expected to happen**:
masterSubnet parameter is set during ARM template generation process

**How to reproduce it** (as minimally and precisely as possible):
Deploy provided cluster into a custom VNet with a single subnet.

**Anything else we need to know**:

### LINKED ISSUE #341: Windows pod creation always fails with Pod sandbox changed - Failed create pod sandbox
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of aks-engine?**:

Version: v0.28.1
GitCommit: efc9dcfd
GitTreeState: clean

**Kubernetes version**: v1.9.11

**What happened**: 

Our containerized application suddenly stopped working and now all pods on windows nodes are stuck in a restart cycle of:

Normal   SandboxChanged          5m (x2207 over 4h)   kubelet, 3401k8s012  Pod sandbox changed, it will be killed and re-created.

Warning  FailedCreatePodSandBox  20s (x2230 over 4h)  kubelet, 3401k8s012  Failed create pod sandbox.

**What you expected to happen**:

I have deleted all deployments and services, rebooted all Windows nodes and the Linux master and attempted to reapply all deployments and services, but all pods are stuck in the error cycle above

**How to reproduce it** (as minimally and precisely as possible):

I don't know the exact steps as it occurred suddenly. However this has now happened in two separate aks-engine deployments in the last 4 days.

**Anything else we need to know**:

It's a mixed cluster of Windows and Linux nodes. This only effects pods running on Windows nodes; however it impacts all pods on Windows nodes.

The cluster looks like:

PS:> kubectl get nodes -o wide
NAME                        STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION     CONTAINER-RUNTIME
3401k8s010                  Ready     agent     7d        v1.9.11   <none>        Windows Server Datacenter   10.0.17763.253     docker://18.9.0
3401k8s011                  Ready     agent     7d        v1.9.11   <none>        Windows Server Datacenter   10.0.17763.253     docker://18.9.0
3401k8s012                  Ready     agent     7d        v1.9.11   <none>        Windows Server Datacenter   10.0.17763.253     docker://18.9.0
3401k8s013                  Ready     agent     7d        v1.9.11   <none>        Windows Server Datacenter   10.0.17763.253     docker://18.9.0
3401k8s014                  Ready     agent     7d        v1.9.11   <none>        Windows Server Datacenter   10.0.17763.253     docker://18.9.0
k8s-linuxpool1-34014015-0   Ready     agent     7d        v1.9.11   <none>        Ubuntu 16.04.5 LTS          4.15.0-1035-azure  docker://3.0.1
k8s-master-34014015-0       Ready     master    7d        v1.9.11   <none>        Ubuntu 16.04.5 LTS          4.15.0-1036-azure  docker://3.0.1

Deployed with aks-version v0.28.1

PS:> aks-engine version
Version: v0.28.1
GitCommit: efc9dcfd
GitTreeState: clean

### LINKED ISSUE #1289: Question: AKS Windows supports custom vnet, AKS-E doesn't
I joined the AKS Windows private preview today, I found it supports custom vnet for hybrid Linux and Windows cluster. As far as I know AKS-E deploy and scale doesn't work with custom vnet  yet, see #210 #431.

From my understanding AKS is based on AKS-E, one of tags in my created AKS Windows pool is `aksEngineVersion : v0.33.4-aks`. I am wondering how this happend, does the AKS team fixed this issue on their branch, if it is yes, can you merge that back to AKS-E?

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

Windows node implementation depends upon a MasterSubnet variable that needs to have a different value if custom VNET vs aks-engine-generated VNET

**Issue Fixed**:

Fixes #1289 
Fixes #210 
Fixes #341

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Manually validated the following cluster config:

```
{   "apiVersion": "vlabs",   "properties": {     "orchestratorProfile": {       "orchestratorType": "Kubernetes", "orchestratorRelease": "1.14",       "kubernetesConfig": {         "clusterSubnet": "10.239.0.0/16",         "addons": [           {             "name": "tiller",             "enabled": true,             "config": {               "max-history": "10"             },             "containers": [               {                 "name": "tiller",                 "cpuRequests": "1",                 "memoryRequests": "1Gi",                 "cpuLimits": "1",                 "memoryLimits": "1Gi"               }             ]           },           {             "name": "kubernetes-dashboard",             "enabled": true,             "containers": [               {                 "name": "kubernetes-dashboard",                 "cpuRequests": "50m",                 "memoryRequests": "512Mi",                 "cpuLimits": "50m",                 "memoryLimits": "512Mi"               }             ]           },           {             "name": "rescheduler",             "enabled": true,             "containers": [               {                 "name": "rescheduler",                 "cpuRequests": "20m",                 "memoryRequests": "200Mi",                 "cpuLimits": "20m",                 "memoryLimits": "200Mi"               }             ]           }         ]       }     },     "masterProfile": {       "count": 3,       "dnsPrefix": "",       "vmSize": "Standard_D2_v2",       "OSDiskSizeGB": 200,       "vnetSubnetId": "/subscriptions/SUB_ID/resourceGroups/RG_NAME/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME",       "firstConsecutiveStaticIP": "10.239.255.239",       "vnetCidr": "10.239.0.0/16"     },     "agentPoolProfiles": [       {         "name": "agent1",         "count": ${NODE_COUNT},         "vmSize": "Standard_D2_v2",         "OSDiskSizeGB": 200,         "storageProfile": "ManagedDisks",         "diskSizesGB": [           128,           128,           128,           128         ],         "availabilityProfile": "AvailabilitySet",         "vnetSubnetId": "/subscriptions/SUB_ID/resourceGroups/RG_NAME/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME"       },       {         "name": "agentwin",         "count": ${NODE_COUNT},         "vmSize": "Standard_D2_v2",         "availabilityProfile": "AvailabilitySet",         "osType": "Windows", "vnetSubnetId": "/subscriptions/SUB_ID/resourceGroups/RG_NAME/providers/Microsoft.Network/virtualNetworks/VNET_NAME/subnets/SUBNET_NAME"       }     ],     "windowsProfile": {       "adminUsername": "azureuser",       "adminPassword": "replacepassword1234$", "enableAutomaticUpdates": false, "sshEnabled": true     }, "linuxProfile": {       "adminUsername": "azureuser",       "ssh": {         "publicKeys": [           {             "keyData": ""           }         ]       }     },     "servicePrincipalProfile": {       "clientId": "",       "secret": ""     }   } }
```

**Comment by djsly** [comment]
@jackfrancis , how long normally for AKS to pickup your latest fixes in AKS-Engine ? WE were looking at using custom VNET with AKS and Windows node pool and we couldnt get the Windows node to show up in Kubernetes.  Compared to when we are using a dynamic VNET.

**Comment by PatrickLang** [comment]
@djsly can you open an issue here? https://github.com/azure/aks/issues if you can give a few details on the use case that's helpful too. AKS roadmap is maintained in that repo

**Comment by djsly** [comment]
@PatrickLang , will do! about this particular issue, we are goo using custom Vnet with Windows node in the end... :)

**Pull request merged**
