### PR TITLE
feat: flexvol and csi addons disabled by default

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR changes the default addons installation flow so that the following addons are no longer installed by default:

- blobfuse flexvolume
- keyvault flexvolume

The above addons will be disabled by default because they have been deprecated in favor of alternate solutions

- secrets-csi-driver

The above addon will be disabled by default because it is no longer actively maintained, and the preferred maintenance gesture is to use the official helm chart.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @andyzhangx @aramase

**Comment by andyzhangx** [comment]
it's ok to disable blobfuse flexvol driver since it's deprecated, user should use blob csi drive instead, thanks.

**Comment by jackfrancis** [comment]
@andyzhangx thx for confirming! :)

**Review by Michael-Sinz — APPROVED** [review]
Ahh, this is so good to see - I can (eventually) reduce the list of things I have to disable as they were enabled by default.

Only concern would be teams that may depend on this.  We will need to make sure that this is called out expressly in the release notes as a "breaking" change and that the user would need to expressly enable these addons if they wanted to continue to use them.

**Comment by jackfrancis** [comment]
@Michael-Sinz the current release CI allows project maintainers to edit and curate the release notes before merging to the release branch (that merge acts as a gate to actually validate and publish release artifacts). So you'll have a chance to weigh in then to ensure we're doing sufficient communication.

**Comment by Michael-Sinz** [comment]
> @Michael-Sinz the current release CI allows project maintainers to edit and curate the release notes before merging to the release branch (that merge acts as a gate to actually validate and publish release artifacts). So you'll have a chance to weigh in then to ensure we're doing sufficient communication.

Will have to see how that works out - I hope it gives hints as to what all of the changes were from the prior release.

**Review by mboersma — APPROVED** [review]

**Pull request merged**
