### PR TITLE
Chore: updating Az CNI to v1.2.0_hotfix

### PR DESCRIPTION
**Pull request by vakalapa**
**Reason for Change**:

Adding a critical fix to azure transparent mode CNI for mitigating intitial latency issue

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [x] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by matmerr** [comment]
Hey @jchauncey can we mirror 

https://acnreleaseartifacts.azureedge.net/azure-cni/v1.2.0_hotfix/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.2.0_hotfix.zip

to the storage account behind kubernetesartifacts?

**Comment by sozercan** [comment]
@matmer done

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by marosset** [comment]
This change broke the Windows VHD builds.
https://kubernetesartifacts.azureedge.net/azure-cni/v1.2.0/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.2.0_hotfix.zip does not resolve.
@vakalapa  Please take a look.

**Comment by marosset** [comment]
looks like that URL needs to be https://kubernetesartifacts.azureedge.net/azure-cni/v1.2.0_hotfix/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.2.0_hotfix.zip - i'll create a patch

**Comment by jackfrancis** [comment]
Lemme know if a rollback of the regressing PR makes things easier (feel free to initiate that yourself as well)

**Comment by marosset** [comment]
> Lemme know if a rollback of the regressing PR makes things easier (feel free to initiate that yourself as well)

Nah, it is easy to fix.
I wonder why status didn't get reported for the Windows VHD Azure DevOps job for this PR :(

**Pull request merged**
