### PR TITLE
feat: adding Windows VHD with 1.18.0 k8s binaries

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

Adding Windows VHD with 1.18.0 k8s binaries

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
/hold

Need to investigate this deployment error
2020-03-30T15:40:36.7593530Z Error from deployment for kubernetes-eastus-35561 in resource group kubernetes-eastus-35561:exit status 1
2020-03-30T15:40:36.7595291Z 2020/03/30 15:40:36 Command Output: ERROR: Deployment failed. Correlation ID: a0ac9d18-3c14-479a-a555-618689248dbb. {
2020-03-30T15:40:36.7596775Z   "error": {
2020-03-30T15:40:36.7597644Z     "code": "SubscriptionNotAuthorizedForImage",
2020-03-30T15:40:36.7598476Z     "message": "The subscription is not authorized.",
2020-03-30T15:40:36.7599409Z     "target": "imageReference"
2020-03-30T15:40:36.7600287Z   }
2020-03-30T15:40:36.7601043Z }

**Comment by jackfrancis** [comment]
We won't be exposing 1.18.0 to users, as it doesn't have this fix in it:

https://github.com/kubernetes/kubernetes/pull/89604

@aramase, will the above be a part of 1.18.1?

**Comment by aramase** [comment]
@jackfrancis correct, it'll be available in `1.18.1`

cherry pick PR for 1.18 - https://github.com/kubernetes/kubernetes/pull/89605

**Pull request closed without merging**
