### PR TITLE
fix(auth): Explicitly import the AAD library to allow cluster upgrades

### PR DESCRIPTION
**Pull request by skinny**
After https://github.com/Azure/aks-engine/pull/506 was closed/merged it's still not possible to upgrade clusters with AAD support enabled. During the upgrade or scaling operation the error

`FATA[0377] Error upgrading cluster: No Auth Provider found for name "azure"`

still appears. This PR fixes that.

### CODE REVIEW

**Comment by mboersma** [comment]
It looks like some symlinks got checked in as files in this PR, which will cause problems when checking out to UNIX-y platforms. I'm not entirely sure how to fix that, but maybe it's related to the [core.symlinks](https://git-scm.com/docs/git-config) git setting?

**Comment by skinny** [comment]
Yeah I didnt know what to do with those either. They got changed when I updated the deps and build the project so I reckoned they should be updated as well

**Comment by mboersma** [comment]
Here's the problem I see:

```
$ git co -b aad-upgrade-support skinny/aad-upgrade-support
error: unable to create symlink vendor/github.com/go-bindata/go-bindata/testdata/symlinkFile/file1: File name too long
error: unable to create symlink vendor/github.com/go-bindata/go-bindata/testdata/symlinkParent/symlinkTarget: File name too long
error: unable to create symlink vendor/github.com/go-bindata/go-bindata/testdata/symlinkRecursiveParent/symlinkTarget: File name too long
D	vendor/github.com/go-bindata/go-bindata/testdata/symlinkFile/file1
D	vendor/github.com/go-bindata/go-bindata/testdata/symlinkParent/symlinkTarget
D	vendor/github.com/go-bindata/go-bindata/testdata/symlinkRecursiveParent/symlinkTarget
Branch 'aad-upgrade-support' set up to track remote branch 'aad-upgrade-support' from 'skinny'.
Switched to a new branch 'aad-upgrade-support'
```

Maybe not a critical issue since the links are in a vendored `testdata` folder, but IDK if this will cause future merge issues. I'll try to re-vendor on top of this from macOS and update the PR if I can.

**Comment by skinny** [comment]
@mboersma no problem! As long as the end result is the same its fine by me 😊

Thanks and have a great weekend

**Comment by mboersma** [comment]
Codecov didn't report back on this PR, so the bot won't merge it. I'll do that.

**Pull request merged**
