### PR TITLE
chore: Use prod repos for containerd.

### PR DESCRIPTION
**Pull request by cpuguy83**
**Reason for Change**:

containerd was moved to our prod repos, so let's use that.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
I was just trying these commands to see the diff and found some oddity. We should make double-sure this works for 18.04:

```shell
 % curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
% curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main%  
% # Is the trailing "%" char ok when it ends up at /etc/apt/sources.list.d/microsoft-prod.list?
```

**Comment by jackfrancis** [comment]
``` 
Error from deployment for kubernetes-southeastasia-53976 in resource group kubernetes-southeastasia-53976:exit status 1
 2020/04/21 18:41:18 Command Output: ERROR: Deployment failed. Correlation ID: a7b0c5c5-5b16-44b3-bc55-15b476434882. {
   "status": "Failed",
   "error": {
     "code": "ResourceDeploymentFailure",
     "message": "The resource operation completed with terminal provisioning state 'Failed'.",
     "details": [
       {
         "code": "VMExtensionProvisioningError",
         "message": "VM has reported a failure when processing extension 'cse-master-0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=27\n[stdout]\nTue Apr 21 18:33:46 UTC 2020,k8s-master-31250611-0\n\n[stderr]\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
       }
     ]
   }
 }
```

**Comment by cpuguy83** [comment]
Argh, issue is because prod repo didn't have containerd 1.3.2 (only 1.3.3).
I've gone ahead and pushed that version to the repo now.

**Comment by cpuguy83** [comment]
@jackfrancis It seems CI had some issues and couldn't run. Did you run this locally?

**Comment by jackfrancis** [comment]
Yes, I ran several jenkins jobs against the branch using a containerd cluster config

**Pull request merged**
