### PR TITLE
chore: Update Azure CNI to v1.2.2

### PR DESCRIPTION
**Pull request by AbelHu**
**Reason for Change**:

Update Azure CNI to v1.2.2.
The fix [Write to intermediate file before moving to state file](https://github.com/Azure/azure-container-networking/commit/98f838ef1b7fc1a6ef0a3f1b34b81840d703469e) in v1.2.2 is very important for Windows.

Please see more details in Azure CNI v1.2.2 release notes:
https://github.com/Azure/azure-container-networking/releases/tag/v1.2.2

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by jsturtevant — APPROVED** [review]

**Comment by jsturtevant** [comment]
@jackfrancis fyi on azure cni version update on Linux.  I'll let you merge if you have no objections

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by marosset — COMMENTED** [review]
/lgtm

**Pull request merged**
