### PR TITLE
feat: add support for Kubernetes v1.24.16

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v12415

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@mboersma want to rebase?

**Comment by CecileRobertMichon** [comment]
opened https://github.com/Azure/aks-engine/pull/5104 for the VHD failure

**Review by CecileRobertMichon — APPROVED** [review]
lgtm

**Comment by mboersma** [comment]
I have a PR ready for Kubernetes v1.24.17. I'll open it as soon as our k8s build pipeline passes.

**Comment by mboersma** [comment]
> Do you still want to merge this one?

We can make it a lower priority than the other two that are open. But it may take a while for the pipeline build to succeed (I saw some tests fail on the first pass), so let's do plan to merge it.

**Comment by mboersma** [comment]
Update: I'll close this when #5112 passes and we can merge v1.24.17 instead.

**Comment by mboersma** [comment]
See #5112

**Pull request closed without merging**
