### PR TITLE
chore: updating azure cni version to v1.1.0

### PR DESCRIPTION
**Pull request by tamilmani1989**
**Reason for Change**:

1. Azure CNI IPVS Support Linux
2. Azure CNI Dualstack Support Linux - vnet v4 ips and non-vnet v6 ips
3. Bug fixes

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
Is there a release of this with signed binaries? I expect #2992 to merge soon, and we need to sign all the binaries we put on disk in the future.

**Comment by tamilmani1989** [comment]
> Is there a release of this with signed binaries? I expect #2992 to merge soon, and we need to sign all the binaries we put on disk in the future.

is this requirement only for windows binaries right?

**Comment by mboersma** [comment]
Yes, I think we're primarily concerned with Windows binaries being signed.

**Comment by jchauncey** [comment]
Ive published the 1.1.0 binaries to the prod storage account. The pipeline will change on how we consume these going forward but this should unblock this pr

**Comment by tamilmani1989** [comment]
@jchauncey  Thanks. are the binaries uploaded to mirror? if so , can you please retrigger test? it looks like the test failed while fetching cni

==> azure-arm: + timeout 60 curl -fsSL https://kubernetesartifacts.azureedge.net/azure-cni/v1.1.0/binaries/azure-vnet-cni-linux-amd64-v1.1.0.tgz -o /opt/cni/downloads/azure-vnet-cni-linux-amd64-v1.1.0.tgz
==> azure-arm: curl: (22) The requested URL returned error: 404 Not Found

**Comment by jchauncey** [comment]
its there now.. im not sure if ihave the ability to retrigger the tests or not.

**Comment by tamilmani1989** [comment]
> its there now.. im not sure if ihave the ability to retrigger the tests or not.

i think you should have. can you try this "/azp run pr-e2e"

**Comment by tamilmani1989** [comment]
@mboersma  @jackfrancis  tests cancelled due to timeout. can you please check?

**Pull request merged**
