### PR TITLE
fix: omit NSG rules for Upgrade scenario

### LINKED ISSUE #1624: Application not accessible from outside cluster during aks-engine Upgrade
Applications are not accessible from outside the cluster during the aks-engine upgrade

**Steps To Reproduce**
1. Deploy application(say nginx) and service of type LoadBalancer to expose the application to be accessed from outside the cluster
2. Upgrade cluster using aks-engine upgrade. During upgrade operation the application will not be accessible from outside the cluster

**Expected behavior**
Should be able to access the application from outside the cluster during upgrade process

**AKS Engine version**
v0.36.2

**Kubernetes version**
1.12.8

**Additional context**

### PR DESCRIPTION
**Pull request by Bhuvaneswari-Santharam**
**Reason for Change**:

Retain NSG rules created by workloads during upgrade scenario

**Issue Fixed**:

Fixes #1624

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by Bhuvaneswari-Santharam** [comment]
cc @honcao @CecileRobertMichon @jadarsie @rjaini @jackfrancis

**Comment by mboersma** [comment]
Codecov didn't report in here, so I'm merging manually.

**Pull request merged**
