### PR TITLE
feat: add support for Kubernetes v1.17.12

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v11711

**Issue Fixed**:

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

This PR contains a temporary commit for testing that should be removed before merging.

**Comment by mboersma** [comment]
> exceeded regional cores quota

Sigh.

**Comment by mboersma** [comment]
This [passed CI](https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=5818&view=logs&jobId=2af82614-90d1-512d-fa5b-6cc2930bb489), so I'll strip off the test commit and it should be ready for review.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
