### PR TITLE
fix: metrics server cluster role

### LINKED ISSUE #1707: Update metrics-server from 0.2.1 to 0.3.3 don't work properly.
**Describe the bug**
I tried to update the metrics-server (installed with addons manager) from v0.2.1 to v0.3.3. After the update the metrics-server stop to work properly.

I changed in the yaml file of metrics server only the version of the docker image, removed the option `--source=kubernetes.summary_api:''` and added these two other options `--kubelet-insecure-tls --kubelet-preferred-address-types=InternalIP`

These are the logs:

`I0731 14:37:31.683039       1 serving.go:312] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0731 14:37:32.938791       1 secure_serving.go:116] Serving securely on [::]:443
E0731 14:37:38.441048       1 reststorage.go:147] unable to fetch pod metrics for pod kube-system/nginx-ingress-release-controller-cc7968ffb-jjp2c: no metrics known for pod`
[... a lot of logs in this way and sometimes this]
`E0731 14:38:32.957151       1 manager.go:111] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:k8s-minion-75668405-vmss000076: unable to fetch metrics from Kubelet k8s-minion-75668405-vmss000076 (10.245.0.114): request failed - "401 Unauthorized", response: "Unauthorized", unable to fully scrape metrics from source kubelet_summary:k8s-master-75668405-0: unable to fetch metrics from Kubelet k8s-master-75668405-0 (10.245.255.200): request failed - "401 Unauthorized", response: "Unauthorized", unable to fully scrape metrics from source kubelet_summary:k8s-minion-75668405-vmss000078: unable to fetch metrics from Kubelet k8s-minion-75668405-vmss000078 (10.245.1.80): request failed - "401 Unauthorized", response: "Unauthorized"]`

**Steps To Reproduce**
Install metrics-server v0.2.1 on a cluster, edit the addons-manager config file for metrics-server changing docker version and running options as mentioned above and wait a couple of minutes that addons-manager redeploy the package.

**Expected behavior**
Nothing special, I would like metrics-server continue to work

**AKS Engine version**
v0.33.2

**Kubernetes version**
1.13.5

**Additional context**
Other ref:
https://github.com/kubernetes-incubator/metrics-server/issues/293
https://github.com/Azure/aks-engine/issues/1172

### PR DESCRIPTION
**Pull request by PierluigiLenociAkelius**
**Reason for Change**:

Fix the deployment for v0.3.3 of metrics-server

**Issue Fixed**:

Fixes #1707 

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [x] tested upgrade from previous version

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @PierluigiLenociAkelius! Could you also update the metrics-server spec for 1.16 here:

`parts/k8s/containeraddons/1.16/kubernetesmasteraddons-metrics-server-deployment.yaml`

**Comment by jackfrancis** [comment]
@PierluigiLenociAkelius I've cleaned up the PR so that it will work w/ 1.16 as well. Could you kindly sign the CLA (linked above)?

Thanks!

**Comment by PierluigiLenociAkelius** [comment]
@jackfrancis we are ready to merge, I presume! 😄

**Pull request merged**
