### PR TITLE
chore: deprecate kubernetes versions 1.8 and 1.7

### PR DESCRIPTION
**Pull request by tariq1890**
This PR will deprecate k8s versions 1.7.* and 1.8.*

It should also address #132

### CODE REVIEW

**Comment by tariq1890** [comment]
@mboersma I have rebased this PR.

**Comment by tariq1890** [comment]
@CecileRobertMichon FYI. I have rebased this PR

**Comment by mboersma** [comment]
@tariq1890 I created merge conflicts for you with #232. 😞

**Comment by tariq1890** [comment]
I understand the rationale in that AKS-Engine provides that freedom and is less restrictive comparatively. But I don't see the value in keeping 1.8 support here and I think flexibility along other vectors (addon management, special skus, network configs, hybrid node pools) is what makes aks-engine shine. Kubernetes is fast moving and I think 1.8 is hardly ever used. My 2 cents.

**Comment by jackfrancis** [comment]
lgtm

**Pull request merged**
