### PR TITLE
feat: add support for Flatcar Container Linux

### PR DESCRIPTION
**Pull request by invidian**
**Reason for Change**:

This PR adds support for [Flatcar Container Linux](https://www.flatcar-linux.org/), based on previously supported CoreOS, which support has been removed because of upcoming EoL.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @invidian! Expect a thorough review next week.

**Comment by jackfrancis** [comment]
Hi @invidian, if you can grant this PR maintainer edit privileges I can push up some rebased changes that get this closer to merging. See https://github.com/Azure/aks-engine/pull/3380 for the changeset I'm testing.

**Comment by invidian** [comment]
Hey @jackfrancis, thanks for the update. Unfortunately, I cannot grant you the maintainer edit privileges, as this is a PR coming from organization fork, not the private one. I can pull the changes from #3380 branch and push them here or we can just close this PR, if you want to take over in #3380.

**Comment by jackfrancis** [comment]
Let's collaborate on #3380, thanks!

**Pull request closed without merging**
