### PR TITLE
feat: add support for Kubernetes 1.18.0-alpha.3

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1180-alpha2

**Issue Fixed**:

**Requirements**:

- [x] Windows artifacts uploaded to acsmirror blob store
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

Still need to mirror Windows support archive file.

**Comment by jackfrancis** [comment]
Looks we may have another I ❤️ tests story, consistent failure on kubectl port-forward.

**Comment by mboersma** [comment]
The failure arises from `ImagePullBackoff` for the nginx deployment, but the specific error is new to me:

```console
% k describe pod portforwardlinux-2726 
Name:         portforwardlinux-2726
Namespace:    default
Priority:     0
Node:         1269k8s01000000/10.239.16.4
Start Time:   Wed, 12 Feb 2020 09:28:58 -0700
Labels:       run=portforwardlinux-2726
Annotations:  kubernetes.io/psp: privileged
Status:       Pending
IP:           10.239.16.18
IPs:
  IP:  10.239.16.18
Containers:
  portforwardlinux-2726:
    Container ID:   
    Image:          library/nginx:latest
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2fp2j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-2fp2j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2fp2j
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason          Age                  From                      Message
  ----     ------          ----                 ----                      -------
  Normal   Scheduled       31m                  default-scheduler         Successfully assigned default/portforwardlinux-2726 to 1269k8s01000000
  Normal   SandboxChanged  30m (x4 over 31m)    kubelet, 1269k8s01000000  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         30m (x3 over 31m)    kubelet, 1269k8s01000000  Pulling image "library/nginx:latest"
  Warning  Failed          30m (x3 over 31m)    kubelet, 1269k8s01000000  Failed to pull image "library/nginx:latest": rpc error: code = Unknown desc = no matching manifest for windows/amd64 10.0.17763 in the manifest list entries
  Warning  Failed          63s (x133 over 31m)  kubelet, 1269k8s01000000  Error: ImagePullBackOff

```

**Comment by mboersma** [comment]
I think this broke because e2e tests use `kubectl run` and expect it to generate a deployment, which doesn't happen after kubernetes/kubernetes#87077 merged.

**Pull request merged**
