### PR TITLE
[FakeFake] fix: this is a fake change.

### PR DESCRIPTION
**Pull request by andyliuliming**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by andyliuliming** [comment]
@CecileRobertMichon 
this PR is to mock the PR after merged this PR: https://github.com/Azure/aks-engine/pull/1088

**Comment by andyliuliming** [comment]
@CecileRobertMichon "Azure Pipelines could not run because the pipeline triggers exclude this branch/path." :(

**Comment by CecileRobertMichon** [comment]
@andyliuliming in order to mock the situation we need two PRs modifying the parts/ directory and one of them merging before the other to see if that creates merge conflicts in the second PR.

**Comment by CecileRobertMichon** [comment]
you're not trying to merge into Azure/master, we only run the pipeline on the Azure/master branch that's why you're getting that error message.

**Comment by andyliuliming** [comment]
> @andyliuliming in order to mock the situation we need two PRs modifying the parts/ directory and one of them merging before the other to see if that creates merge conflicts in the second PR.

yes, that's I'm trying to do here.

 andliu/go_bin_data  branch is used to as a base branch like the master.

and the PR here is to mock one PR after the PR 1088 is merged.
and actually you can see the change is very clear here, and the git will definitely auto merge for us.

**Comment by CecileRobertMichon** [comment]
what about `make ensure-generated`? I'll temporarily allow the pipeline on your fork so we can try it out

**Comment by andyliuliming** [comment]
looks like all pass.

**Pull request closed without merging**
