### PR TITLE
fix: replace some leftover acsengine by aksengine

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

Fix some acs-engine references that were left in the code. Most are variables. One is the `generatorCode` that is used in the `CreationSource` tag for VMs.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
/hold

Let's get https://github.com/Azure/aks-engine/pull/253 merged first, as this one will probably be easier to resolve merge conflicts than that one

**Comment by CecileRobertMichon** [comment]
@bacongobbler I rebased can you please do a quick check to make sure I didn't unintentionally undo some of your doc changes?

**Pull request merged**
