### PR TITLE
chore: update omsagent addon to use the latest version

### PR DESCRIPTION
**Pull request by rashmichandrashekar**
Update omsagent addon to use the latest released version - ciprod04232019 and the corresponding yaml changes

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm pending omsagent cluster configuration test (in-progress)

**Comment by jackfrancis** [comment]
omsagent cluster config test failed against this PR:

```
Azure Container Cluster using the Kubernetes Orchestrator
/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:91
  regardless of agent pool type
  /go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:92
    should have addons running [It]
    /go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:467

    Expected error:
        <*errors.fundamental | 0xc000446ce0>: {
            msg: "Timeout exceeded (30m0s) while waiting for Pods (omsagent) to become ready in namespace (kube-system), got 0 of 6 required successful pods ready results",
            stack: [0x9c6ad4, 0x45e941],
        }
        Timeout exceeded (30m0s) while waiting for Pods (omsagent) to become ready in namespace (kube-system), got 0 of 6 required successful pods ready results
    not to have occurred

    /go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:485
```

**Comment by rashmichandrashekar** [comment]
@jackfrancis - I have updated the PR for this test fix. Please run the tests again and this should pass now.

**Pull request merged**
