### PR TITLE
feat: upgrade azure disk csi driver to v1.7.0

### PR DESCRIPTION
**Pull request by andyzhangx**
**Reason for Change**:

feat: upgrade azure disk csi driver to v1.7.0

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by andyzhangx** [comment]
how can I rerun `pr-e2e (k8s_1_21_docker_e2e) `? I doubt whether the test failure is related to this PR.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
