### PR TITLE
feat: support configurable `tags` and `enableMultipleStandardLoadBalancers`

### PR DESCRIPTION
**Pull request by nilo19**
**Reason for Change**:

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

Fixes: https://github.com/Azure/aks-engine/issues/4035

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @nilo19 

I think we should merge this support w/ cluster-api Azure day-and-date with aks-engine

@CecileRobertMichon @devigned are you aware of these 2 upstream changes that this aks-engine PR supports?

https://github.com/kubernetes/kubernetes/pull/96111
https://github.com/kubernetes/kubernetes/pull/96450

**Comment by CecileRobertMichon** [comment]
CAPZ [supports BYO azure.json secret](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/book/src/topics/cloud-provider-config.md) already so no code changes should be needed to try this today.

In the future, if this is a common configuration, we should consider exposing them in the spec to make UX a little smoother for users who don't want to have to provide the entire config, similar to https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/815.

**Comment by nilo19** [comment]
Do we plan to merge this?

**Comment by jackfrancis** [comment]
@nilo19 I rebased on top of current master branch, and added some E2E test foo to ensure that we test this new functionality.

How can we test the tags functionality?

**Comment by nilo19** [comment]
@jackfrancis If the tags are set in azure.json, then it functions well.

**Comment by jackfrancis** [comment]
There's one more thing before we can merge this PR, we need `pkg/api/converterfromapi.go` updated as well.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
