### PR TITLE
[WIP] feat: deploy LB as part of cluster creation

### PR DESCRIPTION
**Pull request by aramase**
**Reason for Change**:

- Create LB and load agent nodes into backend pool for basic LB. This is already done with SLB.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Is this stale?

**Comment by aramase** [comment]
@jackfrancis Not stale. Will resume work on it soon.

**Comment by craiglpeters** [comment]
@aramase is this really not stale? :)

**Comment by aramase** [comment]
@craiglpeters I don't think we need this anymore given the changes for improving LB backend pool addition to the VMSSVM/VM has been merged to upstream code. 

/close

**Pull request closed without merging**
