### PR TITLE
test: unit test for azure stack AzureClient

### PR DESCRIPTION
**Pull request by honcao**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [X] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by honcao** [comment]
@deaborch @jadarsie @rjaini @vikasnav @Bhuvaneswari-Santharam

**Comment by CecileRobertMichon** [comment]
@honcao please make sure your squash commit message includes the `test: ` prefix

**Comment by honcao** [comment]
@CecileRobertMichon , Please close this PR, I opened another PR with better commit message.

**Pull request closed without merging**
