### PR TITLE
fix: use our own hpa-example image

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

Fixes a failing test by using a more recently built Docker image to test HPA.

One of our tests began failing recently because its outbound connectivity test requires `apt update` to pass. The k8s.gcr.io/hpa-example image is quite old and running `apt update` in it fails because of this recent change:
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:
I've been unable to find the Dockerfile and source for k8s.gcr.io/hpa-example to make a proper upstream fix. If you know, let me know.

### CODE REVIEW

**Comment by mboersma** [comment]
The canonical GCR [example container](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/hpa-example) was last updated on Jan 11, 2017. Things get rusty!

**Comment by mboersma** [comment]
The failing 1.10 test is unrelated. This change does appear to have fixed the HPA test problem.

**Comment by jackfrancis** [comment]
thx @mboersma!

**Pull request merged**
