### PR TITLE
feat: update pause image to v3.4.1

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

Updating pause image to v3.4.1 which supports Windows Server Ver 20H2

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
I did an install of  `datacetner-core-20h2-with-containers-smalldisk` and checked the 

(Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ReleaseId it reports as `2009`

**Comment by jackfrancis** [comment]
code lgtm, let's fix the merge conflict and run some tests

**Comment by marosset** [comment]
/hold 
Holding until new Windows VHD gets published and is set as the default VHD

**Pull request merged**
