### PR TITLE
 fix: remove deprecated sshd configs for 18.04

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

With Ubuntu 18.04-LTS, `sshd -T` shows: 
```
/etc/ssh/sshd_config line 24: Deprecated option UsePrivilegeSeparation
/etc/ssh/sshd_config line 27: Deprecated option KeyRegenerationInterval
/etc/ssh/sshd_config line 28: Deprecated option ServerKeyBits
/etc/ssh/sshd_config line 43: Deprecated option RSAAuthentication
/etc/ssh/sshd_config line 50: Deprecated option RhostsRSAAuthentication
```

```
sshd(8) no longer supports the old SSH protocol 1, so all the configuration
options related to it are now deprecated and should be removed from
/etc/ssh/sshd_config.  These are:

  KeyRegenerationInterval
  RSAAuthentication
  RhostsRSAAuthentication
  ServerKeyBits

The Protocol option is also no longer needed, although it is silently
ignored rather than deprecated.
```
https://salsa.debian.org/ssh-team/openssh/blob/master/debian/README.Debian#L240

```
 * This release deprecates the sshd_config UsePrivilegeSeparation
   option, thereby making privilege separation mandatory. Privilege
   separation has been on by default for almost 15 years and
   sandboxing has been on by default for almost the last five.
```
https://www.openssh.com/txt/release-7.5

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm pending "ubuntu" and "ubuntu1804" distro E2E

**Comment by CecileRobertMichon** [comment]
validated with ubuntu-18.04 and ubuntu-16.04 distros.

/hold cancel

**Pull request merged**
