### PR TITLE
style: mutex is not necessary now that rand uses local object

### PR DESCRIPTION
**Pull request by paulgmiller**
Mutex came in from this comment when the funciton was using rand.seed.
https://github.com/Azure/aks-engine/commit/833fe44015ff6328fa0cfa1fc70f9cd420ffde6e
But it could hav been removed after this commit when we move to using a local source and can't bleed across thread.
Here's where they moved to a local object https://github.com/Azure/aks-engine/commit/a6007e7b7d47dfaf8c2663e24ba592beb05fc9bd

Since this isn't a perf sensitive code path there's nothing gained except a few less lines of code so feel free to reject if it's not worth it. 

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
@paulgmiller our fearless leader @jackfrancis ran some other tests on this which failed, but didn't have time to follow up. Sorry to let this dangle so long. Do you think you could rebase it from current master so we can do fresh testing?

**Comment by paulgmiller** [comment]
Pushed a merge of master No conflicts.... Let me know if there's anything else I can do.

**Comment by mboersma** [comment]
This has passed CI twice (the "upload artifact" error is something unrelated we need to find a solution for).

**Comment by jackfrancis** [comment]
@mboersma did you test upgrade?

**Comment by mboersma** [comment]
@jackfrancis I have tested upgrade with this branch locally, from 1.18 -> 1.19.0-beta.2 and 1.15 -> 1.16. Haven't seen any problems, but I suppose the kind of bug this could potentially introduce wouldn't be deterministic. (Having said that, I think @paulgmiller is correct and this is a safe change.)

**Comment by jackfrancis** [comment]
I ran tests yesterday as well and things looked good.

**Pull request merged**
