### PR TITLE
fix: remove shell output from VHD release notes

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

The output of the DevOps pipelines isn't always as serial as it should be, remove all shell commands that accidentally show up in the release notes artifacts.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

until I can verify desired outcome in vhd build

**Comment by CecileRobertMichon** [comment]
verified

/hold cancel

**Comment by jackfrancis** [comment]
I think we need to include a beginning of line regex, like `'^+`, right?

**Comment by CecileRobertMichon** [comment]
> I think we need to include a beginning of line regex, like '^+, right?

Good point, right now we don't have any other "+" characters anywhere else but we might add some later.

It's not at the beginning of the line exactly since the lines start with four spaces but '    ^+.*' works

**Comment by jackfrancis** [comment]
I think something like this is more resilient:

`'^[[:space:]]\{4\}\+'`

If we always know the first four chars are a space followed by a literal `x`

**Comment by CecileRobertMichon** [comment]
I miscounted there are actually 5 spaces, but I applied your suggestion with 5 instead of 4.

**Comment by CecileRobertMichon** [comment]
/hold

the last commit doesn't work

**Comment by CecileRobertMichon** [comment]
/hold  cancel

verified the pipeline output is what we want

**Pull request merged**
