### PR TITLE
feat: add support for Kubernetes 1.14.5

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#v1145

**Issue Fixed**:

**Requirements**:
- [x] Windows artifacts uploaded to acsmirror blob store
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by djsly** [comment]
how long for AKS to pick up this change and allow us to use 1.14.5 ? normally ?

**Comment by mboersma** [comment]
@djsly AKS Engine plans to make a patch release ASAP so these new Kubernetes patches can be available to AKS and others, but it's hard to say when AKS will integrate and release it. Typically a couple weeks.

**Comment by CecileRobertMichon** [comment]
@djsly and for anyone else out there watching, we are working on releasing this to AKS ASAP as per https://github.com/Azure/AKS/issues/1142 

The new versions will also be able in a new aks-engine patch release.

**Comment by mboersma** [comment]
The new Kubernetes versions 1.13.9, 1.14.5, and 1.15.2 are available in [AKS Engine v0.38.6](https://github.com/Azure/aks-engine/releases/tag/v0.38.6), AKS to follow as soon as we can validate all the changes.

**Comment by djsly** [comment]
Thanks all!  @titilambert we should keep an eye open.

**Pull request merged**
