### PR TITLE
chore: update the compute apiversion to 2018-10-01 to support new vmss features

### PR DESCRIPTION
**Pull request by tariq1890**
We need to use the more recent versions of API compute if we want to be up to date and use the new VMSS features like "VMSS overprovisioning + do not run extensions on overprovisioned instances".

### CODE REVIEW

**Comment by jackfrancis** [comment]
Just a slight correction: the new API version delivers "VMSS overprovisioning + do not run extensions on overprovisioned instances".

**Comment by jackfrancis** [comment]
Is there no change to `Gopkg.toml`?

**Comment by tariq1890** [comment]
No there won't be any change, as we already use a new Azure Go SDK library
which has this import version package.

**Comment by jackfrancis** [comment]
Why the change to `Gopkg.lock`?

**Comment by tariq1890** [comment]
The Gopkg locks are changed because we used a new import. The Gopkg lock is a reflection of the imports and the versions of the libraries used in the project.

**Comment by jackfrancis** [comment]
Got it. code lgtm. We'll want to run lots of back-compat tests to validate we can run upgrade against a cluster created with the prior api version spec on the same resources.

**Comment by tariq1890** [comment]
@jackfrancis Sure. Sounds good.

**Comment by tariq1890** [comment]
Upgrade an aks-engine cluster created using `master` worked from this branch :)

**Comment by serbrech** [comment]
I'd say lgtm as well

**Pull request merged**
