### PR TITLE
fix: move the definition of inboundNatRules inside the loadbalancer specification

### PR DESCRIPTION
**Pull request by tariq1890**
Using a separate definition of inboundNatRules makes it less testable as it is a SubResource. This PR deletes the SubResource definition and adds it to the LoadBalancer Resource definition instead.

### CODE REVIEW

**Comment by jackfrancis** [comment]
Is this change backwards-compatible w/ upgrade?

**Comment by tariq1890** [comment]
I don't think this change would pose risks in that surface area. We are
just changing the way of defining the same resources as before.

**Comment by tariq1890** [comment]
@jackfrancis I have tested upgrading a cluster (that was created from master) with this branch and it has worked fine.

**Comment by jackfrancis** [comment]
lgtm

**Comment by ritazh** [comment]
lgtm

**Pull request merged**
