### PR TITLE
fix: add Azure China support for Calico DaemonSet

### PR DESCRIPTION
**Pull request by andyzhangx**
**Reason for Change**:

With this PR, Calico DaemonSet will use `*.azk8s.cn` docker proxy, will generate following image urls in `chinaeast2`:
```
                "image": "dockerhub.azk8s.cn/calico/typha:v3.5.0"
                "image": "dockerhub.azk8s.cn/calico/cni:v3.5.0"
                "image": "dockerhub.azk8s.cn/calico/node:v3.5.0"
                "image": "gcr.azk8s.cn/google_containers/cluster-proportional-autoscaler-amd64:1.1.2-r2"
```

In global Azure, it will use keep the original image url:
```
                "image": "calico/typha:v3.5.0"
                "image": "calico/cni:v3.5.0"
                "image": "calico/node:v3.5.0"
```

**Issue Fixed**:

https://github.com/Azure/container-service-for-azure-china/issues/49

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

@CecileRobertMichon 

cc @AhmedMoAli

### CODE REVIEW

**Comment by andyzhangx** [comment]
BTW, this PR only covers version > 1.11, will make change for other versions later, just need a code reivew first, thanks.

**Comment by CecileRobertMichon** [comment]
@andyzhangx please use [conventional commit messages](https://www.conventionalcommits.org/) in the commit message and the PR title.

Unit tests failed https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=572&view=logs&jobId=739e1b7c-752b-5dd3-b8f8-24f95e240c64.

**Comment by andyzhangx** [comment]
hi @CecileRobertMichon I found this PR does not work, the `kubernetesmasteraddons-calico-daemonset.yaml` file is under `parts/k8s/addons`, while I found only yaml fils under `parts/k8s/containeraddons` are handling `ContainerImage` tag:
https://github.com/Azure/aks-engine/blob/aa434b2e88de408dc1bbeb1fbc5f7a46277c687e/pkg/engine/template_generator.go#L209

So question is what's the relationship between `parts/k8s/addons` and `parts/k8s/containeraddons`  dir, shall I move `kubernetesmasteraddons-calico-daemonset.yaml` to `parts/k8s/containeraddons`  dir?

**Comment by CecileRobertMichon** [comment]
@andyzhangx you can move the addon yaml to ` parts/k8s/containeraddons`. See  https://github.com/Azure/acs-engine/pull/4218 for details on how the addon refactor was originally implemented. I believe part of Tariq's reasoning for creating a new ` parts/k8s/containeraddons` dir was to distinguish between addons using the new pattern and the ones using the old one.

**Comment by andyzhangx** [comment]
/hold cancel
Below are the test result done on Azure China:
```
azureuser@k8s-master-15258257-0:/etc/kubernetes/addons$ sudo cat /etc/kubernetes/addons/calico-daemonset.yaml | grep azk8s
      - image: dockerhub.azk8s.cn/calico/typha:v3.5.0
        image: dockerhub.azk8s.cn/calico/cni:v3.5.0
        image: dockerhub.azk8s.cn/calico/node:v3.5.0
      - image: gcr.azk8s.cn/google_containers/cluster-proportional-autoscaler-amd64:1.1.2-r2
azureuser@k8s-master-15258257-0:/etc/kubernetes/addons$ kubectl get po -n kube-system | grep calico
calico-node-hclrv                                    1/1     Running   0          4m13s
calico-node-mbmc7                                    1/1     Running   0          4m13s
calico-typha-c4ff7765b-4v4zg                         1/1     Running   0          4m13s
calico-typha-horizontal-autoscaler-fc5f4f794-rrk7v   1/1     Running   0          4m8s
```

thanks for your help @CecileRobertMichon

**Comment by andyzhangx** [comment]
FYI. This issue is fixed in `v0.35.1`

**Pull request merged**
