### PR TITLE
docs: Update quickstart.md to add scoop install guide

### PR DESCRIPTION
**Pull request by elemount**
**Reason for Change**:

Scoop is a good tool for install packages. By this PR https://github.com/ScoopInstaller/Main/pull/1010 , scoop can install aks-engine. Scoop will help user to download the aks-engine from Github release and it is secure for users. 

**Issue Fixed**:

None

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [x] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
Hey, that's great--thanks for doing that @elemount!

So I assume we need to create a new PR at Scoop to match each new release of aks-engine? If so, we should add that to the [release docs](https://github.com/Azure/aks-engine/blob/master/docs/community/release-checklist.md) so we don't forget in the future.

**Comment by elemount** [comment]
> Hey, that's great--thanks for doing that @elemount!
> 
> So I assume we need to create a new PR at Scoop to match each new release of aks-engine? If so, we should add that to the [release docs](https://github.com/Azure/aks-engine/blob/master/docs/community/release-checklist.md) so we don't forget in the future.

Hi @mboersma , it does not needed. Scoop main bucket have a auto check-and-pr tooling and it will daily check the github release page and try to find if there is any version released. So if the bits name pattern is not changed, aks-engine does not need to notify the new version, scoop can automatically pull and update the version.

**Comment by mboersma** [comment]
> scoop can automatically pull and update the version

Excellent! Thanks again for doing this.

**Pull request merged**
