### PR TITLE
fix: create role assignment for master VMs

### LINKED ISSUE #2367: Permission issue using autoscaler plugin
**Describe the bug**
I use aks-engine to create a k8s cluster which I want to have the following properties:
- Belong to a dedicated resource group for easier resource management (`resource-group-1`)
- Be able to query other resources in an existing, custom VNET (`main-vnet`), which belongs to another resource group (`resource-group-main`)
- Has 2 VMSS backed node pools:
    - High priority node pool with auto scaling
    - Low priority node pool with auto scaling

The cluster is created using a service principal with the following role:
- `Owner` on the `resource-group-1` resource group
- `Contributor` on the `main-vnet` VNET

To avoid ip conflicts, I've properly created and assigned two separate subnets in `main-vnet`:
- one for the kubernetes master node: `master-subnet`
- one for the other nodes (both node pools): `agents-subnet`

The cluster-autoscaler fails to scale the low priority node pool because of a permission error:
```
E1126 17:02:06.863462       1 azure_scale_set.go:213] virtualMachineScaleSetsClient.CreateOrUpdate for scale set "k8s-burst-12135021-vmss" failed: 
compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=403 
Code="LinkedAuthorizationFailed" Message="The client '<k8s-master-service-principal>' with object id '<redacted>' has permission to perform action 
'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/<redacted>
/resourceGroups/<resource-group-1>/providers/Microsoft.Compute/virtualMachineScaleSets/<low-priority-vmss>'; however, it does not have permission to perform action 
'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions
/<redacted>/resourceGroups/<resource-group-main>/providers/Microsoft.Network/virtualNetworks/<main-vnet>/subnets/<agents-subnet>' or the linked scope(s) are invalid."
```

It seems the Service Principal associated to kubernetes master does not have the permission to add a new machine to the agent subnet.

**Steps To Reproduce**
The cluster is created using:
```
 aks-engine deploy -f --resource-group "dask-cluster" --debug\
  --location "westeurope" \
  --subscription-id "<redacted>" \
  --client-id "<redacted>" \
  --client-secret "<redacted>" \
  --api-model "./cluster-definition.json" \
  --set linuxProfile.ssh.publicKeys[0].keyData="<redacted>" \
  --set masterProfile.dnsPrefix="dask-cluster-`date +"%m-%d-%yT-%H-%M-%S"`", \
  --set servicePrincipalProfile.clientId="<redacted>" \
  --set servicePrincipalProfile.secret="<redacted>"
```
where `cluster-definition` is:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.14.7",
      "kubernetesConfig": {
        "useManagedIdentity": true,
         "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "pools": [
              {
                "name": "burst",
                "config": {
                  "min-nodes": "0",
                  "max-nodes": "5"
                }
              },
              {
                "name": "stable",
                "config": {
                  "min-nodes": "1",
                  "max-nodes": "2"
                }
              }
            ],
            "config": {
              "scan-interval": "1m"
            }
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "dask-cluster",
      "vmSize": "Standard_D4_v3",
      "firstConsecutiveStaticIP": "<redacted>",
      "vnetSubnetId": "/subscriptions/<redacted>/resourceGroups/<resource-group-main>/providers/Microsoft.Network/virtualNetworks/<main-vnet>/subnets/<master-subnet>"
    },
    "agentPoolProfiles": [
      {
        "name": "burst",
        "count": 3,
        "vmSize": "Standard_D4_v3",
        "availabilityProfile": "VirtualMachineScaleSets",
        "scaleSetPriority": "Low",
        "scaleSetEvictionPolicy": "Delete",
        "storageProfile": "ManagedDisks",
        "OSDiskSizeGB": 200,
        "vnetSubnetId": "/subscriptions/<redacted>/resourceGroups/<resource-group-main>/providers/Microsoft.Network/virtualNetworks/<main-vnet>/subnets/<agents-subnet>"
      },
      {
        "name": "stable",
        "count": 1,
        "vmSize": "Standard_D4_v3",
        "availabilityProfile": "VirtualMachineScaleSets",
        "scaleSetEvictionPolicy": "Delete",
        "storageProfile": "ManagedDisks",
        "OSDiskSizeGB": 200,
        "vnetSubnetId": "/subscriptions/<redacted>/resourceGroups/<resource-group-main>/providers/Microsoft.Network/virtualNetworks/<main-vnet>/subnets/<agents-subnet>"
      }
    ],
    "linuxProfile": {
      "adminUsername": "<redacted>",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    }
  }
}
```
**Expected behavior**
Since the service principal used to create the cluster has `Contributor` role on the Vnet I would expect that the `k8s-master` be able to auto-scale properly.

**AKS Engine version**
v0.44.0
**Kubernetes version**
1.14.7
**Additional context**
I'm not sure this is a bug, it might very well be an issue with the permissions set up on my side. I've done my best trying to figure out which role I need to affect to the service principal, but I've been having a really hard time to find proper details in the docs for each functionality (auto-scaler, custom Vnet, etc...).
Otherwise the cluster works perfectly. Thank you for aks-engine !

### LINKED ISSUE #2373: Cluster auto scaler broken in system MSI enabled cluster if worker subnet is in different resource group
In a cluster using system managed identities where the worker subnet is in a different resource group than the master VMs the cluster auto scaler doesn't work as the new worker VMs can't "join" the network properly.

The solution is to assign the role `Network Contributor` to all master identities on all vnets of worker subnets. This has to happen after the creation of the worker VMs but before the custom script extension for installing Kubernetes runs.

As the worker subnet (and in turn its vnet) is in a different RG the generated ARM template must create the role assignment in an embedded / nested / sub-template.

### PR DESCRIPTION
**Pull request by dennis-benzinger-hybris**
Fixes #2373 
Fixes #2367

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks! Could you please `git commit --amend` the commit message to something human-readable? That text appears in the AKS Engine release notes directly.

**Comment by jackfrancis** [comment]
@dennis-benzinger-hybris I added some quick unit test coverage to the additions in `types.go`. If you enable contributions from maintainers on this PR I can push that up.

Or, you could add those UT yourself, thanks!

**Comment by dennis-benzinger-hybris** [comment]
> @dennis-benzinger-hybris I added some quick unit test coverage to the additions in `types.go`. If you enable contributions from maintainers on this PR I can push that up.

Oh, sorry :-). Didn't want to exclude you. I've activated the checkbox now.

**Comment by dennis-benzinger-hybris** [comment]
@jackfrancis, I've added a test for `createKubernetesMasterRoleAssignmentForAgentPools` which should fix the code coverage. Please start the `/azp run pr-e2e` once more.

**Comment by dennis-benzinger-hybris** [comment]
The latest job seems to have failed because of
```
Status=429 Code=\"OperationNotAllowed\" Message=\"The server rejected the request because too many requests have been received for this subscription.\"
```
for some Kubernetes versions.
(from https://dev.azure.com/aks-engine/AKS-Engine/_build/results?buildId=3747&view=logs&j=a48fcffa-d400-5086-fd55-6a393fb8fdb7&t=9d93e863-c26a-5b58-475a-eafe7efc9f3e)

@jackfrancis, could you please investigate this or restart the job?

I don't have access to the Azure subscriptions used in the tests.

**Comment by jackfrancis** [comment]
@dennis-benzinger-hybris those results are not related to your change.

I've rebased this PR on top of current master to improve E2E test fidelity, and am running a broader set of cluster configuration tests against this branch, including back-compat for upgrade and scale. Hang tight, we're almost there! :)

And thank you again.

**Comment by dennis-benzinger-hybris** [comment]
@jackfrancis, have you started the pipeline after your push?

**Comment by dennis-benzinger-hybris** [comment]
@jackfrancis, thanks for merging 👍 . Do you have any idea when there will be a release with this fix?

**Comment by jackfrancis** [comment]
We will cut a v0.46.1 by tomorrow EOD -8 GMT at the latest.

**Pull request merged**
