### PR TITLE
test: check net.ipv4.tcp_retries2 kernel parameter

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

Restores a bonus test from #1093 that was unrelated to the problem with setting `net.netfilter.nf_conntrack_tcp_be_liberal`.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm pending validation using "ubuntu" distro

**Comment by CecileRobertMichon** [comment]
/lgtm

Feel free to `/hold cancel` once you're ready to merge after testing the Ubuntu distro

**Comment by jackfrancis** [comment]
validated

**Pull request merged**
