### PR TITLE
chore: rev the nvidia driver version for the newer driver

### PR DESCRIPTION
**Pull request by overplumbum**
**Reason for Change**:
Driver update is required to run cuda-10.1 workloads inside containers.

**Issue Fixed**:

**Requirements**:

**Notes**:

Driver info:

https://www.nvidia.com/Download/driverResults.aspx/144595/en-us
https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-418-4004/index.html

An example of previously failing workload:

```
$ kubectl run --generator=run-pod/v1 dvtest --rm -it  --restart=Never \
  --image=nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 -- true

pod default/dvtest terminated (ContainerCannotRun)
oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:337:
running prestart hook 0 caused \"error running hook: exit status 1, stdout:
stderr: exec command: [
/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real
--device=all --compute --utility --require=cuda>=10.1 brand=tesla,driver>=418,driver<419
--pid=25554 /var/lib/docker/overlay2/.../merged
]\\nnvidia-container-cli: requirement error: unsatisfied condition: driver >= 418\\n\""
```

### CODE REVIEW

**Comment by mboersma** [comment]
lgtm

**Comment by CecileRobertMichon** [comment]
holding until we get testing data for #897 

/hold

**Comment by jackfrancis** [comment]
Validated that this works. Let's wait for the full full nvidia + GPU implementation to land (which requires  a new VHD that is currently in-progress) and then we'll put this change on top of it.

Thanks @overplumbum!

**Pull request merged**
