### PR TITLE
chore: Updating Azure CNI and Azure NPM to v1.0.28

### PR DESCRIPTION
**Pull request by jaer-tsun**
**Reason for Change**:

Updates to the latest release of Azure CNI and NetworkPolicy:

https://github.com/Azure/azure-container-networking/releases/tag/v1.0.28

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
@jaer-tsun this PR requires some assets to be mirrored at https://acs-mirror.azureedge.net/cni. I'll take care of that.

**Comment by mboersma** [comment]
/azp run pr-e2e

The Azure CNI v1.0.28 archive files are now mirrored.

**Comment by jaer-tsun** [comment]
/assign @mboersma

thanks Matt

**Pull request merged**
