### PR TITLE
chore: Upgrade nvidia drivers to 450.80.02

### PR DESCRIPTION
**Pull request by gdippolito**
**Reason for Change**:

Upgrade the Nvidia drivers for GPU machine to 450.80.02. 

This version of the drivers is the same used in AzureML based images since April 2021. This change will add compatibility with newer version of CUDA (11.1,11.2,11.3). Reference https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html 

**Issue Fixed**:

None. It adds support to run docker images based on CUDA >= 11.1

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

Should be pretty safe since it is a minor version upgrade.

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @gdippolito, is there a newer version of basic CUDA validation we can run in E2E that you know of? We're still running the v0.1 image from 4+ years ago, see:

https://github.com/Azure/aks-engine/blob/master/test/e2e/kubernetes/workloads/cuda-vector-add.yaml

**Comment by gdippolito** [comment]
> Thanks @gdippolito, is there a newer version of basic CUDA validation we can run in E2E that you know of? We're still running the v0.1 image from 4+ years ago, see:
> 
> https://github.com/Azure/aks-engine/blob/master/test/e2e/kubernetes/workloads/cuda-vector-add.yaml

Thanks for your comment @jackfrancis. I have updated the e2e test with a more recent image which uses CUDA 11.1.

I have done few tests locally and this sample image does not seem to work with the version of the drivers I picked (it works on 460.x but not on 450.80.02). I'm a bit confused since according to the Nvidia documentation this is expected to work.

**Comment by jackfrancis** [comment]
@gdippolito thanks! I've tested your new image, and the E2E tests pass fine. So I think we're good here.

cc @Michael-Sinz @jadarsie  are there any concerns with the following:

- updating the driver version
- testing `nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.1-ubuntu18.04` instead of `k8s.gcr.io/cuda-vector-add:v0.1`

To be clear, these driver changes are specific to docker-backed clusters. If you're using containerd you can't use these drivers, and are probably using the gpu-operator already if you've figured out how to make this work with aks-engine-created clusters.

**Comment by Michael-Sinz** [comment]
Not that I know of.  Have not specifically tested that mix but we are also moving to containerd soon (I hope)

__
Michael Sinz C Architect C <http://midori/> v C Microsoft
________________________________

**Comment by jadarsie** [comment]
> @gdippolito thanks! I've tested your new image, and the E2E tests pass fine. So I think we're good here.
> 
> cc @Michael-Sinz @jadarsie are there any concerns with the following:
> 
>     * updating the driver version
> 
>     * testing `nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.1-ubuntu18.04` instead of `k8s.gcr.io/cuda-vector-add:v0.1`
> 
> 
> To be clear, these driver changes are specific to docker-backed clusters. If you're using containerd you can't use these drivers, and are probably using the gpu-operator already if you've figured out how to make this work with aks-engine-created clusters.

FYI @penggu

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by penggu** [comment]
Looks good to me.

**Comment by gdippolito** [comment]
Shall we :ship: it?

**Pull request merged**
