### PR TITLE
feat: setting a default containerd package for Windows

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

We should be setting a default containerd package for Windows nodes if we plan on making containerd be the default container runtime for aks-engine.

This package contains **signed** versions of upstream containerd/containerd release binaries to comply with Azure SysLock policies.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
@abelhu This package is currently not being pushed to china cloud mirrors. I believe AKS will only be using the packages based on cosine teams containerd branch and not use the upstream packages correct? If that is correct then is it ok to not mirror these packages?

**Review by jsturtevant — APPROVED** [review]

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by AbelHu** [comment]
> @AbelHu This package is currently not being pushed to china cloud mirrors. I believe AKS will only be using the packages based on cosine teams containerd branch and not use the upstream packages correct? If that is correct then is it ok to not mirror these packages?

My understanding is that AKS will still use upstream package. In preview, AKS can only use the package from cosine team. @keikhara Please correct me if my understanding is wrong.

**Pull request merged**
