### PR TITLE
fix: add rbac rules for nodes/status in cloud-node-manager.yaml

### PR DESCRIPTION
**Pull request by nilo19**
**Reason for Change**:

Add rbac rules for nodes/status in cloud-node-manager.yaml.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
> Add rbac rules for nodes/status in cloud-node-manager.yaml.

That describes what this PR does, but isn't a reason: why do we need to add this RBAC permission? It's not in the [example manifest](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/examples/out-of-tree/cloud-node-manager.yaml) at kubernetes-sigs/cloud-provider-azure, so I'm just curious why the change is needed.

**Comment by nilo19** [comment]
> example manifest

https://github.com/kubernetes-sigs/cloud-provider-azure/pull/372 the PR is adding it in the example manifest. We need this because it blocks several of our tests in [here](https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-serial).

**Comment by mboersma** [comment]
/azp run pr-e2e

@nilo19 I rebased this off current master because CI testing will fail without #3707.

**Pull request merged**
