### PR TITLE
fix: protect the slice for append operation in multi-thread scenario

### PR DESCRIPTION
**Pull request by andyliuliming**
for more details about the issue please take a look at this:
https://medium.com/@cep21/gos-append-is-not-always-thread-safe-a3034db7975

### CODE REVIEW

**Comment by andyliuliming** [comment]
@thomas1206

**Comment by andyliuliming** [comment]
Hi @mboersma , I think there's some issue on the circleci golang lint.
it ask us to do these changes for the style:
 "github.com/mattn/go-colorable" => colorable "github.com/mattn/go-colorable"

and all the api version model:
"github.com/Azure/aks-engine/pkg/api/v20160330" =>v20160330 "github.com/Azure/aks-engine/pkg/api/v20160330"

will leave it to you whether we need changes like that..

**Comment by mboersma** [comment]
Thanks @andyliuliming. We may have a fix for the goimports check in #204. I'll get that fixed and look at your PR today.

**Comment by tariq1890** [comment]
@andyliuliming Could you rebase this PR?

**Comment by andyliuliming** [comment]
> @andyliuliming Could you rebase this PR?

rebased, thanks :)

**Comment by andyliuliming** [comment]
@mboersma could you please help merge? Thanks.

**Comment by tariq1890** [comment]
@andyliuliming can you address my last comment? I can merge after that

**Comment by andyliuliming** [comment]
> @andyliuliming can you address my last comment? I can merge after that

done, thanks very much :)

**Pull request merged**
