### PR TITLE
chore: WS 2019 July 2021 patches for vhd

### PR DESCRIPTION
**Pull request by jsturtevant**
**Reason for Change**:

WS 2019 July 2021 patches: https://support.microsoft.com/en-us/topic/july-13-2021-kb5004244-os-build-17763-2061-d2b763cb-fad4-4b0a-a67f-4e184e277b99

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:
cc @marosset @jackfrancis

### CODE REVIEW

**Comment by marosset** [comment]
Should we wait and put the new signed-scripts package w/ Abels changes in the VHD?

**Comment by marosset** [comment]
https://github.com/Azure/aks-engine/pull/4567

**Comment by jsturtevant** [comment]
> Should we wait and put the new signed-scripts package w/ Abels changes in the VHD?

Yes, we should merge https://github.com/Azure/aks-engine/pull/4568 before building the vhd.  #4568 should include the updates to the vhd to install the scripts.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by marosset — APPROVED** [review]
/lgtm

**Pull request merged**
