### PR TITLE
Replace gometalinter with golangci-lint

### PR DESCRIPTION
**Pull request by tariq1890**
Golangci-lint is a faster linter than gometalinter.

Based on my performance tests, these were the average times that I got.

gometalinter: 26seconds
golangci-lint: 14 seconds

### CODE REVIEW

**Comment by tariq1890** [comment]
This PR depends on the docker-go-dev image to have golangci-lint installed

**Comment by mboersma** [comment]
This is great! `gometalinter` has timed out on me before.

In CircleCI I see this:
```
WARN [runner/megacheck.{unused,gosimple}] Can't run megacheck because of compilation errors in packages
```

Maybe a problem with how we set up `golangci-lint` in the go-dev image?

**Comment by tariq1890** [comment]
@mboersma The WARN message should now be suppressed.

**Pull request merged**
