### PR TITLE
chore: add go mod support

### PR DESCRIPTION
**Pull request by andyliuliming**
**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
The commit message needs to use conventional commit style to make sure that squash commit shows up in release notes.

/hold

**Comment by CecileRobertMichon** [comment]
@andyliuliming can you please update the PR description?

**Comment by mboersma** [comment]
[Your comment](https://github.com/Azure/aks-engine/pull/1078#issuecomment-484163759) in #1078 suggests this change won't work on its own when the time comes to vendor aks-engine into another codebase.

Could we just update `sirupsen/logrus` with `dep` and not introduce go modules?

**Comment by andyliuliming** [comment]
Hi @jackfrancis @mboersma , could you please help merge this PR if no other comments? so I can do the according change in ACSRP repo. thanks.

**Pull request closed without merging**
