### PR TITLE
chore: update azure sdk for BYOK support on OS disk

### PR DESCRIPTION
**Pull request by andyzhangx**
**Reason for Change**:

update azure sdk for BYOK support
azure disk encryption(SSE+CMK)  requires azure compute sdk version >= `2019-07-01`

PR(https://github.com/kubernetes/kubernetes/pull/84605) has added BYOK support on data disk in k8s v1.17, this is the first PR to add BYOK support on os disk in aks-engine repo.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:
sdk upgrade commands used in this PR:

```
sed -i 's/mgmt\/2018-10-01\/compute/mgmt\/2019-07-01\/compute/g' ./cmd/rotate_certs_test.go
sed -i 's/mgmt\/2018-10-01\/compute/mgmt\/2019-07-01\/compute/g' ./pkg/engine/*.go
sed -i 's/mgmt\/2018-10-01\/compute/mgmt\/2019-07-01\/compute/g' ./pkg/armhelpers/*.go
sed -i 's/mgmt\/2018-10-01\/compute/mgmt\/2019-07-01\/compute/g' ./pkg/operations/kubernetesupgrade/*.go
sed -i 's/mgmt\/2018-10-01\/compute/mgmt\/2019-07-01\/compute/g' ./pkg/engine/transform/transform.go
sed -i 's/mgmt\/2018-10-01\/compute/mgmt\/2019-07-01\/compute/g' ./pkg/armhelpers/azurestack/*.go
sed -i 's/mgmt\/2018-10-01\/compute/mgmt\/2019-07-01\/compute/g' ./pkg/armhelpers/utils/*.go
go mod vendor
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
unit test failed:
```
##[section]Starting: Check if generated code is up to date
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
make ensure-generated
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /__w/_temp/c8a79426-90ac-48f8-85e8-d46b40c4c1dc.sh
==> Checking generated files <==
+ GENERATED_FILES=("pkg/i18n/translations_generated.go" "pkg/engine/templates_generated.go")
++ mktemp -d
+ T=/tmp/tmp.i3syFuWVPs
+ trap 'rm -rf "${T}"' EXIT
+ for file in ${GENERATED_FILES[*]}
+ cp -a pkg/i18n/translations_generated.go /tmp/tmp.i3syFuWVPs/
+ for file in ${GENERATED_FILES[*]}
+ cp -a pkg/engine/templates_generated.go /tmp/tmp.i3syFuWVPs/
+ make generate
make[1]: Entering directory '/__w/1/s'
make -C hack/tools/
make[2]: Entering directory '/__w/1/s/hack/tools'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/__w/1/s/hack/tools'
go generate -mod=vendor -v ./... > /dev/null 2>&1
make[1]: Leaving directory '/__w/1/s'
+ for file in ${GENERATED_FILES[*]}
++ basename pkg/i18n/translations_generated.go
+ basefile=translations_generated.go
+ diff -r /tmp/tmp.i3syFuWVPs/translations_generated.go /__w/1/s/scripts/../pkg/i18n/translations_generated.go
1c1
< // Code generated by go-bindata. DO NOT EDIT. @generated
---
> // Code generated for package i18n by go-bindata DO NOT EDIT. (@generated)
64a65
> // Name return file name
67a69,70
> 
> // Size return file size
70a74,75
> 
> // Mode return file mode
73a79,80
> 
> // Mode return file modify time
76a84,85
> 
> // IsDir return file whether a directory
78c87
< 	return false
---
> 	return fi.mode&os.ModeDir != 0
79a89,90
> 
> // Sys return file is sys mode
go generate produced changes that were not already present.
Make sure you include generated assets in your commit.
+ echo 'go generate produced changes that were not already present.'
+ echo 'Make sure you include generated assets in your commit.'
+ exit 1
+ rm -rf /tmp/tmp.i3syFuWVPs
Makefile:165: recipe for target 'ensure-generated' failed
make: *** [ensure-generated] Error 1
##[error]Bash exited with code '2'.
##[section]Finishing: Check if generated code is up to date
```

while I already run `make ensure-generated`

**Comment by CecileRobertMichon** [comment]
@devigned is this ^ related to the weirdness you and @jackfrancis investigated a while back by any chance?

**Comment by CecileRobertMichon** [comment]
I get a diff when running `make generate` from the dev image that the tests are using (run `make dev` then `make generate`)... I wonder if this is a tool versioning issue.

**Comment by mboersma** [comment]
> I wonder if this is a tool versioning issue.

It seems to be. I think both @jackfrancis and I ran into this and worked around it with:

```console
$ rm `which go-bindata` && make generate

**Comment by devigned** [comment]
To ensure all dev tools are at the correct version, you can run:
```bash
cd ./hack/tools && make reload
```

https://github.com/Azure/aks-engine/blob/1cb07950f1a25a16053cb97bf7b18670440db862/hack/tools/Makefile#L22-L23

**Comment by andyzhangx** [comment]
```rm `which go-bindata` && make generate``` works for me, thanks folks!

**Pull request merged**
