### PR TITLE
chore: add apache2-utils as an apt dependency

### PR DESCRIPTION
**Pull request by jadarsie**
**Reason for Change**:
This package includes _htpasswd_

### CODE REVIEW

**Comment by jackfrancis** [comment]
Can you add a backlog issue to add this package to the `test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh` E2E package validation script? If we add it before it's baked into a VHD then the test will always fail for VHD-backed cluster scenarios (all but one of the test scenarios for PRs).

@yangl900 FYI, this new package dependency is an Azure Stack requirement

**Comment by jadarsie** [comment]
> Can you add a backlog issue to add this package to the `test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh` E2E package validation script? If we add it before it's baked into a VHD then the test will always fail for VHD-backed cluster scenarios (all but one of the test scenarios for PRs).
> 
> @yangl900 FYI, this new package dependency is an Azure Stack requirement

@jackfrancis I tried to help and pushed a few commits with my best guess. Is this going in the right direction?

**Comment by jadarsie** [comment]
> Can you add a backlog issue to add this package to the `test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh` E2E package validation script? If we add it before it's baked into a VHD then the test will always fail for VHD-backed cluster scenarios (all but one of the test scenarios for PRs).
> 
> @yangl900 FYI, this new package dependency is an Azure Stack requirement

Here #1824

**Comment by jackfrancis** [comment]
@palma21 @jluk FYI as this PR will pre-install this package into the VHD shared by AKS and AKS Engine Azure Stack.

**Comment by palma21** [comment]
Assume it will be cleaned up from VHD as well as sources for AKS?

**Comment by jadarsie** [comment]
> Assume it will be cleaned up from running node as well as sources list for AKS?

It can be removed, but at this point I do not think packages are removed anywhere in the code base (no new sources). What's your take @jackfrancis? I do not think that keeping these programs pose any harm.

**Comment by jackfrancis** [comment]
@palma21 No, they are not cleaned up. Arguably creates more complexity during provisioning as more stuff could go wrong.

The idea here is we add things to the base image so long as they don't have any material negative effect if you aren't using it (i.e., they are just data on disk)

**Comment by palma21** [comment]
@robbiezhang @wenwu449 for validation while @yangl900 is out

**Comment by jackfrancis** [comment]
We'll want to look out for any CSE 102 error results once a VHD is produced with this package, and we start testing cluster buildouts using that VHD. @CecileRobertMichon FYI

**Pull request merged**
