### PR TITLE
fix: Modified coredns.yaml to include import parameters

### PR DESCRIPTION
**Pull request by evillgenius75**
**Reason for Change**:

Currently coreDNS is set to auto-reconcile and any customization such as override parameters or stub zone proxy customization will not work in AKS-Engine as the Corefile is reset to default config map settings. Adding the import additional parameters can be added by using a coredns-custom config map with the following parameters:
i.e. Rewrite DNS
```
 apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.server: |
    <domain to be rewritten>.com:53 {
        errors
        cache 30
        rewrite name substring <domain to be rewritten>.com default.svc.cluster.local
        forward .  /etc/resolv.conf # you can redirect this to a specific DNS server such as 10.0.0.10
    }
```
i.e. CoreDNS Hosts plugin using overrride
```apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom # this is the name of the configmap you can overwrite with your changes
  namespace: kube-system
data:
    test.override: |
          hosts example.hosts example.org { # example.hosts must be a file
              10.0.0.1 example.org
              fallthrough
          }
```

**Issue Fixed**:

#2146 and #1541 

**Requirements**:

- [ x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [x] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thank you @evillgenius75 !

**Comment by CecileRobertMichon** [comment]
@jackfrancis @evillgenius75 squash commit message needs to amended to follow release note format.

**Comment by jackfrancis** [comment]
Re-running E2E because the one Windows fail signal was a DNS error.

**Pull request merged**
