### PR TITLE
chore: upgrade cni to v1.1.3

### PR DESCRIPTION
**Pull request by tamilmani1989**
**Reason for Change**:

This PR upgrades cni to v1.1.3. CNI has fixes for
1. disabling ra for interfaces created by CNI
2.  fix for TCP lb scenario where nodepool acts as router/proxy

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by tamilmani1989** [comment]
@sozercan @mboersma can you please upgrade binaries to AKS-E mirror.

Linux - https://github.com/Azure/azure-container-networking/releases/download/v1.1.3/azure-vnet-cni-linux-amd64-v1.1.3.tgz

Windows - https://acnreleaseartifacts.blob.core.windows.net/azure-cni/v1.1.3/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.1.3.zip

**Comment by tamilmani1989** [comment]
@paulgmiller

**Comment by jackfrancis** [comment]
Thanks @tamilmani1989!

**Comment by tamilmani1989** [comment]
@mboersma can you please merge this?

**Pull request merged**
