### PR TITLE
fix: aci-connector region is ignored

### LINKED ISSUE #2523: ACI-connector doesn't work well.
**Describe the bug**

The virtual kubelet doesn't work because the field `region` is not correct.

```
cat /etc/kubernetes/addons/aci-connector-deployment.yaml

...
- name: ACI_REGION
          value: <region>
...
```

If I modify the `<region>` to my region, it works well.

**Steps To Reproduce**

**Expected behavior**

Virtual kubelet works properly.

**AKS Engine version**

v0.45.0

**Kubernetes version**

1.17

**Additional context**

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

The region configuration is not being passed into the aci-connector addon spec.

**Issue Fixed**:

Fixes #2523 

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@feiskyer FYI

**Comment by feiskyer** [comment]
Thanks for the fix. Could we upgrade the virtual-kubelet image to latest version?

**Comment by mboersma** [comment]
>  Could we upgrade the virtual-kubelet image to latest version?

:+1: Let's do that in a separate PR to keep changes coherent and isolated.

**Comment by feiskyer** [comment]
Thanks a lot for fixing this. By the way, when could we expect it's being included in aks-engine release?

**Pull request merged**
