### PR TITLE
chore: disable 18.04 + N series VM node pool

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR adds fail fast validation to prevent errors installing nvidia drivers on 18.04-LTS N series node pools.

#3269 describes failures installing nvidia drivers on 18.04-LTS.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
would it make sense to default the distro to 16.04 if GPU is enabled? otherwise a user might get a validation error for using 18.04 when not explicitly specifying 18.04.

**Comment by CecileRobertMichon** [comment]
/hold

see comment above. feel free to hold cancel once resolved.

**Comment by jackfrancis** [comment]
I'm of two minds about that. On the one hand, it's more convenient, on the other hand, it has the likely outcome of going beyond a user's notice, and then only later being confused as to why the node pools are running a hetergeneous OS configuration.

Validating introduces annoyance that doesn't exist, with the benefit that the user is more likely to know exactly the type of cluster she is building.

@mboersma @rbitia @marosset thoughts?

**Comment by marosset** [comment]
I'm not a big fan of changing the default SKU based on if gpu is enabled or not (unless there was a way to may it clear the defaults where getting changed with a confirm dialog or something) since it could be confusing if folks where expecting 18.04 nodes.

**Comment by CecileRobertMichon** [comment]
We could print a warning... Agreed it's not ideal but I'm concerned about people having working apimodels in CI, etc. that suddenly stop working. If we don't change the default we have to call this out as a breaking change in release notes.

**Comment by marosset** [comment]
I'm trying to decide if I think it would be better to break users right away so they are aware of the issue and call this out as a breaking change like you suggested or allow users to continue along without seeing breaks in CI but potentially not be aware of their cluster configs...

Right now I'm leaning toward the former but am curious what other folks think.

**Comment by jackfrancis** [comment]
I actually intentionally broke upgrade scenarios (there's a UT) in this PR because we *don't* want to allow `aks-engine upgrade` to proceed against a working cluster w/ 18.04-backed GPU nodes. Essentially, the new 5.3 kernel broke our current nvidia implementation, so it's important that we don't allow folks to do that.

So actually, I realized this PR is actually functionally incomplete, as @CecileRobertMichon points out. If we want to permit a distro value of `""` during vlabs api model validation, we have to change the defaults. If we don't want to permit that, then we can essentially add the `""` (no user preference) to the not allowed list of distros here:

https://github.com/Azure/aks-engine/pull/3275/files#diff-f45af0b14c127459636440a5981a6934R585

Let's put the choice to a vote...

**Comment by jackfrancis** [comment]
Disallow a non-user-opinionated distro for N series SKUs, and require the user choose between the two available 16.04 options.

Add thumbs-up reaction to choose this one.

**Comment by jackfrancis** [comment]
Update the defaults flow to set distro defaults for N series SKUs distinctly as compared to other pools.

Add thumbs-up reaction to choose this one.

**Comment by jackfrancis** [comment]
@CecileRobertMichon @marosset @mboersma @ksubrmnn @devigned @ritazh could you please vote if you have a preference?

**Comment by jackfrancis** [comment]
Based on the votes, I've implemented a "permit no user opinion when specifying N series VM SKU, and default to 16.04" solution.

**Pull request merged**
