### PR TITLE
fix: enable systemd proposed implementation for non-VHD scenario

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

When using "ubuntu" distro the systemd/proposed install of the following version isn't working:

`229-4ubuntu21.17`

Deployments yield:

```
Error from deployment for kubernetes-southcentralus-76873 in resource group kubernetes-southcentralus-76873:exit status 1
2019/03/06 19:42:35 Command Output: ERROR: Deployment failed. Correlation ID: e80bf0f6-b582-4161-bf55-8ca50b22bb33. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=48\n[stdout]\n\n[stderr]\nConnection to k8s.gcr.io 443 port [tcp/https] succeeded!\nConnection to gcr.io 443 port [tcp/https] succeeded!\nConnection to docker.io 443 port [tcp/https] succeeded!\n\"."
      }
    ]
  }
```

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
this should be `fix: `

**Comment by CecileRobertMichon** [comment]
FYI the single commit message will be used as squash message, not the title so `fix` needs to be added in admin merge

**Comment by jackfrancis** [comment]
VHD job looks good:

`Setting up systemd (229-4ubuntu21.17) ...‌`

**Pull request merged**
