### PR TITLE
chore: validate MS moby 3.0.7 candidate build

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
This is a throwaway PR to help validate that a new, unreleased version of moby will work on AKS Engine.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by cpuguy83** [comment]
Nice looks good it seems?

**Comment by mboersma** [comment]
I think so. :+1:

**Comment by mboersma** [comment]
The next Azure moby release is not imminent, so I'm closing this validation PR.

**Comment by mboersma** [comment]
/hold

This PR isn't meant to be merged as-is; it's just for testing.

**Pull request closed without merging**
