### PR TITLE
chore: add new Azure VM SKUs, brazilsoutheast, westus3 regions

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR updates Azure consts, enabling more recent VM SKUs.

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@penggu, can you review these changes? Do these include the required VM SKUs you need?

**Comment by jadarsie** [comment]
/lgtm

giving @penggu some time to chime in

**Comment by penggu** [comment]
@jackfrancis Yes. It contains the T4 GPU VM SKUs that I wanted.

**Comment by penggu** [comment]
> @penggu, can you review these changes? Do these include the required VM SKUs you need?

Yes.

**Pull request merged**
