### PR TITLE
delete minor unreachable code caused by log.Fatal

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

**Reason for Change**:

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@Abirdcfly, thanks for this! Unfortunately we'll have to rebase this on top of current master branch before we can merge.

**Comment by Abirdcfly** [comment]
> @Abirdcfly, thanks for this! Unfortunately we'll have to rebase this on top of current master branch before we can merge.

Done.

**Review by jackfrancis — APPROVED** [review]
/lgtm

thanks @Abirdcfly!

**Pull request merged**
