### PR TITLE
fix: enableEncryptionWithExternalKms with master VMSS missing objectID

### LINKED ISSUE #1034: enableEncryptionWithExternalKms broken due to missing objectId in generated template
**Is this a request for help?**:
---
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of aks-engine?**:
---
0.34.0

**Kubernetes version**:
1.14.1

**What happened**:
Deployment failed

**What you expected to happen**:
Deployment succeeded

**How to reproduce it** (as minimally and precisely as possible):
I used the same api model as before; I suspect the key part is:
```
        "enableEncryptionWithExternalKms": true,
```

**Anything else we need to know**:
Here's the error message from aks-engine deploy:
```
INFO[0260] Finished ARM Deployment (<name and date>). Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"An invalid value was provided for 'accessPolicies'.\"\r\n  }\r\n}"}]
Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"An invalid value was provided for 'accessPolicies'.\"\r\n  }\r\n}"}]
```

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

Restore `CreateKeyVaultVMSS` to the behavior it had before the template refactor for `enableEncryptionWithExternalKms`. Compare with:
https://github.com/Azure/aks-engine/blob/release-v0.31.0/parts/k8s/kubernetesmasterresourcesvmss.t#L76

**Issue Fixed**:

Fixes #1034

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

for manual validation

**Comment by CecileRobertMichon** [comment]
@davidmatson FYI

**Comment by jackfrancis** [comment]
So this fixes the case when useManagedIdentity is false?

**Comment by CecileRobertMichon** [comment]
> So this fixes the case when useManagedIdentity is false?

Correct

**Comment by jackfrancis** [comment]
lgtm

**Comment by CecileRobertMichon** [comment]
/hold cancel

validated

**Pull request merged**
