### PR TITLE
fix: make Azure Disk & File CSI drivers work on 1.22

### PR DESCRIPTION
**Pull request by andyzhangx**
**Reason for Change**:

fix: make Azure Disk & File CSI drivers work on 1.22

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by andyzhangx** [comment]
unit test failure is strange, `make ensure-generated` pass on my dev machine:
```console
# make ensure-generated
==> Checking generated files <==
+ GENERATED_FILES=("pkg/i18n/translations_generated.go" "pkg/engine/templates_generated.go")
++ mktemp -d
+ T=/tmp/tmp.oCaevk8Bv5
+ trap 'rm -rf "${T}"' EXIT
+ for file in ${GENERATED_FILES[*]}
+ cp -a pkg/i18n/translations_generated.go /tmp/tmp.oCaevk8Bv5/
+ for file in ${GENERATED_FILES[*]}
+ cp -a pkg/engine/templates_generated.go /tmp/tmp.oCaevk8Bv5/
+ make generate
make[1]: Entering directory '/root/go/src/github.com/Azure/aks-engine'
make -C hack/tools/
make[2]: Entering directory '/root/go/src/github.com/Azure/aks-engine/hack/tools'
make[2]: Leaving directory '/root/go/src/github.com/Azure/aks-engine/hack/tools'
go-bindata 3.1.2 (Go runtime go1.13.4).
Copyright (c) 2010-2013, Jim Teeuwen.
go generate -mod=vendor -v ./... > /dev/null 2>&1
make[1]: Leaving directory '/root/go/src/github.com/Azure/aks-engine'
+ for file in ${GENERATED_FILES[*]}
++ basename pkg/i18n/translations_generated.go
+ basefile=translations_generated.go
+ diff -r /tmp/tmp.oCaevk8Bv5/translations_generated.go /root/go/src/github.com/Azure/aks-engine/scripts/../pkg/i18n/translations_generated.go
+ for file in ${GENERATED_FILES[*]}
++ basename pkg/engine/templates_generated.go
+ basefile=templates_generated.go
+ diff -r /tmp/tmp.oCaevk8Bv5/templates_generated.go /root/go/src/github.com/Azure/aks-engine/scripts/../pkg/engine/templates_generated.go
+ echo 'Generated assets have no material difference than what is committed.'
Generated assets have no material difference than what is committed.
+ rm -rf /tmp/tmp.oCaevk8Bv5
```

**Comment by andyzhangx** [comment]
@jackfrancis @chewong could you help review? Thanks.

**Review by chewong — COMMENTED** [review]
Looks like the CI didn't install azuredisk-csi-driver as part of their e2e run. Have you tried creating a 1.22 test cluster?

**Comment by andyzhangx** [comment]
> Looks like the CI didn't install azuredisk-csi-driver as part of their e2e run. Have you tried creating a 1.22 test cluster?

@chewong yes, I have tested on 1.22 cluster on both Linux and Windows node pools.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by chewong — APPROVED** [review]

**Comment by andyzhangx** [comment]
can someone merge this PR? thanks.

**Pull request merged**
