### PR TITLE
revert: "feat: Azure CNI dual stack support"

### PR DESCRIPTION
**Pull request by jackfrancis**
Reverts Azure/aks-engine#2862

### CODE REVIEW

**Comment by jackfrancis** [comment]
@tamilmani1989 Consistently observed error:

```
Events:
   Type     Reason                  Age                    From                                    Message
   ----     ------                  ----                   ----                                    -------
   Normal   Scheduled               24m                    default-scheduler                       Successfully assigned kube-system/coredns-autoscaler-64f7fc747-b6xxp to k8s-pool1-27703223-vmss000000
   Warning  FailedCreatePodSandBox  24m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "be16fc0c09954ee84163bdc85c7daa53f963be2061d82ebc0246976f1dfcfb25" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  24m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9d469184bc52a28224dcbb5b9518610631e835cc8686b5b08fb672dde0b8466e" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  23m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "111087fc05129b96b5e989588e4ab241a0042a84868e5d6204ea6ccf095c81bb" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  23m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "edeb89653d691aa6a5fb5c2fa7484cb3e12d9ff93b4f9bc4b983f432b5ce0de5" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  23m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "feca7be7cbfca779459aed0c78565d6df2ce89534475bf325f4db0ce8aade844" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  23m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9344d331c9a10c506cfa21fb24cfd03859b70230d06c124de9c6cfef82d225b8" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  23m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "50eb41661356d5cbbd8aa7b9bb677e6eaaa4854d03d4ba43d87caf2e5046ce73" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  23m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b03a0f19bd81c7e5ba6378d114f1f1a6be8f56b904186422efbd141c6de99fd0" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Warning  FailedCreatePodSandBox  23m                    kubelet, k8s-pool1-27703223-vmss000000  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "90feb9252c4b8c1ec11a1c22e1d2d6fdd279ae05412de37881679e50ae24605b" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
   Normal   SandboxChanged          23m (x12 over 24m)     kubelet, k8s-pool1-27703223-vmss000000  Pod sandbox changed, it will be killed and re-created.
   Warning  FailedCreatePodSandBox  4m36s (x315 over 23m)  kubelet, k8s-pool1-27703223-vmss000000  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4daf9553579cdfa1a64a94cc79302ef52d897a5a71be4de050985f01fbcc2f96" network for pod "coredns-autoscaler-64f7fc747-b6xxp": NetworkPlugin cni failed to set up pod "coredns-autoscaler-64f7fc747-b6xxp_kube-system" network: Failed to allocate v6 pool: Failed to delegate: Failed to allocate pool: Invalid address space
```

Those are events from the cluster-proportional-autoscaler component, recently added to coredns spec.

**Comment by tamilmani1989** [comment]
@jackfrancis  can you share me the cluster definition?

**Comment by jackfrancis** [comment]
@tamilmani1989 it's the `apiModel` config object here:

https://github.com/Azure/aks-engine/blob/master/test/e2e/test_cluster_configs/everything.json#L20

**Comment by tamilmani1989** [comment]
@jackfrancis Thanks. It looks like dualstack not even enabled in cluster config you shared. Not sure why cni ipam v6 binary gets invoked. Let me test locally with this cluster config.

**Comment by tamilmani1989** [comment]
@jackfrancis After deploying k8s cluster with cluster config..is there any specific test that trigger these errors? Can i get access to failed cluster..it would be more easier to debug

**Comment by tamilmani1989** [comment]
@jackfrancis I think i found the problem. i was checking for boolean instead of string. i will fix it and push this -> https://github.com/Azure/aks-engine/blob/905210b35ab7cb797ebf88488b499f47071a4969/parts/k8s/cloud-init/artifacts/cse_config.sh#L252

**Comment by tamilmani1989** [comment]
This PR https://github.com/Azure/aks-engine/pull/3110 will fix the issue

**Pull request closed without merging**
