### PR TITLE
fix: remove packer user

### LINKED ISSUE #899: Remove packer user at provisioning with AKS distro
packer user is created as part of VHD Packer build process. We delete `/home/packer` during deployments but we don't remove the packer user. We should remove it for consistency.

On a VM built with AKS distro:

`packer:x:1000:1000:Ubuntu:/home/packer:/bin/bash`

### PR DESCRIPTION
**Pull request by alexeldeib**
**Reason for Change**:

**Issue Fixed**:

Fixes #899 

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
lgtm pending successful VHD Pipeline job

**Comment by mboersma** [comment]
D'oh, I guess it's not that simple:

```
==> azure-arm: Cleanup requested, deleting resource group ...[0m
[1;32m==> azure-arm: 
[0;32m    azure-arm: /usr/sbin/deluser: `/usr/sbin/userdel packer' returned error code 8. Exiting.[0m
[0;32m    azure-arm: userdel: user packer is currently used by process 2153[0m
[0;32m    azure-arm: Warning: group `packer' has no more members.[0m
```

**Comment by alexeldeib** [comment]
If it seems too good to be true...

I'll try to find a good place to move this during the setup scripts.

**Comment by CecileRobertMichon** [comment]
@alexeldeib https://github.com/Azure/aks-engine/blob/master/parts/k8s/kubernetescustomscript.sh#L55 should work

**Comment by alexeldeib** [comment]
@CecileRobertMichon is there a different command to requeue vhd check? It seems to have disappeared

**Comment by CecileRobertMichon** [comment]
Nope, that's because the VHD pipeline is smart and only runs when it's needed :) You're not changing the VHD codepaths anymore so the VHD build isn't a required validation.

**Comment by alexeldeib** [comment]
D'oh 💯

**Comment by CecileRobertMichon** [comment]
second attempt e2e passed, pipeline failed on artifact publish step

/lgtm

**Pull request merged**
