### PR TITLE
[WIP] feat: use signed binaries for azure-vnet-cni

### LINKED ISSUE #2973: Signed Azure CNI binaries
You can find the artifacts here - 

linux: `https://kubernetesartifacts.azureedge.net/azure-cni/<version>/binaries/azure-vnet-cni-linux-amd64-<version>-signed.tar`
windows: `https://kubernetesartifacts.azureedge.net/azure-cni/<version>/binaries/azure-vnet-cni-windows-amd64-<version>-signed.zip`

The following versions have been uploaded:
* 2020.1.31.1
* 2020.2.21.1
* 2020.2.27.1

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
Switches to the azure-vnet-cni binaries published and signed by that team, then mirrored to the production CDN. This is one step in a effort to sign code and binaries deployed to AKS Engine clusters.

**Issue Fixed**:
Fixes #2973

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by mboersma** [comment]
Currently failing, as seen through `kubectl describe coredns-pod`:

  Warning  NetworkNotReady  1s (x13 over 24s)  kubelet, k8s-agentpool1-26399701-vmss000001  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

**Comment by jackfrancis** [comment]
@yangl900 @xuto2 FYI, what are the AKS implications of CNI binaries being hosted at this URI?

**Comment by mboersma** [comment]
The signed (and slightly newer?) binaries emit this error in /var/log/azure-vnet.log that I don't see on a healthy cluster with unsigned v1.0.33 binaries:

```log
2020/04/02 16:12:07 [117184] [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP: [127.0.0.1/8 ::1/128]
2020/04/02 16:12:07 [117184] [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:0d:3a:8f:f5:82 Flags:up|broadcast|multicast} with IP: [10.255.255.5/12 fe80::20d:3aff:fe8f:f582/64]
2020/04/02 16:12:07 [117184] [net] Network interface: {Index:3 MTU:1500 Name:docker0 HardwareAddr:02:42:ff:08:63:6f Flags:up|broadcast|multicast} with IP: [172.17.0.1/16 fe80::42:ffff:fe08:636f/64]
2020/04/02 16:12:07 [117184] [net] network store key not found
2020/04/02 16:12:07 [117184] [cni-net] Plugin started.
2020/04/02 16:12:07 [117184] [cni-net] Plugin stopped.
```

Seems to be coming from this line of code: https://github.com/Azure/azure-container-networking/blob/17e2c7d4044343dc9bc58ee506eb9e1fb5e88dbc/network/manager.go#L116

**Comment by jackfrancis** [comment]
> The signed (and slightly newer?) binaries emit this error in /var/log/azure-vnet.log that I don't see on a healthy cluster with unsigned v1.0.33 binaries:
> 
> ```
> 2020/04/02 16:12:07 [117184] [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP: [127.0.0.1/8 ::1/128]
> 2020/04/02 16:12:07 [117184] [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:0d:3a:8f:f5:82 Flags:up|broadcast|multicast} with IP: [10.255.255.5/12 fe80::20d:3aff:fe8f:f582/64]
> 2020/04/02 16:12:07 [117184] [net] Network interface: {Index:3 MTU:1500 Name:docker0 HardwareAddr:02:42:ff:08:63:6f Flags:up|broadcast|multicast} with IP: [172.17.0.1/16 fe80::42:ffff:fe08:636f/64]
> 2020/04/02 16:12:07 [117184] [net] network store key not found
> 2020/04/02 16:12:07 [117184] [cni-net] Plugin started.
> 2020/04/02 16:12:07 [117184] [cni-net] Plugin stopped.
> ```
> 
> Seems to be coming from this line of code: https://github.com/Azure/azure-container-networking/blob/17e2c7d4044343dc9bc58ee506eb9e1fb5e88dbc/network/manager.go#L116

Good catch @mboersma! @jchauncey, were these built from 1.0.33?

@tamilmani1989 FYI

**Comment by jchauncey** [comment]
We arent building these so I have no idea. Their release page doesnt give much detail either - https://msazure.visualstudio.com/AzureWiki/_wiki/wikis/AzureWiki.wiki/45476/Release-2020-2-27-1

**Comment by mboersma** [comment]
They report version as `v1.0.33` and those release notes make it appear as though they are built from that tag, so I'm probably mistaken in guessing they are newer.

**Comment by mboersma** [comment]
Apparently /etc/cni/net.d/10-azure.conflist differs significantly between the two builds. I think this is the issue.

**Comment by mboersma** [comment]
We are revising the Azure artifact pipeline so AKS Engine can use signed azure-cni binaries published directly on GitHub, which would hopefully obviate the need for replacing the `10-azure.conflist` files.

I'm optimistically closing this PR in favor of #3075 or its successor.

**Pull request closed without merging**
