### PR TITLE
feat(cilium) Add Cilium 1.4 support and improve deployment process

### PR DESCRIPTION
**Pull request by skinny**
This PR allows for the creation of a new systemd unit to auto-mount the bpffs (almost) required by the Cilium project (http://docs.cilium.io/en/latest/kubernetes/configuration/?highlight=bpffs#mounting-bpffs-with-systemd). After creating the unit the REBOOT_REQUIRED flag is set to ensure mounting occurs (had some trouble with only enable/restarting the mount).

The master-addon is replaced with a modified 1.4 version on the default cilium one. add-on manager annotations were added and a new toleration to allow the etcd cluster to deploy on non-ready nodes. This helps to bootstrap the cilium setup.

API model used for testing : 

```{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.13.2",
      "kubernetesConfig": {
        "serviceCidr": "10.1.0.0/16",
        "dnsServiceIP": "10.1.0.10",
        "clusterSubnet": "10.244.0.0/16",
        "etcdDiskSizeGB": "64",
        "networkPlugin": "cilium",
        "networkPolicy": "cilium",
        "apiServerConfig": {
          "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,AlwaysPullImages"
        },
        "addons": [{
          "name": "tiller",
          "enabled": true
        }, {
          "name": "ip-masq-agent",
          "enabled": false
        }]
      }
    },
    "masterProfile": {
      "count": 3,
      "vmSize": "Standard_A2_v2",
      "vnetSubnetId": ""
    },
    "agentPoolProfiles": [{
      "name": "default",
      "count": 3,
      "vmSize": "Standard_D2_v2"
    }],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [{
          "keyData": "ssh-rsa ..."
        }]
      }
    },
    "servicePrincipalProfile": {
      "clientId": ".....",
      "secret": "...."
    },
    "aadProfile": {
      "serverAppID": "....",
      "clientAppID": "....",
      "tenantID": "......"
    }
  }
}```

### CODE REVIEW

**Comment by jackfrancis** [comment]
FYI @skinny I rebased/force pushed this PR. Generally we allow the community to maintain the cilium surface area, and we'll maintain tests to ensure no functional regressions as we move the code forward.

Your api model example using the new `"networkPlugin": "cilium"` configuration tests out. We're running some `"networkPolicy": "cilium"` (just that by itself) tests to see if pre-existing cilium cluster configurations continue to work as before. Stand by.

**Comment by jackfrancis** [comment]
tests look good

/lgtm

**Comment by jackfrancis** [comment]
@skinny Does the `ip-masq-agent` addon not ever make sense in a cilium context? If so, we should just disable the addon by default so folks don't have to manually do so in the api model.

**Comment by skinny** [comment]
@jackfrancis Cilium will take care of masquerading so the `ip-masq-agent` is never needed. What's the best spot to disable it by default ?

**Comment by jackfrancis** [comment]
https://github.com/Azure/aks-engine/pull/551


By the way, our regular cilium networkPlugin tests are failing upgrade pretty consistently:

```
time="2019-02-20T21:56:38Z" level=info msg="Draining node k8s-agent1-15546206-vmss000000"
FATA[1606] Error upgrading cluster: Get https://kubernetes-centralus-35995.centralus.cloudapp.azure.com/api/v1/nodes/k8s-agent1-15546206-vmss000000: read tcp 172.17.0.5:47240->52.165.182.128:443: read: connection timed out 
time="2019-02-20T22:12:56Z" level=error msg="Error draining VM in VMSS: Get https://kubernetes-centralus-35995.centralus.cloudapp.azure.com/api/v1/nodes/k8s-agent1-15546206-vmss000000: read tcp 172.17.0.5:47240->52.165.182.128:443: read: connection timed out"
```

Are you using `aks-engine upgrade` on clusters built this way? Are you seeing similar cordon/drain timeout symptoms.

**Pull request merged**
