### PR TITLE
feat: support using existing identity for addons (#2238)

### PR DESCRIPTION
**Pull request by xuto2**
**Reason for Change**:

cherry-pick for https://github.com/Azure/aks-engine/pull/2238/files to aks-release branch

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by xuto2** [comment]
@jackfrancis @CecileRobertMichon  can one of you help approve this PR? This is cherry-picking https://github.com/Azure/aks-engine/pull/2358 to aks-release branch for AKS' usage. FYI @norshtein

**Comment by jackfrancis** [comment]
@xuto2 Wouldn't we merge this to master first?

**Comment by xuto2** [comment]
> @xuto2 Wouldn't we merge this to master first?

@jackfrancis  this is already merged to AKS-Engine master.

**Pull request merged**
