### PR TITLE
chore: Updating omsagent to have the changes for latest release - ciprod08222019

### PR DESCRIPTION
**Pull request by rashmichandrashekar**
Changes to the yaml to for the new release
Increase resource requests
update image tag to ciprod08222019

### CODE REVIEW

**Comment by jackfrancis** [comment]
Is this PR still active?

**Comment by rashmichandrashekar** [comment]
> Is this PR still active?

Not currently working on this. Will get back to it in the next week, since we need to include a new release. Is it possible to put this on hold?

**Comment by jackfrancis** [comment]
It might be easier to create a new PR rather than rebase. Up to you.

**Pull request closed without merging**
