### PR TITLE
[WIP] chore: upgrade cni-plugins to v0.8.3

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

See:

https://github.com/containernetworking/plugins/releases/tag/v0.8.3

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@tamilmani1989 Do we know if Azure CNI is compatible w/ cni-plugins v0.8?

https://github.com/containernetworking/plugins/releases/tag/v0.8.0

**Comment by mboersma** [comment]
The packaging and archive names have changed for the cni-plugins v0.8.x series. The two files that I mirrored are:
https://acs-mirror.azureedge.net/cni/cni-plugins-linux-amd64-v0.8.3.tgz
https://acs-mirror.azureedge.net/cni/cni-plugins-windows-amd64-v0.8.3.tgz

So this PR will need additional changes to accomodate that. (Or we could hack around it perhaps by renaming the windows archive to match the old pattern.)

**Comment by jackfrancis** [comment]
@mboersma Good catch. Just pushed up a change that should unblock functional testing against v0.8.3. We can figure out how to merge this if we decide we want v0.8.3.

**Comment by jackfrancis** [comment]
(and updated VHD spec as well)

**Pull request closed without merging**
