### PR TITLE
fix: removed unnecessary elb artifacts when PrivateCluster is enabled

### PR DESCRIPTION
**Pull request by mkosieradzki**
**Reason for Change**:

Removes remaining elb artifacts in private cluster. Related to: #487 .

**Issue Fixed**:

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Hi @mkosieradzki, is this to enable a "private cluster" + "standard load balancer" cluster configuration scenario?

**Comment by mkosieradzki** [comment]
@jackfrancis the scenario you have mentioned has been enabled in #487 and it already works for me. I have just noticed that there are some unncessary leftovers in this scenario and added some cleanup.

**Pull request merged**
