### PR TITLE
chore: update Azure CNI to v1.4.25

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR updates the version of Azure CNI built into new clusters to v1.4.25.

Reference:

- https://github.com/Azure/azure-container-networking/releases/tag/v1.4.25

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by Michael-Sinz — APPROVED** [review]
Thank you - this at least gets us up to date in aks-engine.
Too bad this is a vhd spin...

**Comment by jackfrancis** [comment]
@AbelHu do you recall how the replication to `https://kubernetesartifacts.azureedge.net` happens for Azure CNI? Seems like this recent release hasn't been replicated.

**Comment by AbelHu** [comment]
@jackfrancis I think that azure cni team will upload them to the storage account. cc @tamilmani1989

**Comment by bridgetkromhout** [comment]
Closing as no longer relevant.

**Pull request closed without merging**
