### PR TITLE
chore: add administration tools

### PR DESCRIPTION
**Pull request by sylr**
- htop
- iotop
- iftop
- sysstat

### CODE REVIEW

**Comment by jackfrancis** [comment]
@sylr FYI I rebased/force-pushed this PR to reconcile it with some changes we're managing to go generated commit requirements in master (sorry for the moving furniture).

**Comment by jackfrancis** [comment]
@weinong @jakepearson @cchildress @juan-lee Anyone have any opinions about introducing the OS tools noted in the PR description to AKS node vms?

**Comment by cchildress** [comment]
These are definitely very helpful debugging tools. I use htop all the time. I find atop and iftop to be quite helpful as well.

If the goal here is to make our nodes easier to debug out of the box I'd say this is a solid step in that direction.

**Comment by sylr** [comment]
@cchildress +1 for iftop, I'll add it

**Pull request merged**
