### PR TITLE
chore: upgrade Azure CNI to 1.4.9

### PR DESCRIPTION
**Pull request by thatmattlong**
**Reason for Change**:

Upgrade default Azure CNI to latest release and remove old CNI version from VHD.

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [x] tested upgrade from previous version

### CODE REVIEW

**Comment by thatmattlong** [comment]
Can someone please upload the artifacts to the acs mirror, maybe @sozercan or @jackfrancis, and kick off E2E?
Windows: https://acnreleaseartifacts.azureedge.net/azure-cni/v1.4.9/binaries/azure-vnet-cni-singletenancy-windows-amd64-v1.4.9.zip
Linux: https://github.com/Azure/azure-container-networking/releases/download/v1.4.9/azure-vnet-cni-linux-amd64-v1.4.9.tgz

**Comment by sozercan** [comment]
@matmerr should be able to do this directly now

**Comment by thatmattlong** [comment]
@sozercan Mat was able to get the artifacts into the mirror and now VHD build is passing, but it looks like I don't have sufficient permissions to kick off e2e. Can you kick off the E2Es?

**Comment by thatmattlong** [comment]
@sozercan can you kick e2e again? I fixed a failing UT so it is ready to test again

**Comment by thatmattlong** [comment]
@sozercan it looks like pr-e2e k8s_1_22_docker_e2e failed due to flake, can you re-run that one? I don't see the "Re-run failed jobs" button in ADO so I can't do it myself :( Also, I noticed @AbelHu opened #4619 for Windows CNI - do you guys prefer that we do 2 PRs, one for linux and one for windows, or is this fine as is?

**Comment by jsturtevant** [comment]
> Also, I noticed @AbelHu opened #4619 for Windows CNI - do you guys prefer that we do 2 PRs, one for linux and one for windows, or is this fine as is?

this one lgtm I kicked off the test flake
/lgtm

**Comment by thatmattlong** [comment]
Thanks @jsturtevant , can I get approvals from you and one other (maybe @sozercan if you're around today) to complete this?

**Comment by sozercan** [comment]
I am going to defer to @jsturtevant and/or @jackfrancis for approvals/merge

**Review by AbelHu — APPROVED** [review]

**Review by jsturtevant — APPROVED** [review]

**Pull request merged**
