### PR TITLE
chore: Update calico to v3.7.2

### PR DESCRIPTION
**Pull request by song-jiang**
**Reason for Change**:

Update calico to v3.7.2

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@song-jiang FYI the `TestAssignDefaultAddonImages` unit test expects the previous calico version, so that will need to be updated.

**Comment by song-jiang** [comment]
@jackfrancis Thanks! Code updated.

**Comment by song-jiang** [comment]
@CecileRobertMichon pr-e2e failed with following error message, not sure what should I do next. Could you help please?

**Comment by CecileRobertMichon** [comment]
@song-jiang that's a known intermittent issue (https://github.com/Azure/aks-engine/issues/1306), I've restarted that test.

**Comment by song-jiang** [comment]
Great. Thanks @CecileRobertMichon @mboersma @jackfrancis

**Pull request merged**
