### PR TITLE
chore: enable VHD re-use in no outbound scenarios

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR allows VHD-like CSE flows, regardless of the "distro" value. So long as `/opt/azure/vhd-install.complete` exists on the underlying filesystem when CSE runs, it will assume that all required artifact dependencies are present, and skip those installation steps (e.g., apt-get install).

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
/azp run

(testing fixing the pipelines)

**Pull request merged**
