### PR TITLE
fix: update GPU driver to 450.51.06 (#3814)

### LINKED ISSUE #3814: Update to newer GPU driver version
The current NVIDIA driver version is 418 with Ubuntu 18.04 and the latest version from NVIDIA is 450. 418 doesn't support a lot of current frameworks, like pytorch. Also needed to support CUDA.

### PR DESCRIPTION
**Pull request by Nishikoh**
**Reason for Change**:

> The current NVIDIA driver version is 418 with Ubuntu 18.04 and the latest version from NVIDIA is 450. 418 doesn't support a lot of current frameworks, like pytorch. Also needed to support CUDA.

**Issue Fixed**:

fix #3814

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
Manually tested this using a `"distro": "ubuntu-18.04"` config on an N series pool, checked out O.K.

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
Thank you @Nishikoh!

**Comment by jackfrancis** [comment]
cc @xuto2 this drivers version update is testing out O.K. for AKS Engine

**Pull request merged**
