### PR TITLE
[DO NOT MERGE] feat: update azuredisk-csi-driver

### PR DESCRIPTION
**Pull request by haofan-ms**
**Reason for Change**:

Update azuredisk-csi-driver to support external cloud provider on Azure Stack

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [ ] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by songjiaxun** [comment]
Looks good to me. We have tested this new YAML file and it works.

**Comment by jadarsie** [comment]
Could you please add `"useCloudControllerManager": true` to API models used by the PR gates?
- examples/e2e-tests/kubernetes/release/default/definition.json
- examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json

```json
"kubernetesConfig": {
  "useCloudControllerManager": true
}
```

@jackfrancis to confirm these are the correct API models

**Comment by jadarsie** [comment]
BTW, that change should force the deployment of the disk/file CSI drivers (AFAIK)

**Comment by haofan-ms** [comment]
> BTW, that change should force the deployment of the disk/file CSI drivers (AFAIK)

Yes, set "useCloudControllerManager" to "true" will force disk/file CSI driver

**Pull request closed without merging**
