### PR TITLE
fix: Change win-cni to win-bridge binaries and config

### PR DESCRIPTION
**Pull request by vyta**
**Reason for Change**:

This replaces the deprecated plugin with win-bridge

**Issue Fixed**:

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by vyta** [comment]
@PatrickLang

**Comment by CecileRobertMichon** [comment]
(testing the new pipeline, please disregard)

/azp run pr-e2e

**Comment by jackfrancis** [comment]
lgtm

**Comment by PatrickLang** [comment]
Sorry about this - I missed it initially while I was out of town. Reviving it now

**Comment by PatrickLang** [comment]
fun fact - on Windows - 0x643 = ERROR_INSTALL_FAILURE.

**Comment by PatrickLang** [comment]
manual tests looking ok - can start pods, route to services

**Pull request merged**
