### PR TITLE
ci: updating pub to v0.2.6 to address publishing issues

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

Updates to a version of pub that supports categoryMap fields.
https://github.com/devigned/pub/pull/24

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jsturtevant** [comment]
looks like there were some updates to pub which is on 2.6 now? Should this be updated to https://github.com/devigned/pub/releases/tag/v0.2.6?

**Comment by marosset** [comment]
/hold 
Will update to pub v0.2.6

**Pull request merged**
