### PR TITLE
chore: update zip name for mooncake mirror

### PR DESCRIPTION
**Pull request by tamilmani1989**
**Reason for Change**:

This PR fixes zip name for windows package in mooncake mirror

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by tamilmani1989** [comment]
can @sozercan / @jchauncey confirm if this change is good?

**Comment by sozercan** [comment]
@tamilmani1989  I believe we'll need to change the url to `kubernetesartifacts.blob.core.chinacloudapi.cn` (similar to `CSIProxyDownloadURL`) as `mirror.azk8s.cn` doesn't have this artifact.

**Comment by tamilmani1989** [comment]
> @tamilmani1989 I believe we'll need to change the url to `kubernetesartifacts.blob.core.chinacloudapi.cn` (similar to `CSIProxyDownloadURL`) as `mirror.azk8s.cn` doesn't have this artifact.

Ok i see all URLS need to be updated then. I'm not sure about other urls like ContainerdDownloadURLBase, CNIPluginsDownloadURL. do you want me to update for that also?

**Comment by tamilmani1989** [comment]
also why are we not doing for other national clouds but only for mooncake?

**Comment by sozercan** [comment]
I don't think we are hosting those in `kubernetesartifacts.blob.core.chinacloudapi.cn`, just need the change for `VnetCNIWindowsPluginsDownloadURL` and `VnetCNILinuxPluginsDownloadURL`

**Comment by tamilmani1989** [comment]
@sozercan I made the change. Please take a look . 
@mboersma  I dont think e2e is required. I changed for mooncake url and anyway e2e is not going to cover that.

**Comment by mboersma** [comment]
>  I dont think e2e is required

No, but "azp run pr-e2e" is also the way to run the lint checks and unit tests as well.

**Pull request merged**
