### PR TITLE
feat: add support for Kubernetes 1.22.0-beta.1

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1220-beta0

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] Kubernetes artifacts built and pushed by Azure Pipelines
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by Michael-Sinz — APPROVED** [review]

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
@sozercan @jchauncey @chewong can you kindly ping when this is available?

```
==> azure-arm: + for KUBERNETES_VERSION in ${K8S_VERSIONS}
==> azure-arm: + for component in kube-apiserver kube-controller-manager kube-proxy kube-scheduler
==> azure-arm: + CONTAINER_IMAGE=mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.22.0-beta.1
==> azure-arm: + loadContainerImage mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.22.0-beta.1
==> azure-arm: + docker pull mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.22.0-beta.1
==> azure-arm: Error response from daemon: manifest for mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.22.0-beta.1 not found: manifest unknown: manifest tagged by "v1.22.0-beta.1" is not found
==> azure-arm: + exit 35
```

**Comment by sozercan** [comment]
@jackfrancis I just approved it, should be up in a few minutes

**Comment by mboersma** [comment]
Sorry, I jumped the gun a bit when opening the PR--publishing wasn't done yet. Should be happy now.

**Comment by mboersma** [comment]
```
==> azure-arm: + docker pull mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v0.5.1
    azure-arm: v0.5.1: Pulling from oss/kubernetes/azure-cloud-node-manager
    azure-arm: 39fafc05754f: Already exists
    azure-arm: 98cb8163d7da: Pulling fs layer
    azure-arm: eeb08ba6e455: Pulling fs layer
==> azure-arm: error pulling image configuration: Get https://westus2.data.mcr.microsoft.com/01031d61e1024861afee5d512651eb9f-h36fskt2ei//docker/registry/v2/blobs/sha256/a8/a862b043bcec5329978260ae70ccc5432a0d9ed8e83f594434c1aee6227f7759/data?P1=1625775725&P2=1&P3=1&P4=Xv17dAZnLC9j0B4puScbLbW6xANQPgr7Tc7U1NaoYcw%3D&se=2021-07-08T20%3A22%3A05Z&sig=cUVdU19o4bGvwinZHiu0YoCsNtpWm7c6uqXe9V4y4q8%3D&sp=r&spr=https&sr=b&sv=2016-05-31&regid=01031d61e1024861afee5d512651eb9f: read tcp 10.0.0.4:58626->204.79.197.219:443: read: connection reset by peer
```

Flaky! I will re-run.

**Pull request merged**
