### PR TITLE
fix: Adding csi-proxy logs locked file list to prevent access denied errors

### PR DESCRIPTION
**Pull request by marosset**
**Reason for Change**:

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
This is to address this issue
https://github.com/kubernetes/kubernetes/pull/93948#issuecomment-726409727

**Review by chewong — COMMENTED** [review]
/lgtm

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
