### PR TITLE
feat: Add ACL rules for Windows

### PR DESCRIPTION
**Pull request by AbelHu**
**Reason for Change**:

feat: Add ACL rules for Windows

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jsturtevant** [comment]
Could you give a some explanation on what these acl rules do and why they are needed? Maybe some documentation would be relevant?

**Comment by jsturtevant** [comment]
/approve cancel 

Wrong pr sorry. Still looking

**Comment by jsturtevant** [comment]
There is a blocking issue for containerd in azurecni preventing pods from coming up.  There is a fix in progress

```
 Warning  FailedCreatePodSandBox  28m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6f46dfcd7aa787bf251a5a142b3fdf647244c0cd4e7c798032e61e17dd28108f": Failed to create endpoint: Failed to set Policy: Type: EndpointPolicy, Data: {"Action":"Block","Direction":"Out","Priority":200,"Protocols":"6","RemoteAddresses":"168.63.129.16/32","RemotePorts":"80","RuleType":"Switch","Type":"ACL"}
```

**Review by marosset — APPROVED** [review]
/lgtm

**Pull request merged**
