### PR TITLE
Added references to capz

### PR DESCRIPTION
**Pull request by craiglpeters**
Indicating that aks-engine is a legacy ARM-based project, and pointing users to CAPZ

**Reason for Change**:
Making it clear to users that aks-engine is a stable project, and that new use cases are enabled through Cluster API on Azure with CAPZ

**Issue Fixed**:

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [X] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
lgtm

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
cc @devigned @CecileRobertMichon @mboersma @marosset @jsturtevant

**Comment by craiglpeters** [comment]
I'd like to point this change out to @jadarsie and @Michael-Sinz as well

**Pull request merged**
