### PR TITLE
docs: refine message about aks-engine project status

### PR DESCRIPTION
**Pull request by craiglpeters**
Clarifying that the project is maintained, and use for Azure Stack Hub

**Reason for Change**:
Some refinement about project status is needed to avoid confusion

**Issue Fixed**:

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [X] No
- [ ] Yes

If "Yes," did you notify that project's maintainers and provide attribution?

- [ ] No
- [ ] Yes

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by devigned — APPROVED** [review]
Clear and concise.
lgtm

**Comment by jadarsie** [comment]
lgtm

**Comment by walterov** [comment]
Thanks @craiglpeters. This will work better for ASH customers.

**Review by walterov — APPROVED** [review]

**Pull request merged**
