### PR TITLE
fix: Fixed bug in condition check for dualstack

### PR DESCRIPTION
**Pull request by tamilmani1989**
**Reason for Change**:

This PR fixes  @bug introduced by this PR #2862. It checks for string in condition check instead of boolean
**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by tamilmani1989** [comment]
/assign @jackfrancis  

can you run azp e2e?

**Comment by tamilmani1989** [comment]
@jackfrancis  can you please trigger again? Sorry i was unaware that i should run make generate if i change script.

**Comment by jackfrancis** [comment]
Thanks @tamilmani1989!

**Pull request merged**
