### PR TITLE
fix: user contributor role for Master VMAS role assignments

### PR DESCRIPTION
**Pull request by tariq1890**
This fixes a discrepancy between the old template and refactor versions for VMAS masters.

### CODE REVIEW

**Comment by mboersma** [comment]
lgtm

**Comment by mboersma** [comment]
E2E may fail until we merge and rebase off #885.

**Comment by tariq1890** [comment]
@jackfrancis yes

**Comment by mboersma** [comment]
The dns-liveness restart is a bit concerning and may have to do with the new coredns update in 1.14.0. I'll file a separate issue for that and merge this by consensus with the maintainer team.

**Pull request merged**
