### PR TITLE
test: don't hardcode base 64 encoded script values in template tests

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Reason for Change**:

Remove hardcoded scripts in unit tests. These cause dev friction as the base64 encoded string needs to be updated each time one of these scripts is changed. The goal of that specific unit test is not to test the content of the scripts themselves but instead to test template generation.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by tariq1890** [comment]
The key idea is to have those as raw values in the text. Should those methods change, the test cases will have to be updated  as well. This forces the developer to think/look more closely at the changes involved. 

I would vote for keeping the tests as-is.

**Comment by serbrech** [comment]
That's inline with what I was expressing in the stand-up this morning.
lgtm

**Comment by jackfrancis** [comment]
>  Should those methods change, the test cases will have to be updated as well.

We should unit test the methods themselves for those behaviors, not the ARM resource object composition implementations.

**Comment by jackfrancis** [comment]
lgtm pending unit tests

**Pull request merged**
