### PR TITLE
fix: fix restart command in setup-custom-search-domains.sh

### PR DESCRIPTION
**Pull request by mohatb**
++ This script calls a function systemctl_restart and trying to restart the networking service, however, looking at the inputs provided to the function #systemctl_restart 20 5 10 restart networking I see the 4th input should be the service name while in our case it is "restart" which I believe where it is failing.
 
```
systemctl_restart() {
    retries=$1; wait_sleep=$2; timeout=$3 svcname=$4
    for i in $(seq 1 $retries); do
        timeout $timeout systemctl daemon-reload
        timeout $timeout systemctl restart $svcname && break || \
        if [ $i -eq $retries ]; then
            return 1
        else
            sleep $wait_sleep
        fi
    done
}
```
 
```
#!/bin/bash
set -x
source /opt/azure/containers/provision_source.sh
echo "  dns-search <searchDomainName>" | tee -a /etc/network/interfaces.d/50-cloud-init.cfg
#systemctl_restart 20 5 10 restart networking
systemctl_restart 20 5 10 networking
wait_for_apt_locks
retrycmd_if_failure 10 5 120 apt-get -y install realmd sssd sssd-tools samba-common samba samba-common python2.7 samba-libs packagekit
wait_for_apt_locks
echo "<searchDomainRealmPassword>" | realm join -U <searchDomainRealmUser>@$(echo "<searchDomainName>" | tr /a-z/ /A-Z/) $(echo "<searchDomainName>" | tr /a-z/ /A-Z/)
```

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@mohatb can you please update the commit message to `fix: fix restart command in setup-custom-search-domains.sh`? Otherwise the commit won't be picked up by our release changelog script.

git commit --amend
git push -f

**Comment by mboersma** [comment]
@mohatb in addition to fixing the commit message as Cécile described, could you run `make generate` and commit the generated file? It's failing in CI where it checks to see that is up to date.

**Comment by mboersma** [comment]
Never mind–I took the liberty of updating this PR to conform. I hope that's ok @mohatb. Thanks again!

**Comment by CecileRobertMichon** [comment]
It's still not mergeable without a signed CLA @mboersma @mohatb

**Comment by mohatb** [comment]
@CecileRobertMichon @mboersma  I signed CLA and I've also updated the pull to source kubelet.sh as well in the script.

**Comment by mboersma** [comment]
@mohatb why do we need to `source /opt/azure/containers/kubelet.sh`–was there an undefined function or variable?

If that's requires, then it looks like you need to run `make generate` and commit the results still. `templates_generated.go` doesn't have the `source` change.

**Comment by mohatb** [comment]
Yes, Kubelete.sh updates the script by updating <searchDomainName> <searchDomainRealmPassword> <searchDomainRealmUser> which should be sourced in the script. Am not really sure what templates_generated.go does. Please let me know if anything I need to do from my side.

**Comment by mohatb** [comment]
@mboersma so I just tested with kubelet.sh and that failed to update the script with the variables because it is happening during the execution. this is an example from the output log:

```
Processing triggers for dbus (1.10.6-1ubuntu3.4) ...
+ break
+ echo Executed '"apt-get' -y install realmd sssd sssd-tools samba-common samba samba-common python2.7 samba-libs 'packagekit"' 1 times
Executed "apt-get -y install realmd sssd sssd-tools samba-common samba samba-common python2.7 samba-libs packagekit" 1 times
+ wait_for_apt_locks
+ fuser /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock
+ echo '<searchDomainRealmPassword>'
++ echo '<searchDomainName>'
++ tr /a-z/ /A-Z/
+ realm join -U '<SEARCHDOMAINNAME>'
/opt/azure/containers/setup-custom-search-domains.sh: line 10: searchDomainRealmUser: No such file or directory
root@k8s-master-34763407-0:/opt/azure/containers#
```

So I guess kubelet.sh should somehow run before setup-custom-search-domain.sh because during the execution it won't update the script with sed and apply it to the current execution. Below are the logs to better understand

```
+ source /opt/azure/containers/kubelet.sh
++ set -e
++ sed -i 's|<img>|k8s.gcr.io/kube-addon-manager-amd64:v8.7|g' /etc/kubernetes/manifests/kube-addon-manager.yaml
++ for a in '"/etc/kubernetes/manifests/kube-apiserver.yaml /etc/kubernetes/manifests/kube-controller-manager.yaml /etc/kubernetes/manifests/kube-scheduler.yaml"'
++ sed -i 's|<img>|k8s.gcr.io/hyperkube-amd64:v1.12.8|g' /etc/kubernetes/manifests/kube-apiserver.yaml /etc/kubernetes/manifests/kube-controller-manager.yaml /etc/kubernetes
/manifests/kube-scheduler.yaml
++ a=/etc/kubernetes/manifests/kube-apiserver.yaml
++ sed -i 's|<args>|"--advertise-address=<advertiseAddr>", "--allow-privileged=true", "--anonymous-auth=false", "--audit-log-maxage=30", "--audit-log-maxbackup=10", "--audit
-log-maxsize=100", "--audit-log-path=/var/log/kubeaudit/audit.log", "--audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml", "--authorization-mode=Node,RBAC", "--bind
-address=0.0.0.0", "--client-ca-file=/etc/kubernetes/certs/ca.crt", "--cloud-config=/etc/kubernetes/azure.json", "--cloud-provider=azure", "--enable-admission-plugins=Namesp
aceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration", "--enable-bootstra
p-token-auth=true", "--etcd-cafile=/etc/kubernetes/certs/ca.crt", "--etcd-certfile=/etc/kubernetes/certs/etcdclient.crt", "--etcd-keyfile=/etc/kubernetes/certs/etcdclient.ke
y", "--etcd-servers=https://<etcdEndPointUri>:2379", "--insecure-port=8080", "--kubelet-client-certificate=/etc/kubernetes/certs/client.crt", "--kubelet-client-key=/etc/kube
rnetes/certs/client.key", "--profiling=false", "--proxy-client-cert-file=/etc/kubernetes/certs/proxy.crt", "--proxy-client-key-file=/etc/kubernetes/certs/proxy.key", "--repa
ir-malformed-updates=false", "--requestheader-allowed-names=", "--requestheader-client-ca-file=/etc/kubernetes/certs/proxy-ca.crt", "--requestheader-extra-headers-prefix=X-R
emote-Extra-", "--requestheader-group-headers=X-Remote-Group", "--requestheader-username-headers=X-Remote-User", "--secure-port=443", "--service-account-key-file=/etc/kubern
etes/certs/apiserver.key", "--service-account-lookup=true", "--service-cluster-ip-range=10.0.0.0/16", "--storage-backend=etcd3", "--tls-cert-file=/etc/kubernetes/certs/apise
rver.crt", "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_12
8_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_
RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", "--tls-private-key-file=/etc/kubernetes/certs/apiserver.key", "--v=4"|g' /etc/kubernetes/manifests/kube-apise
rver.yaml
++ sed -i 's|<etcdEndPointUri>|127.0.0.1|g' /etc/kubernetes/manifests/kube-apiserver.yaml
++ sed -i 's|<advertiseAddr>|10.240.10.1|g' /etc/kubernetes/manifests/kube-apiserver.yaml
++ sed -i 's|<args>|"--allocate-node-cidrs=false", "--cloud-config=/etc/kubernetes/azure.json", "--cloud-provider=azure", "--cluster-cidr=10.240.0.0/12", "--cluster-name=tes
tabutalebdns", "--cluster-signing-cert-file=/etc/kubernetes/certs/ca.crt", "--cluster-signing-key-file=/etc/kubernetes/certs/ca.key", "--configure-cloud-routes=false", "--co
ntrollers=*,bootstrapsigner,tokencleaner", "--feature-gates=LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true", "--kubeconfig=/var/lib/kubelet/kubeconfig", "--lea
der-elect=true", "--node-monitor-grace-period=40s", "--pod-eviction-timeout=5m0s", "--profiling=false", "--root-ca-file=/etc/kubernetes/certs/ca.crt", "--route-reconciliatio
n-period=10s", "--service-account-private-key-file=/etc/kubernetes/certs/apiserver.key", "--terminated-pod-gc-threshold=5000", "--use-service-account-credentials=true", "--v
=2"|g' /etc/kubernetes/manifests/kube-controller-manager.yaml
++ sed -i 's|<args>|"--kubeconfig=/var/lib/kubelet/kubeconfig", "--leader-elect=true", "--profiling=false", "--v=2"|g' /etc/kubernetes/manifests/kube-scheduler.yaml
++ sed -i 's|<img>|k8s.gcr.io/hyperkube-amd64:v1.12.8|g; s|<CIDR>|10.240.0.0/12|g; s|<kubeProxyMode>|iptables|g' /etc/kubernetes/addons/kube-proxy-daemonset.yaml
++ KUBEDNS=/etc/kubernetes/addons/kube-dns-deployment.yaml
++ sed -i 's|<img>|k8s.gcr.io/coredns:1.5.0|g; s|<domain>|cluster.local|g; s|<clustIP>|10.0.0.10|g' /etc/kubernetes/addons/coredns.yaml
++ sed -i 's|<kubeClusterCidr>|10.240.0.0/12|g' /etc/kubernetes/addons/calico-daemonset.yaml
++ sed -i /initContainers/,/cni-net-dir/d /etc/kubernetes/addons/calico-daemonset.yaml
++ sed -i 's|<searchDomainName>|porthit.com|g; s|<searchDomainRealmUser>|abutaleb|g; s|<searchDomainRealmPassword>|passowrd|g' /opt/azure/containers/setup-custom-search-doma
ins.sh
+ echo '  dns-search <searchDomainName>'
+ tee -a /etc/network/interfaces.d/50-cloud-init.cfg
  dns-search <searchDomainName>
+ systemctl_restart 20 5 10 networking
```

**Pull request closed without merging**
